### ISSUE TITLE
Add "Select an Identifier/Filename" to Edit Mode GUI

### ISSUE THREAD

**Issue by epiil** [amiaopensource/vrecord#10]
I see that an Identifier can be added on the command line once a user proceeds from the Edit GUI. Was there a reason why it couldn't be created while still in the GUI?

![screen shot 2015-10-16 at 1 09 46 pm](https://cloud.githubusercontent.com/assets/2568978/10548242/3d09eaf8-7407-11e5-8391-4e9cb93df523.png)

**Comment by dericed** [comment]
I guess it wasn't because that value would (hopefully) change at every recording. The idea was to set everything that is non-variable in the GUI then get interviewed on the varying things, as the filename would presumably always vary.

**Comment by epiil** [comment]
Ah I see, that makes sense for batch transfers. For those doing standalone transfers via the GUI (perhaps a group of users might be considering this?), I'm wondering if it's worthwhile to add an Identifier field with the option of leaving it undeclared, to be prompted for it later.

**Comment by dericed** [comment]
The GUI is more so for managing static preferences rather than specifics about the next recording. Closing this for now though it's feasible a future iteration could have a preference gui and a next-recording gui and thus more so avoid the CLI.
