### ISSUE TITLE
favor sdl output over ffplay during recording

### ISSUE THREAD

**Issue by dericed** [amiaopensource/vrecord#106]
Currently vrecord uses tee and pipes to pass the output of bmdcapture in two directions, such as (paraphrasing from https://github.com/amiaopensource/vrecord/blob/1506a512b4ecc3ea53436b9f51072fc2d9129612/vrecord#L1112-L1129):

```
mkfifo PIPE2QCTOOLS
bmdcapture [...] -F nut -f pipe:1 | tee >(ffplay -i - [...]) | ffmpeg [...] -i - PRIMARYOUTPUT -f nut -y PIPE2QCTOOLS | ffprobe -f lavfi "movie=PIPE2QCTOOLS:s=v+a,signalstats" -show_frames -show_versions -of xml=x=1:q=1 -noprivate | gzip > QCTOOLSOUTPUT
```

With the new sdl install via ffmpeg in homebrew, I think this could be simplified to cut out ffplay, such as:

```
mkfifo PIPE2QCTOOLS
bmdcapture [...] -F nut -f pipe:1 | ffmpeg [...] -i - PRIMARYOUTPUT -f sdl [output window output] - -f nut -y PIPE2QCTOOLS | ffprobe -f lavfi "movie=PIPE2QCTOOLS:s=v+a,signalstats" -show_frames -show_versions -of xml=x=1:q=1 -noprivate | gzip > QCTOOLSOUTPUT
```

**Comment by retokromer** [comment]
👍

**Comment by privatezero** [comment]
Would this still support listening to the audio stream while digitizing?

**Comment by dericed** [comment]
@privatezero O_O it's doesn't seem like sdl takes audio as an input

**Comment by privatezero** [comment]
😢😢😢😢

**Comment by dericed** [comment]
ya, given that the ffmpeg sdl output doesn't play audio, then we'd still have to pipe out to ffplay or mpv. closing for now.
