### ISSUE TITLE
start contributing.md

### ISSUE THREAD

**Issue by dericed** [amiaopensource/vrecord#115]
Since we have contributors and since the content of the repo has licenses, we should draft a contributing.md document to guide/encourage the contributors.

**Comment by privatezero** [comment]
This sounds like a good plan!  Anything in particular that you think would be valuable to put in this?  Code of conduct e.g. http://contributor-covenant.org/?  Style requirements for cowsay use?

**Comment by dericed** [comment]
There's a good example in https://github.com/amiaopensource/amia-org/blob/master/CONTRIBUTING.md

**Comment by retokromer** [comment]
Can this be closed?

**Comment by privatezero** [comment]
Seems like since we now have a contributing doc that it can!

**Comment by retokromer** [comment]
Thanks, I’m trying to clean-up a little…
