### ISSUE TITLE
update doc to gui mode

### ISSUE THREAD

**Issue by dericed** [amiaopensource/vrecord#122]
[This](https://github.com/amiaopensource/vrecord#gui-mode) should be updated per https://github.com/amiaopensource/vrecord/pull/121#issuecomment-265864973

**Comment by privatezero** [comment]
updated in https://github.com/amiaopensource/vrecord/commit/a895003ae883f7e252c0146724d52f268b14e62e!

**Comment by libbyhopfauf** [comment]
Do you mean add in a logo for the Color Matrix mode?
