### ISSUE TITLE
Clean up Pashua GUI

### ISSUE THREAD

**Issue by jfarbowitz** [amiaopensource/vrecord#13]
Since we've added more options the GUI is looking a bit cluttered.

**Comment by jfarbowitz** [comment]
It's partially cleaned up as of cca15e4 written by @dinahhandel and me.

**Comment by epiil** [comment]
boooo I just submitted a PR for this

**Comment by jfarbowitz** [comment]
Sorry, I'll take a look at your pull request and see how it looks. You probably did a better job than we did.

**Comment by jfarbowitz** [comment]
It looks alot cleaner than our version. I just merged it. Maybe standard could be moved down slightly...

**Comment by epiil** [comment]
Thanks!

**Comment by jfarbowitz** [comment]
Just fixed standard in 90ebd24. This bug is squashed for now!
