### ISSUE TITLE
call of vrecord’s man (help_button)

### ISSUE THREAD

**Issue by retokromer** [amiaopensource/vrecord#130]
In my opinion, the line https://github.com/amiaopensource/vrecord/blob/master/vrecord#L157 is wrong:
- On one hand, without a break, one can read the help message `PRESS Q TO EXIT` only **after** having exited the man.
- On the other hand, I guess the escape should read `\033[0m` instead of `\033]0;`.
- On the third hand, why bells here?

Sorry.

**Comment by retokromer** [comment]
Perhaps something like:
```echo "Press [q] to exit from the man page" && sleep 4 && man vrecord && _master_gui```

**Comment by privatezero** [comment]
Hi! That command was written to change the title of the terminal window to display the instructions "PRESS Q TO EXIT" and then to reset the window title after the man page was exited.  Is it not behaving in this way on your computer?

**Comment by retokromer** [comment]
Ah, thank you very much, @privatezero, for the explanation! No, on my terminal it does not work that way, because I use it... for other purposes (it displays the usage of the CPUs and GPUs). Then it's fine, and I close the issue.
