### ISSUE TITLE
[wish] improve man page

### ISSUE THREAD

**Issue by retokromer** [amiaopensource/vrecord#142]
- list the possible parameters of `-e`
- indicate what are the default values of those parameters

@privatezero Is it possible to open the Pashua windows with the defaults selected? I guess, this would be useful for the user.

**Comment by privatezero** [comment]
I'll look into this on Monday when I am back at my work computer!

**Comment by retokromer** [comment]
No hurry! Thank you!

FYI: Now it opens like:

<img width="913" alt="screenshot" src="https://cloud.githubusercontent.com/assets/3246607/26026090/65d126dc-37f5-11e7-93bf-d322efe4af14.png">

and may be intimidating. I guess, having the defaults checked would be better, because the user has only to change when needed.

**Comment by retokromer** [comment]
[This](https://github.com/amiaopensource/vrecord/pull/144) does not resolve the issue I have addressed, but… it’s a first step in that direction.

**Comment by privatezero** [comment]
It looks like vrecord in its current form can't really support defaults as it is designed to either store previous values or to prompt for input if a value is left blank.

Perhaps specific initial configurations is something that could be more explicitly addressed in the documentation?

**Comment by retokromer** [comment]
Ah, yeah, sorry! I have added default values in the `vrecord` variant I was testing on Windows. I will back port this here on macOS, and open a PR.
