### ISSUE TITLE
wishlist - deck control

### ISSUE THREAD

**Issue by bturkus** [amiaopensource/vrecord#145]
putting it out there for the future

**Comment by ablwr** [comment]
So excited for you to learn to code and start implementing these wishes yourself :D

**Comment by bturkus** [comment]
haha. yeah, i can see future coding ben now. he's so incredible! first I gotta do my ffmprovisr contribution

**Comment by retokromer** [comment]
Do you mean graphically, or just the functionality?

**Comment by ablwr** [comment]
Cyborg-Ben will be a both graphical and functional upgrade, I hope!

**Comment by retokromer** [comment]
A cross-platform GUI would be tricky to programme in Bash… we should rewrite the code then.

**Comment by ablwr** [comment]
@privatezero knows about this based on his GUI-work with audiorecorder!

**Comment by retokromer** [comment]
Hmm… I have been unable to do it in the modified version of `vrecord`, that is running also on the Windows Subsystem for Linux and also works with AJA Video Systems cards. Yet if someone has a better idea, of course, I am more than happy!

**Comment by privatezero** [comment]
one of the next things I am planning on trying to dive into deeper is a good cross platform gui that could work for vrecord and audiorecorder. In the meantime, I am using `dialog` for the audiorecorder "GUI" in linux. Party like it's 1989!

![image](https://cloud.githubusercontent.com/assets/12941699/26465034/a0fa07ea-413e-11e7-8bb0-f812e2b36fa6.png)

**Comment by ablwr** [comment]
This looks doooopppppeeeee.

**Comment by retokromer** [comment]
I feel younger!

**Comment by dericed** [comment]
Hi, we have deckcontrol for blackmagic implemented in https://github.com/bavc/deckcontrol. This allows a CLI to do deck control. Could you be more specific on how you envision the integration.

**Comment by bturkus** [comment]
To be honest, I don't have much of a grand vision, but we're moving to vrecord sometime over the next few weeks, and one our engineers expressed an interest in device control (our decks are on one side of the room; computers the other). I'm not sure what Pashua (or different a cross-platform solution) would be capable of, but I guess I was picturing the following:

Some method of turning device control on/off
Some method of indicating whether device is online/not
A capture panel with standard options (rewind, fast forward, play/pause, record/capture, etc.)

Deck control also raises some questions related to timecode. I know it's a separate issue, #51, and that there are hurdles related to bmdtools, ffmpeg, and the capabilities of various output formats (see recent Cellar conversation), but there is a connection point here, right?

**Comment by ablwr** [comment]
@bturkus Sounds like something your place of work should consider contributing towards, either by finding someone to do that work or by funding a feature request!

**Comment by retokromer** [comment]
Thank you for the information!

**Comment by bturkus** [comment]
@ablwr I totally agree. It's an idea that I'm actively bringing up in conversation. To be clear: when I send in vrecord issues, I'm thinking more "compiling a list of improvements" for a hopefully sponsored or supported future, less "someone get started on this now."

**Comment by dericed** [comment]
A pashua interface to the deckcontrol utility wouldn't be too hard. Patches welcome. :)

**Comment by retokromer** [comment]
@bturkus FYI I would like to make a new release before Tuesday (meetings at _The Reel Thing_ in Amsterdam) with only little changes https://github.com/amiaopensource/vrecord/compare/v0.7.28...master

@dericed Pashua is not a cross-platform solution if I am not completely wrong.

**Comment by thejackiejay** [comment]
@dericed Would love to see vRecord map buttons in the GUI to control the deck via an RS-422 cable.

**Comment by dericed** [comment]
we support deckcontrol now via rs422 via https://github.com/bavc/deckcontrol/ or via avfctl, so closing as resolved.

**Comment by thejackiejay** [comment]
Woohoo! Thanks.

Jackie Jay
*Audiovisual Archivist and Educator*
thejackiejay@gmail.com
415-615-2463
