### ISSUE TITLE
"muxers is deprecated" message at bottom of capture window

### ISSUE THREAD

**Issue by kellyhaydon** [amiaopensource/vrecord#149]
Some odd messages in the capture window - is this something to be concerned about? I noticed it when I reinstalled vrecord today. 

![screen shot 2017-06-06 at 12 17 45 pm](https://user-images.githubusercontent.com/9436241/26848254-9b7ad20c-4ab4-11e7-9057-75d80836c030.png)

**Comment by privatezero** [comment]
This seems related to this recent merge https://github.com/amiaopensource/vrecord/pull/108.

Was supposed to provide a visual dropped frame warning - looks like some of the commands it is using have been deprecated? That is where that warning would be coming from I think, but I am not familiar with the guts of that particular merge.

**Comment by dericed** [comment]
That's drawtext writing the last x lines from one of the logs, so it's including a warning about the use of nut in the pipe between bmdcapture and ffmpeg.

**Comment by retokromer** [comment]
I guess, the warning is created here: https://github.com/FFmpeg/FFmpeg/blob/master/libavformat/mux.c#L298

**Comment by retokromer** [comment]
Is `bmdcapture` up-to-date?

**Comment by retokromer** [comment]
What is the status of this issue?

**Comment by richardpl** [comment]
The source of that message needs updating to new api or it will stop working on next FFmpeg API bump.

**Comment by retokromer** [comment]
Is someone working on this? FFmpeg 3.4 or 4.0 should be released in a near future.

**Comment by richardpl** [comment]
Someone need to fix bmdcapture.

**Comment by retokromer** [comment]
vrecord is currently using bdmcapture [v0.2alpha](https://github.com/amiaopensource/bmdtools/releases/tag/v0.2alpha), made on 2016-03-01 by @dericed from @lu-zero‘s repository.

In the meantime, on 2017-03-20, Luca made a [First Pre-release of the second formal release](https://github.com/lu-zero/bmdtools/releases/tag/v0.2).

**Comment by dericed** [comment]
closing as bmdcapture is no longer used
