### ISSUE TITLE
Incompatible codecs/containers selectable

### ISSUE THREAD

**Issue by kieranjol** [amiaopensource/vrecord#15]
From my experience, FFv1 (and possibly v210 and prores?) are not currently compatible with .MXF. 
Perhaps a warning could pop up if these options are selected when using the CLI. I'm not sure how difficult it would be to prevent a user from selecting MXF in the GUI if an incompatible codec is selected?

**Comment by jfarbowitz** [comment]
Dave, are you aware of which codecs/containers are incompatible?

**Comment by dericed** [comment]
Right ffv1 is not usable in MXF (who wants to draft a SMPTE spec?). But right with certain combinations the configuration should be considered invalid.
