### ISSUE TITLE
Where is `xmlstarlet` used?

### ISSUE THREAD

**Issue by retokromer** [amiaopensource/vrecord#158]
If it should not be used, I will delete it here and in the formula. cc @dericed

**Comment by privatezero** [comment]
It is used for some of the built in QC warnings to parse the QCTools report, for example here:

https://github.com/amiaopensource/vrecord/blob/master/vrecord#L1245

**Comment by retokromer** [comment]
Ah, `xml` is an alias of `xmlstarlet`. Thank you!
