### ISSUE TITLE
[wish] GUI menu tweaks

### ISSUE THREAD

**Issue by EG-tech** [amiaopensource/vrecord#159]
Hi guys!

The vrecord GUI mode is super helpful for showing off vrecord to less experienced or command-line-shy users, but I was wondering if it would be possible to return to the GUI menu and select more than one option per vrecord session.

e.g. if you launch the GUI and select "Passthrough", when you're done with passthrough mode and exit the preview window, vrecord closes and you have to relaunch the GUI to select Record or Edit Settings (since it's just purely executing `$ vrecord -p`)

or, selecting "Edit Settings" goes straight on through to record mode once you've selected your configuration - where a new user might expect to set preferences, then return to the main menu before hitting "Record"

Just a few small thoughts! Thanks as always for the incredible work.

**Comment by privatezero** [comment]
Makes sense! Shouldn't be that tricky to tweak it a bit!

**Comment by libbyhopfauf** [comment]
I would also love this!

**Comment by aeschweik** [comment]
Hello all, I put some of these ideas into a PR (#299) and would love feedback if anyone can test!

**Comment by aeschweik** [comment]
Addressed in #299
