### ISSUE TITLE
Question about color_trc options

### ISSUE THREAD

**Issue by kieranjol** [amiaopensource/vrecord#162]
Hi, I was looking at the colour metadata options in vrecord:

https://github.com/amiaopensource/vrecord/blob/master/vrecord#L1203-L1221

I'm just curious why bt709 was picked for the color_trc? I know very little about this stuff, but isn't that used for HD video?

Looking at the list here: https://github.com/FFmpeg/FFmpeg/blob/d14179e3d49eb0f2533db16151e01abb0018b165/libavutil/pixfmt.h#L437
It seems that there are values for SD PAL/NTSC respectively (Gamma 22 and 170M). Again, I don't know enough about what these specific values do (aside from determining the YCbCr -> RGB transform) to know the reasoning, so any information would be really informative.

**Comment by retokromer** [comment]
Using Rec. 709, unlike Rec. 601, allows the R′G′B′ coefficients to match the primaries and white point. This way luma corresponds more closely to luminance.

**Comment by dericed** [comment]
I'm QuickTime's colr atom the transfer function for ITU-R BT.709-2, SMPTE 274M-1995, 296M-1997, 293M-1996, and 170M-1994 are all stored as the same integer value. Matroska's list is more granular since it's based on ISO/IEC 23001-8:2013/DCOR1 and anticipated proposals. I guess in MKV color_trc = 6 (SMPTE170m) could be used, but IIUC that's simply the same transform as color_trc = 1 (bt.709) under a different label. Ping to @jeromemartinez

**Comment by retokromer** [comment]
(We’ve reviewed ISO/IEC 23001-8 quite recently, last year or so.)

**Comment by JeromeMartinez** [comment]
BT.709 and SMPTE 170M are same for transfer characteristics and matrix coefficients, right (but not for colour primaries), color_trc could be smpte170m here for more coherency (this is the reason ISO uses different numbers for same formulas), functionally same.

**Comment by dericed** [comment]
Seems issue is only cosmetic then.

**Comment by retokromer** [comment]
The issue is not only cosmetic: it depends if you are working according to Rec. 601 or to Rec. 709, this is not the same.

**Comment by JeromeMartinez** [comment]
Mostly cosmetic, except that some people check the exact value, and expect the same value for the 3 fields else consider the stream as potentially wrong.

**Comment by dericed** [comment]
Maybe we need to see ISO/IEC motivation to split the same transfer into two different labels (where other av containers have SMPTE170m and bt709 as transfer with the same label).

**Comment by dericed** [comment]
@retokromer the equations are identical, the same inputs will create the same outputs

**Comment by JeromeMartinez** [comment]
> The issue is not only cosmetic: it depends if you are working according to Rec. 601 or to Rec. 709, this is not the same.

How? The formula is same for transfer characteristics in both specs.
ISO says "functionally the same".

**Comment by retokromer** [comment]
@dericed As said [above](https://github.com/amiaopensource/vrecord/issues/162#issuecomment-317716577) Rec. 709 makes more sense IRL because of luma.

**Comment by JeromeMartinez** [comment]
> Rec. 709 makes more sense IRL because of luma.

I don't understand, primaries and white point are in colour primaries field (which are different between BT.709 and SMPTE 170M), not transfer characteristics (the fields were talking about, aren't we?)

**Comment by retokromer** [comment]
A discussion of the related metadata problems may be found in Charles Poynton: _Digital Video and HD: Algorithms and Interfaces_ (2<sup>nd</sup> edition), p. 171–180.

**Comment by dericed** [comment]
From ISO documentation on transfer characteristics, both 1 (bt709) and 6 (bt.601) give identical equations:

```
V = 1.099 L_c^0.45 – 0.099
    for 1 ≥ L_c ≥ 0.018
V = 4.500 L_c
    for 0.018 > L_c ≥ 0
```

and

```
V = 1.099 L_c^0.45 – 0.099
    for 1 ≥ L_c ≥ 0.018
V = 4.500 L_c
    for 0.018 > L_c ≥ 0
```

and as Jerome note, ISO states clearly in regards to `6` (bt.601) that "functionally the same as the value 1" (bt.709).

The cited document by Poynton is behind a paywall.

**Comment by dericed** [comment]
citation for above quotation and equations: https://webstore.iec.ch/corrigenda/iso/isoiec14496-2-amd3-cor1%7Bed3.0%7Den.pdf.

**Comment by kieranjol** [comment]
I am holding a copy of Poynton's book in my hand but I probably shouldn't scan it.
FWIW: Here's what he says on pg 178:

> In light of all this confusion, how should an encoder be configured? For SD material, set the primaries to EBU 3213 for 576i material, and to SMPTE RP 145 for 480i material; set transfer characteristics to BT.709 and matrix coefficiencts to BT.601

**Comment by JeromeMartinez** [comment]
> For SD material, set the primaries to EBU 3213 for 576i material, and to SMPTE RP 145 for 480i material; set transfer characteristics to BT.709 and matrix coefficiencts to BT.601

Functionally same as "For SD material, set the primaries to BT.601 PAL for 576i material, and to  BT.601 NTSC for 480i material; set transfer characteristics to BT.601 and matrix coefficients to BT.601"

I don't catch the difference (my version is just "full BT.601", easier to read IMHO because BT.601 is known for being focused on SD content, but technically same, same numbers in every equations)

**Comment by dericed** [comment]
@kieranjol, status of issue?

**Comment by kieranjol** [comment]
This was a most informative issue.
