### ISSUE TITLE
GUI Audio Passthrough Issue

### ISSUE THREAD

**Issue by libbyhopfauf** [amiaopensource/vrecord#166]
Since the 2017-07-15 vrecord update, when using the GUI if I try to run the audio passthrough mode, a blank mpv screen opens instead. If I type the vrecord -a command into the terminal instead, the audio passthrough mode will open like it is supposed to. I have attached an image of the mpv screen below. Thanks!

![broken_gui_audio](https://user-images.githubusercontent.com/13877631/28886500-960a6c42-776e-11e7-8a38-6f6dcd5abb61.png)

**Comment by retokromer** [comment]
Thank you, @libbyhopfauf, for reporting!

**Comment by retokromer** [comment]
@privatezero I guess, you know Pashua and the GUI much better than I do…

**Comment by privatezero** [comment]
I have limited access to test equipment right now, but I'll see what I can do!

**Comment by retokromer** [comment]
Thank you! I currently do not have access to a test setting at all…

**Comment by retokromer** [comment]
@privatezero I’m not intending to push pressure on you, but just FYI: If this is resolved soon, then I will made a new release for the next teachings.

**Comment by privatezero** [comment]
@retokromer I think I know the root of the problem (the gui declares sets runtype to audiopassthrough after the check for the filterchain leading to the filterchain not being set correctly for mpv).

I still have no means of testing (currently in Japan and very far from access to a Blackmagic), but I will try to make some changes and maybe I can ping @libbyhopfauf to test them out!

**Comment by privatezero** [comment]
theoretically I the change in this branch ought to fix this: https://github.com/amiaopensource/vrecord/tree/fix-gui

Any thoughts?

**Comment by retokromer** [comment]
@privatezero Ha! I am currently travelling in Norway… Thank you for the hint! I can cross-check your fix on my side: it’s theoretically too, but I thinks we should succeed. Thanks again – and sorry for boring you.
