### ISSUE TITLE
support packaging the resulting files

### ISSUE THREAD

**Issue by dericed** [amiaopensource/vrecord#17]
Currently the output is like:
```
${MEDIAID}.${EXTENSION}
${MEDIAID}_log1
${MEDIAID}_log2
${MEDIAID}_log3
```

I propose an option or possibly a default of organizing these files in a directory structure instead, such as (Archivematica SIP style)

```
${MEDIAID}/objects/${MEDIAID}.${EXTENSION}
${MEDIAID}/metadata/submissionDocumentation/logs/${MEDIAID}_log1
${MEDIAID}/metadata/submissionDocumentation/logs/${MEDIAID}_log2
${MEDIAID}/metadata/submissionDocumentation/logs/${MEDIAID}_log3
```

**Comment by jfarbowitz** [comment]
I think I can figure out how to do this...

**Comment by dericed** [comment]
Or perhaps this is more clear, but requires asking for the id of the tape (media) and the id of the package.

${PACKAGEID}/objects/${MEDIAID}.${EXTENSION}
${PACKAGEID}/metadata/submissionDocumentation/logs/${MEDIAID}_log1
${PACKAGEID}/metadata/submissionDocumentation/logs/${MEDIAID}_log2
${PACKAGEID}/metadata/submissionDocumentation/logs/${MEDIAID}_log3

**Comment by jfarbowitz** [comment]
Is it likely that the package is going to have a different ID from the media?

**Comment by CSchloss385** [comment]
Hey Jonathan! Before you start on this, I want to think through the workflow a little bit. Trying to figure out if this is worth changing.

**Comment by jfarbowitz** [comment]
No problem.

**Comment by jfarbowitz** [comment]
This was closed as the feature is not currently needed. No work was done on this.
