### ISSUE TITLE
add mediaconch check after digitization

### ISSUE THREAD

**Issue by dericed** [amiaopensource/vrecord#171]
I think having a mediaconch policy check after digitization could reduce the risk of a change to any of the underlying components causing an unintended result. The output of vrecord is fairly strict so I think a complex 'or' policy could cover all possible outputs and check combinations of frame size, stream interlacement, and codec interlacement.

**Comment by ablwr** [comment]
I hear MediaConch is great at this!

**Comment by retokromer** [comment]
_patch welcome_

**Comment by dericed** [comment]
resolving in https://github.com/amiaopensource/vrecord/pull/241
