### ISSUE TITLE
Any interest in creating two outputs during capture?

### ISSUE THREAD

**Issue by kieranjol** [amiaopensource/vrecord#181]
I don't know enough about the bmdtools/ffmpeg pipeline, but it looks like combining the creation of a master file (ffv1/mkv) and a mezzanine (prores/mov) at the same time is doable? 
https://github.com/amiaopensource/vrecord/blob/master/vrecord#L1230

It looks as if adding, for example,  `-c:v prores -map 0 prores.mov` to the final ffmpeg command could achieve this. I plan on testing this out when I get some time and access to a mac capture station, but I was just curious if this was the kind of thing where a patch might be welcome, or is it overkill when a subsequent transcode could just be performed? I'd imagine that finding space in the `vrecord -e` GUI might be trick as well.

I'm working with a colleague who needs a prores file for their exhibition workflow, but we need an FFV1/MKV file for our needs. I was going to just knock up a quick script, but I would like to pilot the use of vrecord in our workflow for this particular test.

**Comment by privatezero** [comment]
I know that @libbyhopfauf at Moving Image Preservation of Puget Sound (MIPoPS) was using a modified version of vrecord that created an h264 derivative on capture, so it definitely seems feasible (although I do recall prores being more intensive to encode so hopefully that wouldn't cause to much drag on the capture stream!)

**Comment by kieranjol** [comment]
Thanks @privatezero! I was actually thinking that proxy generation would also be interesting, but definitely not necessary for what I'm thinking of. I agree that the bottleneck could just be processing power.. I'll let ye know how the testing goes anyhow.

**Comment by retokromer** [comment]
Especially Kostya’s is slow.

**Comment by kieranjol** [comment]
Aye, but better for interlaced material?

**Comment by retokromer** [comment]
Better in general, except speed…

**Comment by kieranjol** [comment]
A quick test worked just fine anyhow. System resources weren't an issue, though I didn't try `prores_ks`. I might look into this a bit more when I have some time and I might send in a pull request if I end up working on it. I think I can close this for now.

**Comment by bturkus** [comment]
very exciting!

**Comment by privatezero** [comment]
Just to play devil's advocate - aren't there some disadvantages to creating what I assume are access files at point of capture? 

To do things like trim heads/tails, normalization of audio, application of deinterlacing filters etc. would still require additional manipulation that other software is more suited for.

I admit I am a bit of a fan of the ['Do one thing and do it well'](https://en.wikipedia.org/wiki/Unix_philosophy#Do_One_Thing_and_Do_It_Well) philosophy, but isn't vrecord's strength more in capture of preservation files rather than other parts of the file processing chain?

**Comment by dericed** [comment]
@iamdamosuzuki can you review this issue. Anything left or can it be closed?

**Comment by iamdamosuzuki** [comment]
I'm very happy with the results of this! Right now it only creates MP4s, not ProRes as requested by @kieranjol but it meets the needs of LC. 

@privatezero your comments are very thoughtful and certain are worth considering. I do think it's worthwhile to keep more intervention-heavy processes like trimming bars and normalizing to other software. However, as it stands the one-to-one MP4s that vrecord can create now are used by a lot of labs, and this will save a lot of time in post-processing.

**Comment by privatezero** [comment]
@iamdamosuzuki glad it's useful!
