### ISSUE TITLE
test to see if vrecord can be installed on linux?

### ISSUE THREAD

**Issue by jfarbowitz** [amiaopensource/vrecord#19]

**Comment by dericed** [comment]
cc @intelligencer

**Comment by jfarbowitz** [comment]
Can use Linuxbrew to install, but what will it do without Pashua?

**Comment by intelligencer** [comment]
I can test this weekend. Is this just for the new GUI or the whole shebang?

**Comment by kieranjol** [comment]
Was this done? I can test with Linuxbrew on ubuntu.

**Comment by jfarbowitz** [comment]
Closing this at the moment as we need to focus on other. If someone else wants to work on it.
