### ISSUE TITLE
Request for single-channel mono audio configuration

### ISSUE THREAD

**Issue by iamdamosuzuki** [amiaopensource/vrecord#195]
The following Audio Channel Mappings are currently available:

- Undeclared
- 2 Stereo Tracks (Channels 1 & 2 -> 1st Track Stereo, Channels 3 & 4 -> 2nd Track Stereo)
- 1 Stereo Track (From Channels 1 & 2)
- 1 Stereo Track (From Channels 3 & 4)
- Channel 1 -> 1st Track Mono, Channel 2 -> 2nd Track Mono
- Channel 2 -> 1st Track Mono, Channel 1 -> 2nd Track Mono 

I would like to request the addition of the following Mappings

- 1 Mono Track (From Channel 1)
- 1 Mono Track (From Channel 2)

**Comment by privatezero** [comment]
So, to clarify, you would like options to ingest with a single mono track (from either channel 1 or 2) instead of the current option which creates two mono tracks, with one possibly ending up blank?

**Comment by dericed** [comment]
Makes sense for all those videotape formats with only one audio channel:
um
...
...
PixelVision
...
maybe that’s it.

**Comment by privatezero** [comment]
I dunno - I was using vrecord to capture telecine which only had mono!

**Comment by kellyhaydon** [comment]
Half inch open feel video is single, *blows raspberry *

**Comment by iamdamosuzuki** [comment]
Thanks Kelly! Also BAVC did some PixelVision recently 😇

**Comment by iamdamosuzuki** [comment]
Thanks Kelly! Also, BAVC did some PixelVision recently... 😇

**Comment by privatezero** [comment]
I should be able to make this tweak in the next day or so - just gotta get back on a mac so I can make sure I am not butchering the pashua gui!

**Comment by privatezero** [comment]
Added via https://github.com/amiaopensource/vrecord/pull/248
