### ISSUE TITLE
Request for Full Range Visual and Numerical

### ISSUE THREAD

**Issue by bturkus** [amiaopensource/vrecord#198]
Greg Lisi, whom I work with a NYPL, mentioned that he thought it'd be awesome if vrecord offered a "full range visual + numerical" view. 

I'd be happy to take a stab at this, if it's as easy as copying the current "visual + numerical" and making a few small tweaks, but I don't wanna look like a total idiot. I'm realizing just now that 33 people watch this repo. Too late!

**Comment by ablwr** [comment]
Greg Lisi, whom I work with at DHC, also has mentioned this feature request. 😂

**Comment by ablwr** [comment]
Only 22 people watch ffmprovisr and now I am filled with jealous rage!

**Comment by kieranjol** [comment]
Id   very much recommend taking a public stab at adding it yourself. Ive
only ever had a positive experience of recieving feedback about my
mistakes,it makes me learn so much more. And pretty much every ffmpeg patch
from seasoned developers gets feedback that requires changes before the
patch is accepted.

**Comment by richardpl** [comment]
What is that "full range visual and numerical view"?

**Comment by bturkus** [comment]
basically, it'd be a combination of views that are already available. something like this, but with full range pixels highlighted in the top right (instead of broadcast range). And I guess the BRNG numbers would be swapped out, or eliminated entirely. 

![vrecord_visual_numerical_2016-11-22](https://user-images.githubusercontent.com/8987230/33849463-a73d84aa-de7e-11e7-8b87-5b122380e57a.jpg)

**Comment by aeschweik** [comment]
Addressed in #298
