### ISSUE TITLE
Edit mode not working in GUI

### ISSUE THREAD

**Issue by libbyhopfauf** [amiaopensource/vrecord#199]
When I try to run the edit mode from the GUI, the record command seems to be run instead. 

![screen shot 2017-12-08 at 3 30 45 pm](https://user-images.githubusercontent.com/13877631/33789438-3454dfc2-dc2d-11e7-8bf5-b9c2973b7b9c.png)

![screen shot 2017-12-08 at 3 18 55 pm](https://user-images.githubusercontent.com/13877631/33789332-a9a64e06-dc2c-11e7-9174-72297bdf6ede.png)

If I type the vrecord -e command into the Terminal manually, then the edit mode GUI opens normally.

**Comment by privatezero** [comment]
It looks like the combining of the gui conditional with the other conditionals in https://github.com/amiaopensource/vrecord/commit/bafff652f6561e0b704dff973b8da705d1248da5 caused this to fail.

Previously `runtype` would be set to `GUI`, then reset to `edit` when the button was pushed. This was followed by a second check on `runtype`.

In the current form `runtype` is set for the gui and then there is no subsequent check for `runtype`, so the script goes straight to recording (even though the gui output sets `runtype` to `edit`.

**Comment by retokromer** [comment]
(Sorry, during my recent use in the wild, I always worked with the CLI only.)

**Comment by privatezero** [comment]
Thank you as always @retokromer! I didn't notice either as I am now in linux land. Once this is fixed (looks like @libbyhopfauf has this covered) I am planning on moving some stuff around to incorporate the suggestions in https://github.com/amiaopensource/vrecord/issues/159. Maybe then the GUI will be a more useful tool for training sessions!

**Comment by retokromer** [comment]
Indeed, that’s an excellent idea, @privatezero! Once https://github.com/amiaopensource/vrecord/pull/190 is merged, I’ll make a new release.

**Comment by libbyhopfauf** [comment]
I fixed the edit mode for the gui and it is now merged
