### ISSUE TITLE
Prevent user from starting new capture when bmdcapture is still running

### ISSUE THREAD

**Issue by CSchloss385** [amiaopensource/vrecord#20]
If bmdcapture is still running, a user can open up a new terminal tab or terminal window and start an entirely new capture. Need to find a way to tell the user that bmdcapture is busy and the user should close the terminal tab in order to proceed with a new capture.

**Comment by jfarbowitz** [comment]
This might be helpful for writing to code: http://www.anyexample.com/linux_bsd/bash/check_if_program_is_running_with_bash_shell_script.xml

**Comment by retokromer** [comment]
ping

**Comment by retokromer** [comment]
@jfarbowitz Are you working on this?
