### ISSUE TITLE
Error message when setting "Set Recording Time" to 0

### ISSUE THREAD

**Issue by GregH18** [amiaopensource/vrecord#206]
Hi all,

I'm not sure how others feel about this, but I thought it might be helpful to have an error message or warning when setting the `set recording time in minutes` to `0`. We ran several tests using a combination of containers and codecs setting the `set recording time in minutes` drop down to `0`, and the video and logs were captured. However, when we started the capture, the line at the bottom that displays recording information while was not scrolling (see the image below). When the `set recording time` drop down is set to something other than `0`, the ffplay window appears and works fine. 
![image02](https://user-images.githubusercontent.com/27779274/33963785-328d755a-e024-11e7-8a3f-7b553a6a77b3.png)

This threw us off at first, and thought this might be a helpful fix so that others don't perceive a problem when there isn't one.

Thanks!

**Comment by dericed** [comment]
Also closed by https://github.com/amiaopensource/vrecord/pull/210
