### ISSUE TITLE
PAL Digitization Failed

### ISSUE THREAD

**Issue by jfarbowitz** [amiaopensource/vrecord#21]
Testers at University of Bern tried digitizing a PAL tape and were not getting a video signal. We traced it to the fact that with their BM capture card PAL is listed as option 1 whereas vrecord currently thinks PAL is 2. 

We need to have vrecord properly look up what number represents the PAL setting and what is NTSC when vrecord starts running and use the correct numbers depending on the user's capture card.

**Comment by jfarbowitz** [comment]
Here's a starting point where we parse the bmdcapture help menu and look for PAL and NTSC values:

bmdcapture -h 2>&1 | grep "[0-9] FPS" | tr '\t' ',' | sed 's/:/,/g;s/FPS//g;s/ //g;s|29.97$|30000/1001|g;s|59.9401$|60000/1001|g;s|23.976|24000/1001|g'

bmdcapture -h 2>&1 | grep "PAL"  | cut -d: -f 1 | sed 's/ //g'
bmdcapture -h 2>&1 | grep "NTSC   "  | cut -d: -f 1 | sed 's/ //g'
bmdcapture -h 2>&1 | grep "NTSC"  | cut -d: -f 1 | sed 's/ //g' | head -n 1

**Comment by kieranjol** [comment]
We did a very quick test with a PAL SD MWA Flashtransfer a few days ago and we didn't get a signal either. As we couldn't devote much time to the test, we moved on, but I assumed that we had something set up incorrectly.
As it stands right now, is vrecord not useable in PAL until this issue is sorted, or is there a workaround?

**Comment by dericed** [comment]
@kieranjol to confirm our theory can you copy/paste the output of your `bmdcapture -h` over here

**Comment by kieranjol** [comment]
Hi Dave, I'm at home now (GMT) so I will shoot that on to you in the morning.

**Comment by jfarbowitz** [comment]
Should now be fixed in e4db310. Vrecord should now be more smart about using the correct numbers for NTSC and PAL.

**Comment by jfarbowitz** [comment]
Waiting for some actual PAL testers to confirm before I close.

**Comment by kieranjol** [comment]
telecine:~ administrator$ bmdcapture -h
Usage: bmdcapture -m <mode id> [OPTIONS]

    -m <mode id>:
-> UltraStudio 4K (-C 0 )

Supported video output display modes and pixel formats:
         0:   NTSC                 	 720 x 486 	   29.97 FPS
         1:   PAL                  	 720 x 576 	      25 FPS
         2:   1080p23.98           	 1920 x 1080 	  23.976 FPS
         3:   1080p24              	 1920 x 1080 	      24 FPS
         4:   1080p25              	 1920 x 1080 	      25 FPS
         5:   1080p29.97           	 1920 x 1080 	   29.97 FPS
         6:   1080p30              	 1920 x 1080 	      30 FPS
         7:   1080i50              	 1920 x 1080 	      25 FPS
         8:   1080i59.94           	 1920 x 1080 	   29.97 FPS
         9:   1080i60              	 1920 x 1080 	      30 FPS
        10:   1080p50              	 1920 x 1080 	      50 FPS
        11:   1080p59.94           	 1920 x 1080 	 59.9401 FPS
        12:   1080p60              	 1920 x 1080 	      60 FPS
        13:   720p50               	 1280 x 720 	      50 FPS
        14:   720p59.94            	 1280 x 720 	 59.9401 FPS
        15:   720p60               	 1280 x 720 	      60 FPS
        16:   1080p23.98 DCI 2K    	 2048 x 1080 	  23.976 FPS
        17:   1080p24 DCI 2K       	 2048 x 1080 	      24 FPS
        18:   1080p25 DCI 2K       	 2048 x 1080 	      25 FPS
        19:   2160p23.98           	 3840 x 2160 	  23.976 FPS
        20:   2160p24              	 3840 x 2160 	      24 FPS
        21:   2160p25              	 3840 x 2160 	      25 FPS
        22:   2160p29.97           	 3840 x 2160 	   29.97 FPS
        23:   2160p30              	 3840 x 2160 	      30 FPS
        24:   2160p23.98 DCI 4K    	 4096 x 2160 	  23.976 FPS
        25:   2160p24 DCI 4K       	 4096 x 2160 	      24 FPS
        26:   2160p25 DCI 4K       	 4096 x 2160 	      25 FPS

    -v                   Be verbose (report each 25 frames)
    -f <filename>        Filename raw video will be written to
    -F <format>          Define the file format to be used
    -c <channels>        Audio Channels (2, 8 or 16 - default is 2)
    -s <depth>           Audio Sample Depth (16 or 32 - default is 16)
    -p <pixel>           PixelFormat Depth (8 or 10 - default is 8)
    -n <frames>          Number of frames to capture (default is unlimited)
    -M <memlimit>        Maximum queue size in GB (default is 1 GB)
    -C <num>             number of card to be used
    -S <serial_device>   data input serial
    -A <audio-in>        Audio input:
                         1: Analog (RCA or XLR)
                         2: Embedded Audio (HDMI/SDI)
                         3: Digital Audio (AES/EBU)
    -V <video-in>        Video input:
                         1: Composite
                         2: Component
                         3: HDMI
                         4: SDI
                         5: Optical SDI
                         6: S-Video
    -o <optionstring>    AVFormat options
Capture video and audio to a file. Raw video and audio can be sent to a pipe to avconv or vlc e.g.:

    bmdcapture -m 2 -A 1 -V 1 -F nut -f pipe:1

**Comment by kieranjol** [comment]
Ah, now that I think of it, vrecord was producing 1080p files as well. We probably have those capture logs saved somewhere if they're of any use, but I think the issue sounds solved?

**Comment by jfarbowitz** [comment]
Testers in Bern have confirmed that it's fixed.

Reopen if there are still issues.
