### ISSUE TITLE
Record mode broken if qctoolsxml output turned off

### ISSUE THREAD

**Issue by privatezero** [amiaopensource/vrecord#217]
@libbyhopfauf discovered that if qctoolsxml output is turned off, record mode will just start piping into the terminal.

It looks like at https://github.com/amiaopensource/vrecord/blob/master/vrecord#L1209 the command was left unfinished and so vrecord just starts to cat the pipe all over the place!

**Comment by retokromer** [comment]
I guess, it’s https://github.com/amiaopensource/vrecord/commit/f46a063226268764ccf418687e2d14ec40da1693
