### ISSUE TITLE
Audio Passthrough Mode Error

### ISSUE THREAD

**Issue by libbyhopfauf** [amiaopensource/vrecord#218]
If I try to run the audio passthrough mode in either the GUI or as a command, I get the following error: 
![screen shot 2017-12-22 at 4 12 05 pm](https://user-images.githubusercontent.com/13877631/34315335-165c3946-e733-11e7-9a85-8de4a93d584c.png)

I tried a fresh install of mpv and tried to locate the proper directory, but I wasn't able to a path that fixed the issue.

**Comment by privatezero** [comment]
This probably is an issue with vrecord switching over to the ffmpeg decklink device and mpv rejecting something due to slightly different syntax - I don't think it is a problem on your end!

**Comment by retokromer** [comment]
The bug should have been introduced with https://github.com/amiaopensource/vrecord/commit/8f6a31be7cbab07ebceb85fc076ef1cb0338a5f4, but I could not find it so far. Any hint, @dericed?

**Comment by privatezero** [comment]
I don't have a blackmagic device right now, so can't test fully, but I have been throwing raw yuv422p10 (which should be the output of the decklink pipe, right?) at the audiopassthrough mpv filter, and have not been able to recreate the problem. Hmm, strange!!

**Comment by privatezero** [comment]
Is it possible that something could have gotten out of whack in the /etc/mpv/encoding-profiles.conf file? I seem to recall that Homebrew doesn't replace configs in the /etc/ directory when reinstalling things.

**Comment by retokromer** [comment]
Do you mean mpv‘s [formula](https://github.com/Homebrew/homebrew-core/blob/df8948aa6045ad8b3617a97d485077e5ae093e4a/Formula/mpv.rb#L71)? Then it should, I guess.

**Comment by privatezero** [comment]
Oh, I always interpreted that location to imply persistent configs as per: https://github.com/Homebrew/brew/blob/master/docs/Formula-Cookbook.md#handling-files-that-should-persist-over-formula-upgrades

Either way, this could be totally off though. I just noticed when googling around for people having similar issues that some assumed it was a broken config file.

**Comment by retokromer** [comment]
Currently (and during the next days as well) I cannot access to a Blackmagic device neither. Personally I tend to think that it’s related to a wrongly set parameter.
