### ISSUE TITLE
`lookup_framemd5` and `lookup_qctoolsxml` are identical

### ISSUE THREAD

**Issue by retokromer** [amiaopensource/vrecord#231]
The [functions](https://github.com/amiaopensource/vrecord/blob/master/vrecord#L465-L485) `lookup_framemd5` and `lookup_qctoolsxml` are identical, therefore they could be replaced by one `yes_or_no` function. If there is agreement, I will make a PR.

**Comment by retokromer** [comment]
```
yes_or_no(){
    case "${1}" in
        "Yes"|"No") ;;
        "quit") _report -d "Bye then" ; exit 0 ;;
        *) _report -w "Error: Not a valid option, select a valid number." ; return 1 ;;
    esac
}
```

**Comment by kieranjol** [comment]
+1 this rings a bell from when I was looking deeper into the vrecord source
code.
