### ISSUE TITLE
Escape button does not stop the transfer

### ISSUE THREAD

**Issue by michi-gato** [amiaopensource/vrecord#237]
VHS tape just finished playing-capturing to transfer but the Esc key is not responding to generate reports and log the settings we chose. Instead the transfer continues to log frame, size, time, bitrate, tec. 

After pressing Control+Z, the terminal message said 
> [+1} Stopped /Users/metrostudio/Desktop/vrecord
> logout
> There are stopped jobs.

When previewing the .mov file created from the transfer in VLC, there is no content to view when pressed play. 

TLDR: 
When they pressed "Esc" at the end of a transfer of a 50-minute VHS tape nothing happened and scripts kept running in the terminal. I ended up telling them to hit "ctrl-Z" (maybe a bad idea), and the scripts stopped running but the .mov file is empty. The terminal is still open and we have some log files. 

![screen shot 2018-01-31 at 4 55 01 pm](https://user-images.githubusercontent.com/17103609/35649597-9bbf0896-06a7-11e8-878a-d3fc155898f0.png)

Thank you so much for vrecord, our first two tapes worked great, and looking forward to more.

Thanks.

**Comment by dericed** [comment]
In this case `Control-C` would be more approp, than `Control-Z` (see the [internet](https://askubuntu.com/a/510816)). When you hit `ESC` was the ffplay window the active window, or were you hitting escape in the Terminal application? If you want to share log files I recommend pasting into https://gist.github.com/ and then sharing the link back in here, but I suspect the logs here would just imply that the file didn't finish being written correctly.

**Comment by aeschweik** [comment]
I am getting the same unresponsive results when I hit `esc` in the Terminal window, but when I hit `esc` in the playback window, vrecord terminates correctly.

@michi-gato, does hitting `esc` work on your end when you're in the playback window? It may just be a question of which window is active - hopefully an easy fix for now!

**Comment by michi-gato** [comment]
@aeschweik Actually, I submitted this as a vrecord user on behalf of Molly at metro. She mentioned she'll run test later today and will let us know how it goes since they [completed the brew upgrade](https://docs.google.com/document/d/1GCN5_kYUoR3ucePJqX_A8ca-EvXUwsDB_UD96oYDDu4/edit?usp=sharing) + installing the [newer version of Desktop Video](https://www.blackmagicdesign.com/support/). You'll probably see the resolution soon!

**Comment by aeschweik** [comment]
@michi-gato Thanks for the update!

**Comment by aeschweik** [comment]
Also note that pressing `ctrl-c` in the terminal kills the process abruptly enough that it will not create a QCTools XML, though it should still generate a video file from the capture till then.

**Comment by dericed** [comment]
Closing this as the documentation at https://github.com/amiaopensource/vrecord#ending-a-capture seems clear.
