### ISSUE TITLE
vrecord and MiniDV

### ISSUE THREAD

**Issue by rachmattson** [amiaopensource/vrecord#25]
Just a note to say it would be awesome if we could use vrecord to transfer MiniDV tapes.

**Comment by dericed** [comment]
some possibilities to connect DV to ffmpeg on a Mac: http://ffmpeg.org/ffmpeg-devices.html#dv1394 http://ffmpeg.org/ffmpeg-devices.html#iec61883

**Comment by ablwr** [comment]
Sounds like a ~hackday idea~

**Comment by rachmattson** [comment]
!!!

On Wed, Nov 11, 2015 at 3:05 PM, Ashley <notifications@github.com> wrote:

> Sounds like a ~hackday idea~
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/amiaopensource/vrecord/issues/25#issuecomment-155896155>
> .
>



-- 
Dr. Rachel Mattson
Manager of Special Projects,
La MaMa Archives
m. 917. 216.1426

**Comment by yvonneng** [comment]
+++ that hackday idea!

On Wed, Nov 11, 2015 at 3:05 PM, Ashley <notifications@github.com> wrote:

> Sounds like a ~hackday idea~
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/amiaopensource/vrecord/issues/25#issuecomment-155896155>
> .
>



-- 
Yvonne Ng
Senior Archivist
yvonne@witness.org
@ng_yvonne

WITNESS
80 Hanson Place, 5th Floor
Brooklyn, NY 11217
Tel. 718-783-2000 x320  ::  Fax. 718-783-1593
http://www.witness.org  ::  http://blog.witness.org

*See our recent story on PBS NewsHour: How WITNESS supports citizens using
video to document brutality
<http://www.pbs.org/newshour/bb/teaching-citizens-shoot-better-video-witness-brutality/>.*

**Comment by dinahhandel** [comment]
💥 @ablwr

**Comment by villereal** [comment]
this sounds like an excellent hack day project, pleez add to the wiki as enthusiasm dictates! http://wiki.curatecamp.org/index.php/Association_of_Moving_Image_Archivists_&_Digital_Library_Federation_Hack_Day_2015

**Comment by ablwr** [comment]
I can bring it up tomorrow but I won't be carrying any of the equipment necessary to try to hack this thing out. Also happy to host a NY-based hackday in December.

**Comment by ablwr** [comment]
Addendum: MiniDV totally already works with vrecord if you pipe it through an analog signal. :smirk:

**Comment by dericed** [comment]
@ablwr boooo

**Comment by epiil** [comment]
Just to clarify, vrecord/bmdcapture should be able to capture Composite,
S-Video, Component, and SDI signals coming from MiniDV/DVCAM decks,
depending on the desired output. However, in order to capture native DV
streams, i.e. the data-transfer migration approach, one would have to write
a record command based entirely on ffmpeg calling dv/firewire as a device
(e.g, ffmpeg -f dv1384 ...). Bmdcapture alone will not support dv/firewire
as an available input.

**Comment by CSchloss385** [comment]
This is out of the scope of the vrecord project since you need blackmagic in order to use bmdcapture. Vrecord is therefore unable to capture native DV streams.
