### ISSUE TITLE
add mediaconch to dependency list

### ISSUE THREAD

**Issue by bturkus** [amiaopensource/vrecord#252]
hey,

I'm not sure exactly how this works, but I was wondering if mediaconch could be added to the installation dependencies list. 

Thanks!

**Comment by privatezero** [comment]
Hi Ben!
Since mediaconch is in homebrew, it could be added following the same format as the dependencies [here](https://github.com/amiaopensource/homebrew-amiaos/blob/master/vrecord.rb#L11)!

**Comment by retokromer** [comment]
Thank you, @bturkus , for reporting!
