### ISSUE TITLE
Add audio waveform after ingest

### ISSUE THREAD

**Issue by CSchloss385** [amiaopensource/vrecord#253]
I think it would be helpful to have an audio waveform image generated after vrecord is finished running. This might be useful in better understanding where audio clipping is happening.

**Comment by privatezero** [comment]
Were you thinking purely a sidecar file, or something more visual (like a window that opens automatically with the waveform, and maybe other QC data, after digitization)

**Comment by CSchloss385** [comment]
Hmmm... I think it might be best to keep it as a sidecar file. Maybe it could be an option similar to the creation of framemd5 checksums where the user can decide if they want them generated or not.

**Comment by retokromer** [comment]
+1 for @CSchloss385 suggestion

**Comment by privatezero** [comment]
That way definitely seems cleanest! (Although I think with added options I definitely think we are inching towards needing a redesign of the GUI layout to reduce clutter)

**Comment by CSchloss385** [comment]
That's true. the GUI is looking a little crowded!

**Comment by privatezero** [comment]
Just tested out, and like I thought the `showwavespic` filter doesn't like to make an image from a capture (ran `rec -p | ffmpeg -i - -lavfi showwavespic=split_channels=1:s=1024x800 ~/Desktop/test.png` to test) so this would need to be an additional discrete event after the capture is complete.

Does adding a conditional to generate this post-record and pre-cowsay warnings make sense to people?

**Comment by CSchloss385** [comment]
That makes sense to me!

**Comment by privatezero** [comment]
Cool - I'll take a stab at this with using `drawtext` to add a some time context to the standard `showwavespic` output. Might make the results a little more usable!

**Comment by dericed** [comment]
resolved in https://github.com/amiaopensource/vrecord/pull/357
