### ISSUE TITLE
add option to make a qctools report during capture

### ISSUE THREAD

**Issue by dericed** [amiaopensource/vrecord#27]
This needs some testing to see if this is sane to put another process in the works. Here's an example of how to stick an ffprobe command to make a qctools report onto an existing ffmpeg encoder. It uses a named pipe since I couldn't figure out how to input a regular pipe to ffprobe.

```
mkfifo PIPE2QCTOOLS ; ffmpeg -y -i INPUTFILE.mov OUTPUTFILE.mov -c:v rawvideo -c:a pcm_s24le -f nut PIPE2QCTOOLS | ffprobe -loglevel error -f lavfi "movie=PIPE2QCTOOLS:s=v+a[in0][in1],[in0]signalstats=stat=tout+vrep+brng,cropdetect=reset=1,split[a][b];[a]field=top[a1];[b]field=bottom[b1],[a1][b1]psnr[out0];[in1]ebur128=metadata=1[out1]" -show_frames -show_versions -of xml=x=1:q=1 -noprivate | gzip > EXAMPLE.mov.qctools.xml.gz
```

**Comment by dericed** [comment]
psst @jfarbowitz, can you update the filterchain to add in astats, ala https://github.com/bavc/qctools/commit/7f6eb443c0c1989ab2010861b8207b43dc49d343#diff-84f6a641ca3a8ab3c0b8608f722ca27bR196. The next qctools release will use it so it may make sense to add it now.

Also in general I think astats gives more info than ebur128, so it may make sense to consider replacing ebur128 with astats in vrecord-qctools-mode. Needs a test of impact on performance.

**Comment by jfarbowitz** [comment]
Added the option in 118f4b0. Now I just need to update the filterchain.

**Comment by jfarbowitz** [comment]
Added astats in 0202f88. I haven't taken out ebur128 yet. I tested it a few times. No crashes or strange behavior observed.
