### ISSUE TITLE
Invalid Input Data Messages After Installing 2018-02-08

### ISSUE THREAD

**Issue by jimhone** [amiaopensource/vrecord#270]
After upgrading to the 2018-02-08 version on my late 2013 Mac Pro (OSX 10.13.3), I am no longer able to see the passthrough window and keep receiving invalid data input messages.  I am also using an UltraStudio 4K Extreme (10.9.10 Driver).

![invaliddata](https://user-images.githubusercontent.com/9198748/37063637-97b8f946-215f-11e8-879a-2b41de0ab620.png)

The previous version worked wonderfully well.  Any advice would be appreciated.

**Comment by retokromer** [comment]
Thank you for reporting!

>The previous version worked wonderfully well.

Did the version `2018-01-12` work on your side, or was it an older one?

**Comment by aeschweik** [comment]
Hi @jimhone, thanks for reporting! Would you mind pasting the ffplay and ffmpeg logs into [Gist](https://gist.github.com/)?

**Comment by jimhone** [comment]
I wish I could give you the version date, but I installed it in late summer, early fall of 2017.

**Comment by jimhone** [comment]
Logs are pasted into Gist.

**Comment by dericed** [comment]
fyi https://gist.github.com/jimhone/68892e1ae4b2681ae39ae5b973783f35

**Comment by aeschweik** [comment]
Hi @jimhone, thanks for that! Sorry not to be clearer, I was asking about the logs created by vrecord itself. Are .log files still being created in the aux files directory you set? The contents of the files with suffixes _ffplay and _ffmpeg (highlighted in screenshot below) might shed more light on what's happening.

![screen shot 2018-03-07 at 12 11 41 pm](https://user-images.githubusercontent.com/31541957/37106824-bf6c7da4-2200-11e8-990f-e60ab1fbdcdd.png)

**Comment by dericed** [comment]
@jimhone, can you run this and share the result
`/usr/local/opt/ffmpegdecklink/bin/ffmpeg-dl -f decklink -list_devices 1 -i dummy`

**Comment by dericed** [comment]
Copy paste error. You missed the first character.

**Comment by jimhone** [comment]
Dang! One more time.

Lib-FilmMacPro:~ film2$ /usr/local/opt/ffmpegdecklink/bin/ffmpeg-dl -f decklink -list_devices 1 -i dummy
ffmpeg version 3.4.2 Copyright (c) 2000-2018 the FFmpeg developers
  built with Apple LLVM version 9.0.0 (clang-900.0.39.2)
  configuration: --prefix=/usr/local/Cellar/ffmpegdecklink/3.4.2 --disable-shared --enable-pthreads --enable-gpl --enable-version3 --enable-hardcoded-tables --enable-avresample --disable-jack --cc=clang --host-cflags= --host-ldflags= --enable-gpl --enable-ffplay --enable-libfreetype --enable-libmp3lame --enable-libx264 --enable-libxvid --enable-opencl --enable-videotoolbox --disable-lzma --enable-libopenjpeg --disable-decoder=jpeg2000 --extra-cflags=-I/usr/local/Cellar/openjpeg/2.3.0/include/openjpeg-2.3 --enable-nonfree --enable-decklink --extra-cflags=-I/usr/local/include --extra-ldflags=-L/usr/local/include
  libavutil      55. 78.100 / 55. 78.100
  libavcodec     57.107.100 / 57.107.100
  libavformat    57. 83.100 / 57. 83.100
  libavdevice    57. 10.100 / 57. 10.100
  libavfilter     6.107.100 /  6.107.100
  libavresample   3.  7.  0 /  3.  7.  0
  libswscale      4.  8.100 /  4.  8.100
  libswresample   2.  9.100 /  2.  9.100
  libpostproc    54.  7.100 / 54.  7.100
[decklink @ 0x7fd5fd000000] Blackmagic DeckLink input devices:
[decklink @ 0x7fd5fd000000] 	'Olin Library's UltraStudio 4K Extreme'
dummy: Immediate exit requested
Lib-FilmMacPro:~ film2$

**Comment by dericed** [comment]
@jimhone, you could test with
```
curl -O https://raw.githubusercontent.com/amiaopensource/vrecord/de22056e0c5530555cbc8a0d584b24f913c3c292/vrecord
bash vrecord
```

**Comment by dericed** [comment]
@jimhone, also I'm curious how you renamed your decklink device to `Olin Library's UltraStudio 4K Extreme`

**Comment by jimhone** [comment]
Dave,

The test worked, although I received this at the end:
generating QCTools report... 
.................................................. 100 of 100 %
generating QCTools report... done
Vrecord is analyzing your video file. Please be patient.
Analysis is complete.
 2018-03-08T10:12:41 - File did not pass vrecord policy check for FFV1 video and may not conform to digital preservation standards. Try another file?
pass! /Volumes/Promise Pegasus 3/test5_ffv1.mkv

 2018-03-08T10:12:41 - See /Volumes/Promise Pegasus 3/test5_ffv1_mediaconchreport.xml for a full MediaConch policy report.
Lib-FilmMacPro:~ film2$ 

I can copy the logs to Gist if you need them.

The name is a curiosity to me as well.  It does not resemble any naming convention I've ever used.

I suppose I can go back to UltraStudio 4K Extreme.

Let me know about the logs.

J

**Comment by dericed** [comment]
Sounds like it resolves the issue. @aeschweik, note that his script says the file passes the check but the reported line says that it didn't.

**Comment by aeschweik** [comment]
Hi @jimhone, thanks for the heads up about the policy results at the end. I'm going back over that part of the script but can't recreate that result. If you still have the MediaConch XML I'd love to see it (apologies for dipping into a different issue!).

**Comment by jimhone** [comment]
Annie,

The first thing you should know is that this issue stopped happening when I changed the name of my interface from "Olin Library's UltraStudio 4K Extreme" to "UltraStudio4KExtreme." I guess it truly was an issue with parsing the name of the device.

This morning, I deleted all of the tests from yesterday.  However, I recreated the issue in question by copying the script that Dave posted yesterday and recaptured the same content on vrecord.

Some clarifications:

1. When I performed the test the first time, my presets were for 10-bit uncompressed QuickTime.  No wonder the it failed the FFV1 policy test.

2.  The second time I performed the test, I changed the presets to FFV1 (version 3) and Matroska.  Unfortunately, I still got the fail message.

I will hazard a guess that the may be a small bug in the test script.

At any rate, I've posted both MediaConch reports to Gist.

Best,

J

At any rate,

**Comment by aeschweik** [comment]
Thanks for all of this, Jim, much appreciated!
