### ISSUE TITLE
SHA256 mismatch when installing 0.7.9 via homebrew

### ISSUE THREAD

**Issue by kieranjol** [amiaopensource/vrecord#28]
Deleted the download several times and ran brew upgrade vrecord numerous times and I keep getting the same error.
telecine:~ administrator$ brew upgrade vrecord
==> Upgrading 1 outdated package, with result:
amiaopensource/amiaos/vrecord 0.7.9
==> Upgrading amiaopensource/amiaos/vrecord
==> Downloading https://github.com/amiaopensource/vrecord/archive/v0.7.9.zip
Already downloaded: /Library/Caches/Homebrew/vrecord-0.7.9.zip
Error: SHA256 mismatch
Expected: 72f6a99b70d7b9fba713ee169269c2e909a4cfa8d5f0d93b6534f355fceac0ca
Actual: 0b4eaddd704729a79b9120a908c8317654c82b57ebfb5b3d0ea04f06cf1d1494
Archive: /Library/Caches/Homebrew/vrecord-0.7.9.zip
To retry an incomplete download, remove the file above.
telecine:~ administrator$

**Comment by kieranjol** [comment]
Looks like it might be downloading 0.7?

telecine:~ administrator$ brew upgrade vrecord
==> Upgrading 1 outdated package, with result:
amiaopensource/amiaos/vrecord 0.7.9
==> Upgrading amiaopensource/amiaos/vrecord
==> Downloading https://github.com/amiaopensource/vrecord/archive/v0.7.9.zip
==> Downloading from https://codeload.github.com/amiaopensource/vrecord/zip/v0.7
######################################################################## 100.0%
Error: SHA256 mismatch
Expected: 72f6a99b70d7b9fba713ee169269c2e909a4cfa8d5f0d93b6534f355fceac0ca
Actual: 0b4eaddd704729a79b9120a908c8317654c82b57ebfb5b3d0ea04f06cf1d1494
Archive: /Library/Caches/Homebrew/vrecord-0.7.9.zip
To retry an incomplete download, remove the file above.
telecine:~ administrator$

**Comment by jfarbowitz** [comment]
Sorry, forgot to update the SHA checksum. Should be fixed in 743250c

**Comment by kieranjol** [comment]
Thanks for fixing so quick, and apologies for posting it here rather than on your homebrew page.
