### ISSUE TITLE
vrecord crash when capturing PAL

### ISSUE THREAD

**Issue by kieranjol** [amiaopensource/vrecord#29]
Using 0.7.9, vrecord, specifically ffplay crashes once we start capturing PAL from a Blackmagic ultra studio 4k. It captures a frame and that's it. I'm attaching the video file and all the logs:
https://www.dropbox.com/s/kx75aaa2vzpmvq3/Archive.zip?dl=0

Here's possibly a key error from the ffmpeg log:
[v210 @ 0x7fdec300f200] packet too small
Error while decoding stream #0:0: Invalid data found when processing input
[output stream 0:0 @ 0x7fdec17044c0] EOF on sink link output stream 0:0:default.
[output stream 0:2 @ 0x7fdec17034c0] EOF on sink link output stream 0:2:default.
[output stream 0:1 @ 0x7fdec1703d40] EOF on sink link output stream 0:1:default.
[output stream 1:0 @ 0x7fdec3800a40] EOF on sink link output stream 1:0:default.
No more output streams to write to, finishing.

**Comment by jfarbowitz** [comment]
Dave, any idea what the error might be?

**Comment by dericed** [comment]
@kieranjol what does it say when you `bmdcapture -h`

**Comment by kieranjol** [comment]
telecine:~ administrator$ bmdcapture -h
Usage: bmdcapture -m <mode id> [OPTIONS]

    -m <mode id>:
-> UltraStudio 4K (-C 0 )

Supported video output display modes and pixel formats:
         0:   NTSC                 	 720 x 486 	   29.97 FPS
         1:   PAL                  	 720 x 576 	      25 FPS
         2:   1080p23.98           	 1920 x 1080 	  23.976 FPS
         3:   1080p24              	 1920 x 1080 	      24 FPS
         4:   1080p25              	 1920 x 1080 	      25 FPS
         5:   1080p29.97           	 1920 x 1080 	   29.97 FPS
         6:   1080p30              	 1920 x 1080 	      30 FPS
         7:   1080i50              	 1920 x 1080 	      25 FPS
         8:   1080i59.94           	 1920 x 1080 	   29.97 FPS
         9:   1080i60              	 1920 x 1080 	      30 FPS
        10:   1080p50              	 1920 x 1080 	      50 FPS
        11:   1080p59.94           	 1920 x 1080 	 59.9401 FPS
        12:   1080p60              	 1920 x 1080 	      60 FPS
        13:   720p50               	 1280 x 720 	      50 FPS
        14:   720p59.94            	 1280 x 720 	 59.9401 FPS
        15:   720p60               	 1280 x 720 	      60 FPS
        16:   1080p23.98 DCI 2K    	 2048 x 1080 	  23.976 FPS
        17:   1080p24 DCI 2K       	 2048 x 1080 	      24 FPS
        18:   1080p25 DCI 2K       	 2048 x 1080 	      25 FPS
        19:   2160p23.98           	 3840 x 2160 	  23.976 FPS
        20:   2160p24              	 3840 x 2160 	      24 FPS
        21:   2160p25              	 3840 x 2160 	      25 FPS
        22:   2160p29.97           	 3840 x 2160 	   29.97 FPS
        23:   2160p30              	 3840 x 2160 	      30 FPS
        24:   2160p23.98 DCI 4K    	 4096 x 2160 	  23.976 FPS
        25:   2160p24 DCI 4K       	 4096 x 2160 	      24 FPS
        26:   2160p25 DCI 4K       	 4096 x 2160 	      25 FPS

    -v                   Be verbose (report each 25 frames)
    -f <filename>        Filename raw video will be written to
    -F <format>          Define the file format to be used
    -c <channels>        Audio Channels (2, 8 or 16 - default is 2)
    -s <depth>           Audio Sample Depth (16 or 32 - default is 16)
    -p <pixel>           PixelFormat Depth (8 or 10 - default is 8)
    -n <frames>          Number of frames to capture (default is unlimited)
    -M <memlimit>        Maximum queue size in GB (default is 1 GB)
    -C <num>             number of card to be used
    -S <serial_device>   data input serial
    -A <audio-in>        Audio input:
                         1: Analog (RCA or XLR)
                         2: Embedded Audio (HDMI/SDI)
                         3: Digital Audio (AES/EBU)
    -V <video-in>        Video input:
                         1: Composite
                         2: Component
                         3: HDMI
                         4: SDI
                         5: Optical SDI
                         6: S-Video
    -o <optionstring>    AVFormat options
Capture video and audio to a file. Raw video and audio can be sent to a pipe to avconv or vlc e.g.:

    bmdcapture -m 2 -A 1 -V 1 -F nut -f pipe:1


telecine:~ administrator$

**Comment by jfarbowitz** [comment]
Bern testers have been capturing PAL and haven't had any crashes as of yet.

**Comment by kieranjol** [comment]
Thanks @jfarbowitz . It's surely something on our end. We'll need to investigate more. It doesn't help that it's not a VTR that we're testing with. Our only blackmagic card is hooked up to a standard def PAL 8mm/16mm telecine machine. It has captured just fine with FCP/Avid/Media Express, but we probably need to investigate our settings when hooking it up to vrecord. Those capture tools all have shortcomings that I'm hoping can be alleviated with vrecord.

On a side note, it'd be great if you could pass along my email address along to the Bern people, or if they're comfortable with me getting in touch first.  I'd be interested to hear how they've been getting on with PAL vrecord. kieran[dot]o[dot]leary [attt] gmail[dot]com

**Comment by kieranjol** [comment]
I  was able to do some testing today and all was well. Maybe the mac needed a reboot after installation or something? You have created some truly wonderful software. I hope that we can make use of it at the one workstation that has a blackmagic card. All those logs & framemd5s are just a thing of beauty. You're all amazing!!!
