### ISSUE TITLE
Dropped frames warning

### ISSUE THREAD

**Issue by CSchloss385** [amiaopensource/vrecord#291]
It looks like there is a problem with the dropped frames warning. After the warning, the following appears: 
grep: /: Is a directory
(standard_in) 2: parse error
./vrecord: line 455: /3600: syntax error: operand expected (error token is "/3600")
grep: /: Is a directory
(standard_in) 2: parse error
./vrecord: line 455: /3600: syntax error: operand expected (error token is "/3600")

Also, the capture options will mention dropped frames, but there is no timestamp listed.

**Comment by aeschweik** [comment]
Thank you @CSchloss385 for catching all my mistakes!! My hubris - will fix this week!

**Comment by aeschweik** [comment]
closed in #292
