### ISSUE TITLE
move `_report()` before the `while getopts` loop

### ISSUE THREAD

**Issue by retokromer** [amiaopensource/vrecord#296]
Currently it doesn’t work as intended when a non-correct parameter is passed (e.g. `vrecord -y`).

**Comment by aeschweik** [comment]
closed in #297

**Comment by retokromer** [comment]
Thank you!

**Comment by retokromer** [comment]
P.S. – I guess, https://github.com/amiaopensource/vrecord/issues/302 is to consider as well.
