### ISSUE TITLE
BFF field order in PAL

### ISSUE THREAD

**Issue by kieranjol** [amiaopensource/vrecord#30]
Hi guys,
We're only capturing one frame at the moment (bug reported in other thread), but I ran mediainfo on the frame and all looks well aside from the BFF field order. It should be TFF for PAL, right?

Video
ID/String                        : 1
Format                           : YUV
CodecID                          : v210
CodecID/Hint                     : AJA Video Systems Xena
Duration/String                  : 320ms
BitRate_Mode/String              : CBR
BitRate/String                   : 221 Mbps
Width/String                     : 720 pixel3
Height/String                    : 576 pixel3
DisplayAspectRatio/String        : 4:3
FrameRate_Mode/String            : CFR
FrameRate/String                 : 25.000 fps3
Standard                         : PAL
ColorSpace                       : YUV
ChromaSubsampling                : 4:2:2
BitDepth/String                  : 10 bit3
ScanType/String                  : Interlaced
ScanType_StoreMethod/String      : InterleavedFields
ScanOrder/String                 : BFF
Compression_Mode/String          : Lossless
Bits-(Pixel*Frame)               : 21.333
StreamSize/String                : 8.44 MiB (98%)
Language/String                  : en

**Comment by dericed** [comment]
patches welcome

**Comment by kieranjol** [comment]
Will give this a go over the weekend.

**Comment by kieranjol** [comment]
http://github.com/amiaopensource/vrecord/pull/31

This works in PAL, will require testing in NTSC.

**Comment by jfarbowitz** [comment]
Should be fixed as of 57c4947
