### ISSUE TITLE
compress ffmpeg & ffplay logs?

### ISSUE THREAD

**Issue by bturkus** [amiaopensource/vrecord#300]
Hi,
We're about to embark on embedded vrecord logs (thanks again @aeschweik), and I was wondering: would it be possible/would there be any value to compressing the ffmpeg and ffplay logs before the embed? I noticed they seem to be fairly sizable (a 56.97 GB MKV has a 25.9 MB xml.gz, a 56.8 MB FFplay log, and a 52.7 MB FFmpeg log).

Thanks for considering!

Ben

**Comment by kieranjol** [comment]
I think this would make sense as an option. both zipped up in the one file
or a zip for each log?

**Comment by bturkus** [comment]
i was imagining a zip for each, but i'd be happy with whatever the vrecord gods bestow.

**Comment by dericed** [comment]
I propose not to compress the logs and rather to move the reporting verbosity from 40 (verbose) to 32 (info).

**Comment by bturkus** [comment]
this sounds like a great solution to me. thanks for thinking about it

**Comment by retokromer** [comment]
>I propose not to compress the logs and rather to move the reporting verbosity from 40 (verbose) to 32 (info).

Excellent idea!

**Comment by aeschweik** [comment]
Does #304 address the logs you're talking about? Some of the logs were already at "info" verbosity (which is the default for all but ffreport) so I'm not sure this will change all of them.

**Comment by aeschweik** [comment]
Addressed in #304 by removing one of two near-identical logs - hopefully this helps!

**Comment by bturkus** [comment]
thank you so much!
