### ISSUE TITLE
make input buffer overrun error more noticeable

### ISSUE THREAD

**Issue by dericed** [amiaopensource/vrecord#312]
When the ffmpeg log contains
> [decklink @ 0x7fd254009000] Decklink input buffer overrun!

The the vrecord console output (or cowsay) should summarize that warning, since the file likely is missing frames or contains artifacts from the buffer overrun.

**Comment by retokromer** [comment]
+1

**Comment by dericed** [comment]
fixed in https://github.com/amiaopensource/vrecord/pull/313
