### ISSUE TITLE
Audio Channel Layout Issues with FFmpeg

### ISSUE THREAD

**Issue by jfarbowitz** [amiaopensource/vrecord#32]
Here's the error message we're getting

Single channel layout '2' is interpreted as a number of channels, switch to the syntax '2c' otherwise it will be interpreted as a channel layout number in a later version
SDL_OpenAudio (8 channels, 48000 Hz): 1 (mono) and 2 (stereo) channels supported

We may need to change channel layout numbers in these lines:

```
audiomap="[0:a:0]channelsplit=channel_layout=4.0[a1][a2][a3][a4];[a1][a2]amerge,aformat=channel_layouts=stereo[stereo1];[a3][a4]amerge,aformat=channel_layouts=stereo[stereo2]"
        map1k="-map"
        map1v="[stereo1]"
        map2k="-map"
        map2v="[stereo2]"
        ;;
        "1 Stereo Track")
audiomap="[0:a:0]channelsplit=channel_layout=2[a1][a2];[a1][a2]amerge,aformat=channel_layouts=stereo[stereo1]"
        map1k="-map"
        map1v="[stereo1]"
        map2k=""
        map2v=""
        ;;
```

**Comment by jfarbowitz** [comment]
FFplay command needs to be modified to downmix to 2 channels.

**Comment by privatezero** [comment]
This syntax was replaced with switching to the 'pan' filter for setting up audio mapping.  Current form of `audiomap="[0:a:0]pan=stereo| c0=c0 | c1="$phase_value"c1[stereo1]"` should have resolved this!
