### ISSUE TITLE
[wish] other graphic cards than Blackmagic’s

### ISSUE THREAD

**Issue by retokromer** [amiaopensource/vrecord#322]
I know very well that there are some legal issues, but I suggest nevertheless to support other graphic cards as well, _in primis_ AJA’s, because this is the reality in the field.

**Comment by dericed** [comment]
I suggest that the scope of vrecord is not to develop support for hardware but to build upon what support for hardware is already developed in open projects, ie bmdtools or decklink's support in libavdevice. If you contribute an aja input device to libavdevice, then we could consider integrating it.
