### ISSUE TITLE
vrecord won't work after update

### ISSUE THREAD

**Issue by libbyhopfauf** [amiaopensource/vrecord#33]
I ran brew update and upgrades this morning. After this, I could not vrecord to work. I received an error message saying I need to add a library, which I have since added. Now, however, I continue to get the same error message: Invalid data found when processing input. 
![screen shot 2015-11-13 at 12 36 43 pm](https://cloud.githubusercontent.com/assets/13877631/11158906/36cd1628-8a10-11e5-9ca4-c9ba37076153.png)

**Comment by dericed** [comment]
paste in bmdcapture log and ffmpeg log

**Comment by libbyhopfauf** [comment]
bmdcapture log:

dyld: Library not loaded: /usr/local/lib/libavcodec.56.dylib
  Referenced from: /usr/local/bin/bmdcapture
  Reason: image not found

ffmpeg log:

ffmpeg started on 2015-11-13 at 14:02:43
Report written to "/Users/mac2/Desktop/TESTING_ffmpeg_20151113-140243.log"
Command line:
ffmpeg -v info -hide_banner -stats -i - -c:v v210 -metadata:s:v:0 "encoder=Uncompressed 10-bit 4:2:2" -c:a pcm_s24le -filter_complex "[0:v:0]setfield=bff,setsar=40/27,setdar=4/3[vid1];[0:a:0]channelsplit=channel_layout=4.0[a1][a2][a3][a4];[a1][a2]amerge,aformat=channel_layouts=stereo[stereo1];[a3][a4]amerge,aformat=channel_layouts=stereo[stereo2]" -map "[vid1]" -map "[stereo1]" -map "[stereo2]" -f matroska /Users/mac2/Desktop/TESTING.mkv
Splitting the commandline.
Reading option '-v' ... matched as option 'v' (set logging level) with argument 'info'.
Reading option '-hide_banner' ... matched as option 'hide_banner' (do not show program banner) with argument '1'.
Reading option '-stats' ... matched as option 'stats' (print progress report during encoding) with argument '1'.
Reading option '-i' ... matched as input file with argument '-'.
Reading option '-c:v' ... matched as option 'c' (codec name) with argument 'v210'.
Reading option '-metadata:s:v:0' ... matched as option 'metadata' (add metadata) with argument 'encoder=Uncompressed 10-bit 4:2:2'.
Reading option '-c:a' ... matched as option 'c' (codec name) with argument 'pcm_s24le'.
Reading option '-filter_complex' ... matched as option 'filter_complex' (create a complex filtergraph) with argument '[0:v:0]setfield=bff,setsar=40/27,setdar=4/3[vid1];[0:a:0]channelsplit=channel_layout=4.0[a1][a2][a3][a4];[a1][a2]amerge,aformat=channel_layouts=stereo[stereo1];[a3][a4]amerge,aformat=channel_layouts=stereo[stereo2]'.
Reading option '-map' ... matched as option 'map' (set input stream mapping) with argument '[vid1]'.
Reading option '-map' ... matched as option 'map' (set input stream mapping) with argument '[stereo1]'.
Reading option '-map' ... matched as option 'map' (set input stream mapping) with argument '[stereo2]'.
Reading option '-f' ... matched as option 'f' (force format) with argument 'matroska'.
Reading option '/Users/mac2/Desktop/TESTING.mkv' ... matched as output file.
Finished splitting the commandline.
Parsing a group of options: global .
Applying option v (set logging level) with argument info.
Applying option hide_banner (do not show program banner) with argument 1.
Applying option stats (print progress report during encoding) with argument 1.
Applying option filter_complex (create a complex filtergraph) with argument [0:v:0]setfield=bff,setsar=40/27,setdar=4/3[vid1];[0:a:0]channelsplit=channel_layout=4.0[a1][a2][a3][a4];[a1][a2]amerge,aformat=channel_layouts=stereo[stereo1];[a3][a4]amerge,aformat=channel_layouts=stereo[stereo2].
Successfully parsed a group of options.
Parsing a group of options: input file -.
Successfully parsed a group of options.
Opening an input file: -.
[AVIOContext @ 0x7ff60a6001a0] Statistics: 1 bytes read, 0 seeks
pipe:: Invalid data found when processing input

**Comment by dericed** [comment]
quick fix (maybe): `brew switch mysql v0.7.8`

**Comment by dericed** [comment]
fresh install?
```
brew uninstall ffmpeg libav bmdtools vrecord
brew install vrecord
```

**Comment by libbyhopfauf** [comment]
That worked! Thanks, Dave!

**Comment by dericed** [comment]
B)
