### ISSUE TITLE
Is error message about "MS style video codec tag" actually meaningful?

### ISSUE THREAD

**Issue by jfarbowitz** [amiaopensource/vrecord#34]
When doing vrecord testing to today I got this message:

[mov @ 0x7fbcc400fa00] Using MS style video codec tag, the file may be unplayable!

Is this something we should be concerned about?

**Comment by dericed** [comment]
It's just what ffmpeg says when writing an FFV1 fourcc to QuickTime as a codec id. If you use ffv1 in quicktime, that's the price you pay.
