### ISSUE TITLE
vstop command not found

### ISSUE THREAD

**Issue by kellyhaydon** [amiaopensource/vrecord#36]
We just updated vrecord and getting error messages that "vstop command is not found." Did the functionality change? Is there a new/better way to stop a capture? Screen cap is attached. 

Kelly
![vstop](https://cloud.githubusercontent.com/assets/9436241/11489025/64a62684-9780-11e5-8307-47a71e6d47eb.png)

**Comment by kieranjol** [comment]
https://github.com/amiaopensource/vrecord/commit/e3c24a59b871d55430514f502f9c4b84d402f629

^^Looks like it was removed a few months ago?

**Comment by kellyhaydon** [comment]
OOOOH...we must have missed an update.

**Comment by dericed** [comment]
Ahem https://github.com/amiaopensource/vrecord/blob/master/vrecord#L908

**Comment by dericed** [comment]
vstop's gone

**Comment by kellyhaydon** [comment]
Mission: To  back in time and send an issue about the sudden omission of the vstop command 
Status: Complete.

Thank you!
