### ISSUE TITLE
[wish] HuffYUV as capture format

### ISSUE THREAD

**Issue by retokromer** [amiaopensource/vrecord#366]
I suggest to add the HuffYUV encoding – of course, in FFmpeg owns flavour `ffvhuff`, not the original `huffyuv` – as a choice. Both formats hold the same «raw» image content – this can be proven e.g. by `framemd5` – and have the same lossless compression rate, but the encoding of HuffYUV does require almost <sup>3</sup>/<sub>4</sub> of the time needed by FFV1. (Speed is the reason why we still use this codec for capturing on low-tech hi-quality film scanners.)

**Comment by retokromer** [comment]
Closing, because no interest during four months.

**Comment by dericed** [comment]
Untested, but you may be able to do this with current code via `vrecord -O "-c:v huffyuv"`. The `-O` option would insert the options after the codec selected in the preferences, so it should overrule.

**Comment by retokromer** [comment]
Yes, I presume this works, but I am afraid I see it more like a hack. My patch includes an additional regular format, because in my personal opinion this is a better approach.

**Comment by retokromer** [comment]
It should be FFmpeg’s own codec, I guess (untested): `vrecord -O "-c:v ffvhuff"`.

**Comment by retokromer** [comment]
For the difference between the two implementations, try:
```
ffmpeg -h encoder=huffyuv
```
and compare with:
```
ffmpeg -h encoder=ffvhuff
```

**Comment by retokromer** [comment]
reopening as [suggested](https://github.com/amiaopensource/vrecord/pull/395#issuecomment-444627244) by @dericed

**Comment by bturkus** [comment]
@retokromer re: ffvhuff do you have any perspective on interlacement flags (both +ilme+ildct? one or the other?)

**Comment by retokromer** [comment]
@bturkus I’m afraid, I cannot remember, but I’ll check my patch. (I’m commuting as it’s evening here…)

**Comment by retokromer** [comment]
@bturkus It’s similar to FFV1.  I’ll open a PR with my patch once the others are closed, in order to avoid conflict resolutions.
