### ISSUE TITLE
Create a Field for Technician Name and Record this in Capture Options 

### ISSUE THREAD

**Issue by jfarbowitz** [amiaopensource/vrecord#37]
Add a "Technician Name" field into the GUI and allow an undeclared option. This will be to record the name of the person who did the digitization. The name should be printed in the digitization options text file that vrecord spits out at the end.

**Comment by jfarbowitz** [comment]
If the user decides not to enter in a technician name what should the log say? "N/A" or should the technician field not appear on the log at all?

**Comment by dericed** [comment]
N/A

**Comment by jfarbowitz** [comment]
You got it. It's done in 53e3c1f .
