### ISSUE TITLE
Create Tests for Video Errors Using QCTools XML

### ISSUE THREAD

**Issue by jfarbowitz** [amiaopensource/vrecord#38]
Now that we are generating the QC Tools XML, we should get vrecord to do some quick tests for obvious video errors.

**Comment by jfarbowitz** [comment]
First up some illegal saturation values from a dirty deck: 

This is a little slow (took 9 seconds) but gives the right result.

gzcat BCL00457_ffv1.mov.qctools.xml.gz | xml sel -t -v "count(//tag[@key='lavfi.signalstats.SATMAX'][@value>118])"  -n

Here I use gzcat to pipe the qctools report into xmlstarlet to count the number of frames with a maximum saturation that is outside of the YUV color space limits. In the case of this sample it's 64 frames.

Alternatively this gives the list of frame timestamps with illegal saturation values.

gzcat BCL00457_ffv1.mov.qctools.xml.gz | xml sel -t -m "//frame/tag[@key='lavfi.signalstats.SATMAX'][@value>118]" -v ../@pkt_pts_time -n

The warning should suggest that the user might clean the deck and/or check the original tape.

**Comment by dericed** [comment]
@jfarbowitz make up yur mind!

**Comment by jfarbowitz** [comment]
Sorry, thought you could assign multiple people.

**Comment by jfarbowitz** [comment]
As Dave reported, these tests may take some time so we will need some fancy message like "testing video signal.................." to distract the user.

**Comment by dericed** [comment]
```
 ____________ 
< be patient >
 ------------ 
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||
```

**Comment by jfarbowitz** [comment]
Haha. Are we getting a little too :cow2: -centric?

**Comment by jfarbowitz** [comment]
BTW, what's the threshold we want to set for the number of illegal frames that trigger a warning? 60? 
I looked at the file I redid for Catriona today and the number I got was 14.

**Comment by retokromer** [comment]
@jfarbowitz What is the status of this?

**Comment by jfarbowitz** [comment]
I still think it's a good idea, but as you can tell, I haven't had any time to actually had time to implement any additional tests in over a year. At this point I can't commit to working on it, but would be happy if someone else took the helm on this.

**Comment by retokromer** [comment]
Thank you for the information. Then I let this open.

**Comment by dericed** [comment]
Closing as vrecord incorporates at least three tests based upon qctools data at this point.
