### ISSUE TITLE
Recommended hardware for video capture cards/interfaces

### ISSUE THREAD

**Issue by todrobbins** [amiaopensource/vrecord#39]
I would love to see a little `.md` file with recommended hardware for the various 📼 capture modes. Would anyone besides myself find something like this useful?

I guess it'd be nice to know what are some reliable options.

Cheers!

**Comment by jfarbowitz** [comment]
@todrobbins by hardware do you mean specific capture cards? Computers? Hard drives? 

I think this stuff can be added into the ReadMe.

**Comment by todrobbins** [comment]
Ah yes, specificity would be helpful: capture cards.

**Comment by todrobbins** [comment]
For instance, I have one of these on hand: https://www.elgato.com/en/video/video-capture

Maybe a table listing support for each model?

**Comment by dericed** [comment]
vrecord relies on the SDK for Blackmagic cards and bmdtools to glue it together. So far those are the only cards supported.

**Comment by todrobbins** [comment]
Thanks @dericed. That makes sense now after digging further into bmdtools.
