### ISSUE TITLE
Wishlist: Create log of processes performed 

### ISSUE THREAD

**Issue by dinahhandel** [amiaopensource/vrecord#4]
Create log that captures information about the processes performed on digital files, as well as user-related metadata, such as the user, computer used to processes assets, etc. Something similar to the capture.log shown below.
<img width="946" alt="screen shot 2015-10-08 at 1 11 20 pm" src="https://cloud.githubusercontent.com/assets/9371978/10373881/1ceb7baa-6dbe-11e5-8c10-a9f4af2a914d.png">

**Comment by jfarbowitz** [comment]
Fixed as of f6c023f by @dinahhandel and me.
