### ISSUE TITLE
Ingest Log Getting Written Twice

### ISSUE THREAD

**Issue by jfarbowitz** [amiaopensource/vrecord#40]
Within the same capture_options.log the options are getting written twice.

**Comment by jfarbowitz** [comment]
Can't get it to replicate. It could have been an isolated error as the computer was having issues running vrecord again and had to be restarted.

**Comment by dinahhandel** [comment]
Is it possible it has something to do with _writeingestlog functions being repeated twice? Haven't looked super closely but just happened to notice this: 
<img width="1226" alt="screen shot 2015-12-04 at 11 57 49 am" src="https://cloud.githubusercontent.com/assets/9371978/11595624/613e73ce-9a7e-11e5-8472-fd05a7019aba.png">

**Comment by jfarbowitz** [comment]
Where is that image from? I looked in the current vrecord code and _writeingestlog wasn't repeated for the same items.

**Comment by dinahhandel** [comment]
OH DUH that is my old version of vrecord NEVERMIND :)
