### ISSUE TITLE
add unfiltered view to documentation 

### ISSUE THREAD

**Issue by libbyhopfauf** [amiaopensource/vrecord#400]
A description and image of the unfiltered view needs to be added to the documentation, with a note about purpose (helpful for those consistently experiencing buffer overruns).

**Comment by libbyhopfauf** [comment]
I'm on it!

**Comment by retokromer** [comment]
Thank you, @libbyhopfauf !

**Comment by libbyhopfauf** [comment]
Resolved in Pull Request #491
