### ISSUE TITLE
Allow slice options for FFV1

### ISSUE THREAD

**Issue by b00giehead** [amiaopensource/vrecord#401]
Hi, would it be possible to have slice options for FFV1 so our institution can select 24? We are generating all archiveable outputs to 24, so would be ideal to capture/convert directly via vrecord. I notice it is set to 16 at present. Many thanks!

**Comment by dericed** [comment]
fixed in https://github.com/amiaopensource/vrecord/pull/422, thx @b00giehead!

**Comment by b00giehead** [comment]
Thanks so much Dave! I'll try this out this week :)
