### ISSUE TITLE
add flac/audio encoding options

### ISSUE THREAD

**Issue by bturkus** [amiaopensource/vrecord#403]
i wanna try this one, but gonna wait for gtkdialog

**Comment by retokromer** [comment]
@bturkus Any news on this? On my side I would be more than happy to use this during my next training…

**Comment by bturkus** [comment]
hey @retokromer I was waiting on the switch to new GUI, and didn't realize it already happened. Soo cool!!

**Comment by bturkus** [comment]
closing. dealt with in #417 and #418
