### ISSUE TITLE
Vrecord Fails to Read QCTools XML

### ISSUE THREAD

**Issue by jfarbowitz** [amiaopensource/vrecord#41]
Getting the following message after capture finishes when I am capturing to an external hard drive. Oddly, it works fine when choosing the desktop of my local machine as the capture directory.

```
Vrecord is analyzing your video file. Please be patient.
gzcat: can't stat: /Volumes/GDRIVE1/VRECORD/Farbowitz (/Volumes/GDRIVE1/VRECORD/Farbowitz.gz): No such file or directory
gzcat: can't stat: Redo/qctoolstest1_ffv1.qctools.xml.gz (Redo/qctoolstest1_ffv1.qctools.xml.gz.gz): No such file or directory
-:1.1: Document is empty

^
-:1.1: Start tag expected, '<' not found

^
```

**Comment by jfarbowitz** [comment]
Dave, do you know what might be causing the issue?

**Comment by CSchloss385** [comment]
@jfarbowitz is this still the case?

**Comment by jfarbowitz** [comment]
Will try to replicate today.

**Comment by jfarbowitz** [comment]
haven't seen the issue since. I guess it was an isolated blip. Closing.
