### ISSUE TITLE
libx264 library not loaded error (vrecord 2018-12-13 ffmpeg 4.1)

### ISSUE THREAD

**Issue by bturkus** [amiaopensource/vrecord#411]
Hi,

We seem to be having an issue (on one computer) post-vrecord update from version 10-23 to 12-13. Not sure exactly what happened, but we're getting the following error:
```
No decklink inputs were found. Running `/usr/local/opt/ffmpegdecklink/bin/ffmpeg-dl -hide_banner -f decklink -list_devices 1 -i dummy` results in:

dyld: Library not loaded: /usr/local/opt/x264/lib/libx264.152.dylib

  Referenced from: /usr/local/opt/ffmpegdecklink/bin/ffmpeg-dl

  Reason: image not found
```
We're on Desktop Video 10.11.4, and just updated Mojave from 10.14.1 to 10.14.2. 

Thanks!

Ben

Please check connections and drivers and try again.

**Comment by dericed** [comment]
`brew reinstall ffmpegdecklink` ?

**Comment by bturkus** [comment]
lord. thank you! that did it. all I can say is: it's been a while since I've had to troubleshoot vrecord
