### ISSUE TITLE
[wish] update documentation

### ISSUE THREAD

**Issue by retokromer** [amiaopensource/vrecord#419]
I suggest to update vrecord’s documentation as many recent changes are currently not reflected.

**Comment by bturkus** [comment]
hey @retokromer what changes are you talking about?

**Comment by privatezero** [comment]
I think that the revised GUI is probably a big one!

**Comment by bturkus** [comment]
👍
So we got:
1) New GUI
2) New codecs/containers
3) Diff views for preview/capture (has this made it in yet? does it even need to?)

anything else?

**Comment by retokromer** [comment]
Indeed, I was thinking about the new GUI and the new formats. I also guess that this would be a good time to make the documentation available off-line as well (therefore I reopen https://github.com/amiaopensource/vrecord/issues/249).

**Comment by retokromer** [comment]
See also: https://github.com/amiaopensource/vrecord/issues/401#issuecomment-478733816

**Comment by bturkus** [comment]
hey im taking a look at the docs and wondering, this isnt true anymore, is it?
```
Thus far installing vrecord on Linux using Linuxbrew has not been successful.
```

**Comment by dericed** [comment]
Nope, @privatezero confirmed that it's working recently.

**Comment by retokromer** [comment]
Linuxbrew has been merged into Homebrew. It’s even easier today!

**Comment by dericed** [comment]
Resolved by @bturkus via https://github.com/amiaopensource/vrecord/pull/427. Thanks!
