### ISSUE TITLE
cowsay warning

### ISSUE THREAD

**Issue by NMAAHC** [amiaopensource/vrecord#42]
*WARNING: Your video file contains \
| 130 frames with saturation levels above |
| 124. Your deck may require              |
\ cleaning.* 

Our deck is clean. Is this something to be concerned about?

Also, in red text above the cow - *[v210 @ 0x7fad3c800000] packet too small
Error while decoding stream #0:0: Invalid data found when processing input
[v210 @ 0x7fe62301c000] packet too small*

Freakout? Yes/No?

**Comment by dericed** [comment]
freakout=no

**Comment by dericed** [comment]
```
[v210 @ 0x7fad3c800000] packet too small
Error while decoding stream #0:0: Invalid data found when processing input
[v210 @ 0x7fe62301c000] packet too small
```
just means that there was an incomplete frame at the end. This is because stopping vrecord happens in between frames almost all of the time. #nbd

**Comment by ablwr** [comment]
fortune | cowsay -p

**Comment by jfarbowitz** [comment]
@NMAAHC thanks for bringing this up. I'll improve the Readme so that info about the warnings is more clear. 

Vrecord is just running a simple test on the saturation levels so your deck could be fine. I would recommend checking the file more closely in QC Tools to see what the potential issue is. It could be that the tape has static at the beginning or end which goes outside broadcast range. It could also mean the tape was recorded inconsistently (or if you set it to bars the content was inconsistent with the bars) and the image from some frames fell outside broadcast range.

**Comment by dericed** [comment]
```
 _________________________________________ 
/ When pasting errors reported by cowsay, \
\ please include the cow.                 /
 ----------------------------------------- 
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||
```

**Comment by NMAAHC** [comment]
< Y'all THE BEST >
 ---------------- 
        \   ^__^
         \  (@@)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

**Comment by NMAAHC** [comment]
Just some more red type:
*Multiple frames in a packet from stream 1= 6379KB sq=    0B f=0/0   
[pcm_s32le @ 0x7fb3da012e00] **Invalid PCM packet, data has size 15 but at least a size of 32 was expected
Error while decoding stream #0:1: Invalid data found when processing input**
frame=  352 fps= 30 q=-0.0 q=-0.0 q=-1.0 size=  327348kB time=00:00:11.75 bitratframe=  352 fps= 30 q=-0.0 Lq=-0.0 q=-1.0 size=  327389kB time=00:00:11.75 bitrate=228065.2kbits/s    
video:1122660kB audio:24254kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
[pcm_s32le @ 0x7f8db6008600] **Invalid PCM packet, data has size 15 but at least a size of 32 was expected**
Vrecord is analyzing your video file. Please be patient.
Analysis is complete.*

**Comment by dericed** [comment]
The first issue is real, your capture has abnormally high saturation levels.

The second issue is dealt with in this [part of the documentation](https://github.com/amiaopensource/vrecord#ffmpeg-error-message). The cruel reality of video digitization is that occasionally a fragment of the last frame gets lost in the buffer.

Closing, but re-open if there are other suggestions.
