### ISSUE TITLE
Problem installing gnuplot without lua

### ISSUE THREAD

**Issue by callyho** [amiaopensource/vrecord#421]
Installing vrecord on a new machine, and when I run:
brew install gnuplot --without-lua
I get the error message:
Error: invalid option: --without-lua

Any idea what I might be doing wrong, or if something has changed?

**Comment by retokromer** [comment]
In the classic Brew all options have been removed.

**Comment by retokromer** [comment]
Yep, I just checked: the [gnuplot foumula](https://github.com/Homebrew/homebrew-core/blob/master/Formula/gnuplot.rb) does nor longer allow the option `--without-lua`. I will update our vrecord formula.

Thank you, @callyho, for reporting!

**Comment by retokromer** [comment]
@callyho and/or @b00giehead : Could you possibly test if with just

```
brew install gnuplot
```

it works fine also on your end?

**Comment by callyho** [comment]
@retokromer will test this today or tomorrow & report back

**Comment by retokromer** [comment]
@callyho Excellent, thank you!

**Comment by dericed** [comment]
fixed in https://github.com/amiaopensource/homebrew-amiaos/pull/182.

**Comment by b00giehead** [comment]
Thanks Reto, I’m back in Wednesday so could try then but suspect @callyho will beat me to it. I will update my blog though so thanks for fixing! :)

**Comment by retokromer** [comment]
@bturkus Copy on you disk the amended formula and run: 

```
brew install <drag&drop the local formula>
```

**Comment by callyho** [comment]
Tested with regular gnuplot install, seems to be working fine. FWIW this was on a fresh install of pretty much everything on a Mac running 10.14.

**Comment by retokromer** [comment]
Thank you, @callyho, for reporting back!

**Comment by dericed** [comment]
fixed in https://github.com/amiaopensource/homebrew-amiaos/pull/182, thx @callyho!
