### ISSUE TITLE
ubuntu 18.04 libcerf installation issue

### ISSUE THREAD

**Issue by bturkus** [amiaopensource/vrecord#423]
I'm testing out vrecord installation on an Ubuntu 18.04 vm, and I'm experiencing some sort of libcerf-related installation issue. Looks like this:
```
==> Installing amiaopensource/amiaos/vrecord dependency: libcerf
==> Downloading http://apps.jcns.fz-juelich.de/src/libcerf/libcerf-1.13.tgz
#=#=#                                                                         
curl: (22) The requested URL returned error: 404 Not Found
Error: An exception occurred within a child process:
  DownloadError: Failed to download resource "libcerf"
Download failed: http://apps.jcns.fz-juelich.de/src/libcerf/libcerf-1.13.tgz

benturkus@benturkus-VirtualBox:~$ 
```
Could anyone confirm this or provide any insight? When I go to this libcerf [site](http://apps.jcns.fz-juelich.de/doku/sc/libcerf), it says something about a homepage change. 

Thanks!

**Comment by privatezero** [comment]
Hi @bturkus, currently installing fresh via homebrew on linux can get things stuck in dependencies of dependencies hell where brew isn't playing well with things that are already installed via traditional linux package managers.

To test things out, I would try to get a few of the core dependencies installed and then install vrecord without dependencies. So something along the lines of:

`brew install decklinksdk && brew install ffmpegdecklink && gtkdialog`
`brew install --ignore-dependencies vrecord`

Those are just guesses for core functions rn! I got it to work fine on my end, but it does seem at this point that depending on linux flavor, and what is already installed via `apt` and how homebrew was set up that there is some variance.

**Comment by privatezero** [comment]
Had a typo in there! Updated it!

**Comment by bturkus** [comment]
thanks! that did the trick. I got vrecord installed and running (I think) properly. Couldn't take it all the way due to virtual machine nonsense, but I think I understand enough to update the documentation a bit. @privatezero is there anything else linux-related that you think should be mentioned?

**Comment by bturkus** [comment]
closing. thanks for the help @privatezero!
