### ISSUE TITLE
Matroska log attachment change, latest vrecord version

### ISSUE THREAD

**Issue by digitensions** [amiaopensource/vrecord#431]
Hello team,

With the previous version of vrecord our FFV1/MKV captures had two log files embedded within the MKV wrapper - capture_options and ffmpeg_decklink_input.  Some captures taken yesterday with our Black Magic Decklink Duo (1) had only one log embedded, the capture_options.

I didn't take the captures myself so couldn't review what the cow had to say, and haven't updated FFmpeg on the capture Mac which I will check in case this is the problem.

Otherwise the new shiny vrecord is working perfectly well.  Thank you so much for the FFV1 slices choice! Great to see FLAC too.

**Comment by dericed** [comment]
current logging doesn't catch the output of mkvpropedit, but i'm curious if mkvpropedit gives an error in this circumstance. I'll test and see if i can recreate this. Thank you for reporting

**Comment by privatezero** [comment]
Thanks for catching this!! I suspect that https://github.com/amiaopensource/vrecord/pull/432 might fix it.

**Comment by digitensions** [comment]
Thanks @privatezero. Do you know when this fix will translate to an upgrade. Still on one log here :)

**Comment by dericed** [comment]
@digitensions, @privatezero's fix is in the latest release, so if you're using that then it's still not fixed. In your terminal output near the end are there any mkvpropedit messages that would give a hint of the issue.

**Comment by digitensions** [comment]
I still have the capture window open, and the tail end of our last capture follows. There's some Broken Pipes(?) and at the very end an error about the missing log. Is this a problem with our hard drive naming protocol? It seems to come up with a ton of 'greps' at the bottom.  Thanks so much Dave/Andrew. :)

generating QCTools report... 
.................................................. 100 of 100 %
generating QCTools report... done
av_interleaved_write_frame(): Broken pipe
Error writing trailer of pipe:: Broken pipe
frame= 3162 fps= 25 q=-0.0 Lq=-0.0 q=-1.0 size= 2016010kB time=00:02:06.48 bitrate=130575.2kbits/s speed=0.991x    
video:10482082kB audio:260842kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
Conversion failed!
mv: /Volumes/MACE [1] HD 4/Captured Audio:Video/UNPROCESSED [Koala TV]/Untitled03_ffv1_vitc_frame_timecodes.txt: set owner/group (was: 501/0): Operation not permitted
Vrecord is analyzing your video file. Please be patient.
Vrecord is generating graphs from the QCTools data. One moment please.
 _________________________________________ 
/ WARNING: Your video file contains \
| 347 frames with pixels out of broadcast |
\ range.                            /
 ----------------------------------------- 
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||
QCTools analysis is complete.
grep: /Volumes/MACE: No such file or directory
grep: 4/Captured: No such file or directory
grep: Audio:Video/UNPROCESSED: No such file or directory
grep: TV]/Untitled03_ffv1_ffmpeg_decklink_input.log: No such file or directory
grep: /Volumes/MACE: No such file or directory
grep: 4/Captured: No such file or directory
grep: Audio:Video/UNPROCESSED: No such file or directory
grep: TV]/Untitled03_ffv1_ffmpeg_decklink_input.log: No such file or directory
/usr/local/bin/vrecord: line 1559: [[: [1]:0
HD:0
[Koala:0: syntax error: operand expected (error token is "[1]:0
HD:0
[Koala:0")
grep: /Volumes/MACE: No such file or directory
grep: 4/Captured: No such file or directory
grep: Audio:Video/UNPROCESSED: No such file or directory
grep: TV]/Untitled03_ffv1_ffmpeg_decklink_input.log: No such file or directory
/usr/local/bin/vrecord: line 1570: [[: [1]:0
HD:0
[Koala:0: syntax error: operand expected (error token is "[1]:0
HD:0
[Koala:0")
Checking file conformance against FFV1 video policy...
 2019-06-13T14:21:59 - File passed policy check for FFV1 video.
Vrecord is attaching logs to your Matroska file:
The file is being analyzed.
The changes are written to the file.
Done.
Error: The file '/Volumes/MACE [1] HD 4/Captured Audio:Video/UNPROCESSED [Koala TV]/Untitled03_ffv1_ffmpeg_decklink_input.log' could not be opened for reading: open file error.
Vrecord is done attaching logs to your Matroska file!

**Comment by digitensions** [comment]
It wasn’t bringing in two logs last time I checked. I’ll upgrade next Wednesday and confirm for sure. Thank you for the poke, sorry I forgot to update :)

**Comment by digitensions** [comment]
I have two logs again, many thanks for the fix!

![Screen Shot 2019-09-20 at 14 25 04](https://user-images.githubusercontent.com/37188631/65330534-acb95700-dbb2-11e9-9353-f47e4bb88cb5.png)
