### ISSUE TITLE
avectorscope in qc view?

### ISSUE THREAD

**Issue by bturkus** [amiaopensource/vrecord#434]
does anyone have a sense of how difficult it would be to add avectorscope to vrecord's views? would it be easiest to do it in qcview lua? and has this been considered before? if so, and it's been set aside for a good reason, my bad.

**Comment by dericed** [comment]
iirc there's some issue with syncing audio and video output in ffplay when audio filters are used in the filter to produce visualizations, i'll take a look and see if its still an issue

**Comment by retokromer** [comment]
Do we not use mpv?

**Comment by privatezero** [comment]
I def think that _shouldn't_ be too hard to implement in qc view and possibly as a replacement for part of the window in the audio passthrough mode (which also uses mpv). When I worked on trying to get the basic audio bars into vrecord, FFplay was not up to the job for some reason, with the combination of video and audio filtering massively contributing to lag vs the source material (and the inevitable buffer over runs and a gazillion dropped frames).

**Comment by bturkus** [comment]
I'd def be open to anyone else doing this, but if I gotta struggle thru it I will. This the line that would need tweaking, right? 

https://github.com/amiaopensource/vrecord/blob/d79a79f56a50c7245ec9e9c8c6a83bb91af579ea/Resources/qcview.lua#L232

**Comment by bturkus** [comment]
not to make this more complicated for me (or anyone), but I'd love to be able to see separate phasecopes for ch 1& 2 and ch 3 & 4

**Comment by dericed** [comment]
@retokromer, vrecord does have an mpv dependency

**Comment by retokromer** [comment]
Could we not use «only» mpv? It is much more versatile than ffplay. Just asking, because nowadays I almost never use ffplay.

**Comment by privatezero** [comment]
@bturkus, I don't think that they were ever successful in integrating the full audio passthrough mode into qc mode, so I think that line is more of a place holder? Current audio passthrough is at https://github.com/amiaopensource/vrecord/blob/master/vrecord#L648

I have some wiggle room this week with my 'research' time, so I'll try to take a peak at this later today to at least get reacquainted with the issues. (Assuming I can finish rebuilding my system from a total meltdown this week hahaha)

**Comment by privatezero** [comment]
@retokromer, it has been a while since I was doing side to side comparisons of ffplay vs mpv in the vrecord context, but at the time (a couple years ago) they definitely each had their own quirks that made them better for some things and worse for others in vrecord - but sadly my memory has faded on what exactly worked better in ffplay. Might not be a difference any more!

**Comment by retokromer** [comment]
@privatezero @dericed It’s just an idea. I should delve more into that before having a clear opinion. I know that in my company, only mpv is used anymore, but for training I actually continue to use ffplay…

(Don’t meltdown too many computers, it’s all industrial waste ;-)

**Comment by richardpl** [comment]
I fixed some cases in bunch of filters where afifo was used to get right framerate in video output.
By using .activate callback there should not be need for afifo anymore and this was main issue with lags and buffer overruns.

**Comment by bturkus** [comment]
YOYOYO I just updated Desktop Video (to 11.2), and I got 4 CH and 2 Phasescopes in Audio Passthrough mode. It's a dream; thanks @privatezero!! 

![mpv-shot0014](https://user-images.githubusercontent.com/8987230/61565590-7bec6280-aa47-11e9-9019-98f9cac576a2.jpg)

And yes, it's Jumpin' Jack Flash, which also has captions!!

**Comment by privatezero** [comment]
@bturkus that's great! Thanks for testing/confirming this!

**Comment by privatezero** [comment]
Hi @bturkus, I haven't closed this yet because _technically_ the issue was asking about adding this into the lua qc view, but would you say we can close this for the time being?

Did some investigation into adding it into the lua script, and I was successful - but it did seem to require some syntax changes that had a few cascading effects when switching between filters, so I thought maybe for now keeping audio as its own separate function might be best!

**Comment by bturkus** [comment]
oh yes, for sure, gonna close myself. and thanks again for the implementation @privatezero. It's such a useful addition!
