### ISSUE TITLE
Modification to BRNG Pixels

### ISSUE THREAD

**Issue by bturkus** [amiaopensource/vrecord#44]
I'm interested in having pixels valued at 0 and 255 turn a different color (red?) to indicate clipping. Or possibly some sort of gradient?

I know drop outs and edge related stuff would probably register, but we transfer a lot of 1/2'' open reel, which generally had no regard for legal limits. There are some cases where it seems better to take partial advantage of the allowances of head and footroom, though it can be tricky to know exactly when you've gone too far.

Dave suggested that files treated in such a way should be marked "Full Range." Could this be added as a preference?

**Comment by dericed** [comment]
I think this is all doable with conditions in lutyuv. For now you could use the 'sample range' filter to select either 0 or 255. Whether a file is full range or broadcast range should be visible in the list view of qctools, in the column called "Color Range".

**Comment by dericed** [comment]
please test https://github.com/amiaopensource/vrecord/tree/switch-from-brng-to-geq

**Comment by kellyhaydon** [comment]
I tested today with a HI8mm color bars tape and exploded the values so they exceed 255 and 0, but there doesn't seem to be a difference in the visualizations with the exception of a slight color difference in the Waveform graphics. 

![geq](https://cloud.githubusercontent.com/assets/9436241/13270592/0aefe07e-da44-11e5-9bd4-3496d1ba17d2.png)
![brng](https://cloud.githubusercontent.com/assets/9436241/13270594/0c422694-da44-11e5-8f2d-6e00b2e5e6e1.png)

**Comment by dericed** [comment]
Looks like it doesn't hit 0 and 255 but limits at 1-254.

**Comment by dericed** [comment]
updated in https://github.com/amiaopensource/vrecord/commit/228906e16e00d172dc023fa9717e1e00bb9e94f4, retest plz

**Comment by dericed** [comment]
also note that the geq equation only highlights luma, not chroma

**Comment by retokromer** [comment]
What is the status of this?

**Comment by richardpl** [comment]
I'm writing pseudocolor filter, which would, among other things, replace out-of-range pixels with different colored gradient. Perhaps this is what you need?

**Comment by retokromer** [comment]
>I'm writing pseudocolor filter, which would, among other things, replace out-of-range pixels with different colored gradient.

Is one working on using the pseudocolor filter in vrecord?

**Comment by aeschweik** [comment]
Closed via #269 thanks to @EG-tech!
