### ISSUE TITLE
Pessimistic dialog in CONTRIBUTING.md

### ISSUE THREAD

**Issue by ablwr** [amiaopensource/vrecord#446]
The CONTRIBUTING.md file in this repo's opening paragraph is: "This project welcomes contributions and feedback particularly from active AMIA members, although any contributing and/or interested institutions and individuals are welcome to participate and contribute via issue tracking, various open source communication and social media channels and other sources of public community outreach."

This implies that people who are not active AMIA members are not welcome to contribute code, only comments and hype.

**Comment by richardpl** [comment]
How to become AMIA active member?

**Comment by ablwr** [comment]
@richardpl :moneybag: :moneybag: :moneybag:

**Comment by ablwr** [comment]
Resolved by #447, thanks!
