### ISSUE TITLE
Wishlist - Ability to choose separate directory for output files

### ISSUE THREAD

**Issue by kellyhaydon** [amiaopensource/vrecord#46]
Would be nice for us if a separate directory can be chosen to store all the gnarly non-video output files. Is this a feature anyone else would like to see?

**Comment by NMAAHC** [comment]
Yes! We Do!
This would be a major improvement, IMHO.

**Comment by dericed** [comment]
(╯°□°）╯︵   .log
.mkv ノ( º _ ºノ)

**Comment by dericed** [comment]
It's feasible, but how should this look in the GUI or vrecord.conf log. Just ask for two directories: one for media and one for logs?

**Comment by kellyhaydon** [comment]
Pretty much that is what I was thinking in the GUI...

On Sun, Mar 6, 2016 at 2:42 PM, Dave Rice <notifications@github.com> wrote:

> It's feasible, but how should this look in the GUI or vrecord.conf log.
> Just ask for two directories: one for media and one for logs?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/amiaopensource/vrecord/issues/46#issuecomment-193009721>
> .
>



-- 

*Kelly Haydon | Preservationist*
*415.558.2158 <http://415.558.2158> | kelly@bavc.org <kelly@bavc.org>*



*How do you BAVC?  *
BAVC has been an advocate for artists and media makers for almost 40
years, supplying
the tools, resources, and support they need to tell their stories.
Support BAVC today.
*www.bavc.org/donate <http://www.bavc.org/donate>*

**Comment by libbyhopfauf** [comment]
I would love that as well, Kelly!

**Comment by privatezero** [comment]
Changed the GUI to add the option to select a separate directory for logs etc.  Is this what you guys were thinking?
