### ISSUE TITLE
live  mkv chaptering?

### ISSUE THREAD

**Issue by bturkus** [amiaopensource/vrecord#461]
hi,

this is isn't something that I feel a particular personal need for, but I was wondering if vrecord could possibly evolve to offer live mkv chapter markers. Or, alternatively, if that wouldn't really work as a keystroke-type thing, would it be possible to set timestamps for chapters prior to capture, somewhere in the config menu? 

I guess the use case would be: wanting to capture the entirety of a tape, but also wanting to mark off sections for easy trimming/transcoding in post, or whatever else people use chapters for (skipping to key sections during playback, etc.). It would make some sense to me to do this during capture, as one would typically already be fast forwarding through a tape to set levels (though I suppose getting the timestamps just right could be tricky. Timecode! It's not useless!). 

ben

**Comment by dericed** [comment]
> if vrecord could possibly evolve to offer live mkv chapter markers

It's possible but the chapters would be fairly inaccurate, I'm not sure ffplay could receive keystrokes and use them to log a chapter list, but mpv via lua could do this or potentially the open terminal window. Still it would be a pretty sloppy chapter track when complete. Why not add the chapters after when the content is easier to review and time?

> would it be possible to set timestamps for chapters prior to capture

You mean to simply auto-chapter every x minutes or so? With what name or reason?

**Comment by retokromer** [comment]
>Why not add the chapters after when the content is easier to review and time?

We do it that way, and are happy with.

**Comment by bturkus** [comment]
heard heard heard. closing but will never stop dreaming...

**Comment by kieranjol** [comment]
We must never stop dreaming!
