### ISSUE TITLE
UltraStudio 4k input/output error

### ISSUE THREAD

**Issue by NMAAHC** [amiaopensource/vrecord#464]
Hi All,
We are using an Ultrastudio 4k on Macs running Mojave 10.14.5 to do transfers in vrecord. Right now we are getting errors on two systems in terminal below:
[decklink @ 0x7ff240927c00] Found Decklink mode 720 x 486 with rate 29.97(i)
[decklink @ 0x7ff240927c00] Cannot enable video input
UltraStudio 4K: Input/output error

The preview video is showing up on the Ultrastudio, but the vrecord player won't open. We would appreciate any suggestions.

**Comment by bturkus** [comment]
what version of desktop video do you have installed? have you tried updating, and also reinstalling ffmpegdecklink (`brew reinstall ffmpegdecklink`)?

**Comment by NMAAHC** [comment]
Solved! Had to reseat some cables. BM devices being finicky. Thanks Ben!
