### ISSUE TITLE
Problem instaling vrecord on mac 0S 10.13.6

### ISSUE THREAD

**Issue by dix234** [amiaopensource/vrecord#467]
I am new to all of this so bear with me:

I am getting the following error when I try to install vrecord:

 No available formula with the name "mpv" (dependency of amiaopensource/amiaos/vrecord)
Found a cask named "mpv" instead. Try
  brew cask install mpv

I installed homebrew and followed the installion steps but get stuck with the error above.
Any advice, thoughts?

Erik

**Comment by retokromer** [comment]
`mpv` has been removed recently from Homebrew. Please install the cask and report back. Thank you!

**Comment by dix234** [comment]
I  did that command and then tried to install vrecord. Still same error message. Anything else I can try?
Erik

**Comment by retokromer** [comment]
>Anything else I can try?

@dix234 Could you possibly test this patched formula https://github.com/amiaopensource/homebrew-amiaos/blob/fix_mpv/vrecord.rb and report back. I’m travelling…

**Comment by dix234** [comment]
Sorry to sound stupid. How do I use the programming in this? I am new to all the terminal stuff. I appreciate your help with this.
Erik

**Comment by retokromer** [comment]
@dix234 Oh… sorry for that! You sound not stupid at all.

You can save the amended formula as `vrecord.rb` on your computer, then drag-and-drop it into the Terminal rather than typing `vrecord` when you install:
```
brew install <drag_and_drop_the_ammended_formula>
```

**Comment by dix234** [comment]
it seems to be working now. Thanks so much,

Erik

**Comment by retokromer** [comment]
Is this still an issue?
