### ISSUE TITLE
use `mpv` cask

### ISSUE THREAD

**Issue by retokromer** [amiaopensource/vrecord#468]
The `mpv` formula has been removed from Homebrew. We should modify here in `vrecord` the messages and documentation, in order to use the cask. See https://github.com/amiaopensource/vrecord/issues/467.

**Comment by retokromer** [comment]
Another option would be to host an alternate `mpv` formula on AMIA Open Source and to use it – as we already do for `decklinksdk`, `ffmpegdecklink` and `gtkdialog`.

**Comment by privatezero** [comment]
I think that is probably something we should look into to keep the smoothness of homebrew installs for people who are less comfortable with command line!

**Comment by retokromer** [comment]
Supposing that “that” means hosting an alternate `mpv` formula here on AMIA Open Source: I’ll propose one, once I’m back from IASA/JTS. The easiest way seems to me to create a “virtual release”, because the `mpv` maintainers are not willing to make an official new release or at least a new tag. That way newer features and bug fixes are included.

**Comment by privatezero** [comment]
Yes - I was thinking of an `mpv` formula if there is indeed no simpler solution. As the QC View seems to be, anecdotally, one of the more popular modes to use vrecord in, I think that having simplicity in the `mpv` dependency part of install is a priority.

But for now at least the broken dependency won't block the install formula - thanks! Enjoy IASA!

**Comment by retokromer** [comment]
Resolved in https://github.com/amiaopensource/homebrew-amiaos/pull/204 and https://github.com/amiaopensource/homebrew-amiaos/pull/205.
