### ISSUE TITLE
audio only works in 2 stereo pair mode

### ISSUE THREAD

**Issue by kellyhaydon** [amiaopensource/vrecord#47]
Ben and I are having problems with 0.7.11 on two computers. He's on OSX 10.10.2 and I'm on 10.10.3; there are slight differences between issues. Both stations have Blackmagic 4K Extreme PCI cards installed in MacPro towers. Respective outputs are attached. 

[10.10.3-capture.txt](https://github.com/amiaopensource/vrecord/files/170019/10.10.3-capture.txt)
[10.10.2-passthrough.txt](https://github.com/amiaopensource/vrecord/files/170018/10.10.2-passthrough.txt)

10.10.2
In passthrough mode, the capture window stays open for exactly 10.55 seconds then shuts down. In capture mode, it doesn't stay open a half a second. 

10.10.3
Passthrough mode works as expected. In capture mode, it doesn't stay open a half second.

**Comment by MIAPtech** [comment]
I updated our MacPro towers (running 10.10.5) in the MIAP lab this week to 0.7.11, started receiving the exact same issue Kelly describes above on her 10.10.3 setup during capture. Passthrough works fine, capture mode immediately closes, gives the same error:

[MIAP_lab_10.10.5_capture_error.txt](https://github.com/amiaopensource/vrecord/files/198369/MIAP_lab_10.10.5_capture_error.txt)

Any update on this problem?
- Ethan

**Comment by dericed** [comment]
What audio channel mapping are you using?

**Comment by MIAPtech** [comment]
1 stereo track

**Comment by dericed** [comment]
Same results with '2 stereo track'?

**Comment by MIAPtech** [comment]
That does the trick! Capture seems to run fine now. Is this an issue with the software or am I just incorrectly mapping (what I thought was) a stereo track?

**Comment by dericed** [comment]
can you send the corresponding ffmpeg.log for the problematic capture

**Comment by MIAPtech** [comment]
[test_signal_ffmpeg_20160331-164716.txt](https://github.com/amiaopensource/vrecord/files/198573/test_signal_ffmpeg_20160331-164716.txt)

**Comment by dericed** [comment]
please checkout and test https://github.com/amiaopensource/vrecord/tree/fix-audio-filterchains

**Comment by MIAPtech** [comment]
1 stereo track capture now seems to run as expected with this update (log of successful capture below)
[test_audio2_ffmpeg_20160404-102759.txt](https://github.com/amiaopensource/vrecord/files/202638/test_audio2_ffmpeg_20160404-102759.txt)

**Comment by dericed** [comment]
@MIAPtech, thanks for testing. I merge the commit and made a new release. Please `brew update && brew upgrade` to install v0.7.12. @kellyhaydon I'm going to close this issue, but please re-open if the update doesn't work for you.
