### ISSUE TITLE
File input mode broken

### ISSUE THREAD

**Issue by privatezero** [amiaopensource/vrecord#493]
Latest updates for capture input choice appears to have broken running vrecord via a sample file input.

**Comment by privatezero** [comment]
Tracked this down to the addition of [this line](https://github.com/amiaopensource/vrecord/blame/master/vrecord#L1226) which causes vrecord to attempt to apply the [timecode setting](https://github.com/amiaopensource/vrecord/blame/master/vrecord#L885) to the filter chain, which breaks it with all the test files I have used.

@dericed, since the `ALT_INPUT` flag is usually (I think)  used in debugging, how would you feel about just dropping line 1226?

**Comment by dericed** [comment]
perhaps at this point it makes more sense to have the file input as an alternate input to avfoundation and decklink, rather than an exception like it currently is

**Comment by privatezero** [comment]
I think that the current form works pretty well for debugging, so I wouldn't necessarily want to change it up to that extent - it is basically just as easy to write `vrecord -i ./some-file.mkv` as it is to write `vrecord ./some-file.mkv`, and makes for an easy back and forth when testing things. But if people are using it for non-debugging purposes I could maybe see a little bit of benefit to adding it as an alternate input. Are you aware of any other use cases?
