### ISSUE TITLE
Create ReadMe

### ISSUE THREAD

**Issue by dinahhandel** [amiaopensource/vrecord#5]
Create ReadMe for vrecord.

**Comment by jfarbowitz** [comment]
Summary on how to intstall/use VRecord

Similar to LTOpers

**Comment by epiil** [comment]
I'll let @jfarbowitz teach vrecord to his eager Video Preservation 1
professors and classmates this semester if_and_only_if he writes a good
ReadMe for this repo.

**Comment by jfarbowitz** [comment]
*gulp*

**Comment by jfarbowitz** [comment]
I think I've established a decent Readme at this point. I envision a few more images to add and a few more paragraphs. 

If you have any additional feedback on the Readme, please place it in this issue.

**Comment by jfarbowitz** [comment]
Closing the issue as the read me. Is fairly mature at this point. Readme additions can be opened up as separate bugs.
