### ISSUE TITLE
vector probs

### ISSUE THREAD

**Issue by bturkus** [amiaopensource/vrecord#50]
Not sure exactly what's causing the problem (FFmpeg 3.1.1?), but vectorscope is off by some degree, and flipped along the horizontal axis. See here:

![screen shot 2016-07-08 at 5 00 32 pm](https://cloud.githubusercontent.com/assets/8987230/16740105/64f26cec-4752-11e6-8028-566e7a8b6ec9.png)

**Comment by dericed** [comment]
Ya, the ffmpeg vectorscope used to require being flipped, but now it's flipped by default.

**Comment by privatezero** [comment]
Unflipped the vectorscope as well as changed filters to take advantage of ffmpeg graticule function.
