### ISSUE TITLE
"Audio Only" Capture Option

### ISSUE THREAD

**Issue by bturkus** [amiaopensource/vrecord#509]
Hi,

I was hoping someone might be able to help me add an "audio only" capture option to vrecord. I know it may seem a bit odd, but the use case would be people interested in digitizing audio who may not have the means to purchase a separate audio converter/interface. This is something that's come up a lot in @XFRCollective, when we're asked to put together low-cost, efficient digitization stations. Our current, kinda hacky workflow for "audio only" BM capture is to route the signal through the capture card, open Media Express to kick things off, then open Audacity or Audiorecorder to create the digital file. 

I've had some success doing a version of the following, essentially sending in video + audio but killing the video at the point of creating a file :

`
/usr/local/opt/ffmpegdecklink/bin/ffmpeg-dl -f decklink -audio_depth 32 -i 'UltraStudio HD Mini' -vn -c:a pcm_s24le /Users/benjaminturkus/Desktop/audio002.wav
`
But in chatting with @dericed, he suggested investigating whether one of the decklink inputs would still process audio without a video accompaniment (I think this would be the ideal, though it may not be possible).

I also made a bit of progress in trying to add this to vrecord myself, but I quickly kinda came up against the limits of my bash knowledge. Any help at all would be appreciated, and I think this could be the kind of thing that meets a specific need yet opens up vrecord to a range of different users.

Thanks!

Ben

**Comment by digitensions** [comment]
+1

My former employers capture sepmag via a steenbeck to video stream because they haven’t an audio only capture option. They use vrecord for FFV1 video tape workflows and I’m certain this would be a helpful addition.

Great idea Ben!

**Comment by libbyhopfauf** [comment]
Occasionally with some of the oral history projects that we have helped digitize videotape for, the tapes are super cheap VHS that have such poor video quality (I'm talking pure snow) we have been extracting the audio as a WAV file, which has been fine, but if this option was available, we would use it from time to time!

**Comment by privatezero** [comment]
Hey @bturkus! This is actually the next thing I was planning to do! (one of the reasons I wanted to rework the phase scopes etc). I was planning on doing it by adding another sub menu like the way that DV is selected rn. Since we are already set up to grab stuff from avfoundation devices, this is very doable!

**Comment by kellyhaydon** [comment]
+1

My use case: Music documentation on 1/2” open reel videos that are pretty
much an all-black screen with great audio. This option would be useful for
making some smart storage decisions (don’t @ me).

On Thu, Feb 20, 2020 at 5:40 PM Andrew Weaver <notifications@github.com>
wrote:

> Hey @bturkus
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_bturkus&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=j095mgBqNgHRwp0uxgGyeA&m=EKts5K0DKhBXU1QjO7rcfsu3vkcBNu-G0rogeq7OadE&s=3j1zgyuYAOXvPwS6TM8cebd36p2EE5CN3ZTbek8prQo&e=>!
> This is actually the next thing I was planning to do! (one of the reasons I
> wanted to rework the phase scopes etc). I was planning on doing it by
> adding another sub menu like the way that DV is selected rn. Since we are
> already set up to grab stuff from avfoundation devices, this is very doable!
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_amiaopensource_vrecord_issues_509-3Femail-5Fsource-3Dnotifications-26email-5Ftoken-3DACH7YUO2KE345VQ7BGJWYBTRD4BGNA5CNFSM4KYVWNQKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEMQVS5Y-23issuecomment-2D589388151&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=j095mgBqNgHRwp0uxgGyeA&m=EKts5K0DKhBXU1QjO7rcfsu3vkcBNu-G0rogeq7OadE&s=bUWxxi_IXUCOZhZ6Ys1iefBkWJhLz3uNxvG-ZAw9Zjg&e=>,
> or unsubscribe
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ACH7YUP6K5J7QOVGRJ6RET3RD4BGNANCNFSM4KYVWNQA&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=j095mgBqNgHRwp0uxgGyeA&m=EKts5K0DKhBXU1QjO7rcfsu3vkcBNu-G0rogeq7OadE&s=raQqostMeRMz5q6iMZWoxcVc-Vai9n_QSvf9RVDUPko&e=>
> .
>
-- 
Kelly Haydon
Audiovisual Archivist
NYU Special Collections
Email: kelly.haydon@nyu.edu
*she/her/hers*

*NYU Special Collections – Fales Library, Tamiment Library & Robert F.
Wagner Archives, and University Archives – is undergoing a major renovation
over the next two years. There may be an impact on services and
collections. All repositories will be closed to researchers from May 21,
2020 – September 7, 2020. For further information, please check our
renovation website: **https://wp.nyu.edu/library-renovation/
<https://wp.nyu.edu/library-renovation/> *
