### ISSUE TITLE
Wishlist - Timecode tracks

### ISSUE THREAD

**Issue by kieranjol** [amiaopensource/vrecord#51]
Hello,

I've noticed that there is no timecode information recorded when using vrecord. 
I'm using an UltraStudio 4K in ElCapitan.
I"m thinking of something like the tmcd track in MOV. This information is carried over as metadata when transcoding to FFV1, but I'm not sure if it's possible to record something like starting timecode in some way when capturing directly to ffv1.mkv?

```
 Stream #0:0(eng): Video: ffv1 (FFV1 / 0x31564646), yuv422p10le, 720x576, SAR 47:43 DAR 235:172, 25 fps, 25 tbr, 1k tbn, 1k tbc (default)
    Metadata:
      HANDLER_NAME    : Apple Alias Data Handler
      TIMECODE        : 00:00:01:10
      ENCODER         : Lavc57.41.102 ffv1
      DURATION        : 00:00:29.000000000
```

Is there any interest in this feature, or is it a limitation of bmdtools/vrecord?

**Comment by dericed** [comment]
There's a few issues to resolve. I don't think the bmdtools reads or passes timecode. bmdtools is piped to ffmpeg via a nut container which also doesn't support timecode. There's an opportunity to switch from bmdtools to ffmpeg's own decklink support (which has been improved recently), but I don't think that supports timecode either.

**Comment by kieranjol** [comment]
As an interim solution for vrecord, could mkvpropedit add a timecode tag that contains the starting timecode? ffmpeg generates a tmcd track from an mkv with that tag when you ffmpeg -i input.mkv http://output.mov 
I've found it useful because our prores mezzanines have that timecode track anyhow which is handy for access purposes.

**Comment by dericed** [comment]
resolved in https://github.com/amiaopensource/vrecord/pull/381

**Comment by kieranjol** [comment]
Yay

**Comment by kellyhaydon** [comment]
HEART EMOJIS

On Mon, Nov 5, 2018 at 3:12 PM kieranjol <notifications@github.com> wrote:

> Yay
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_amiaopensource_vrecord_issues_51-23issuecomment-2D436018665&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=j095mgBqNgHRwp0uxgGyeA&m=p1FqsJcy6VkYbwkPZA2aVkgxU8FKmA-XEO357NPzGw0&s=Z_uCqAjx_C2UoFy0l3nMyh_rO8OlkpS_c4F3QQc_kPk&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AI-5F8USXQ-2DLMC3BuIdlti5nqeSdzFv-2DXrks5usJvAgaJpZM4JXA8O&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=j095mgBqNgHRwp0uxgGyeA&m=p1FqsJcy6VkYbwkPZA2aVkgxU8FKmA-XEO357NPzGw0&s=UL6mB9yhWRER0TUgShWJE1095ExzoeGy-h2B3BGfGVo&e=>
> .
>


-- 
Kelly Haydon
Audiovisual Archivist
Fales Library and Special Collections
New York University
Phone: 212 998-2593 <(212)%20998-2593>
Email: kelly.haydon@nyu.edu

*Please note that email is the fastest way to reach me*
