### ISSUE TITLE
DV capture: add test that running on macOS

### ISSUE THREAD

**Issue by retokromer** [amiaopensource/vrecord#512]
Since `DV capture` is currently working on macOS only, a test making sure that the program is not running under another OS should be added.

**Comment by dericed** [comment]
@privatezero is looking at adding a conditional behavior to use the iec61883 device in ffmpeg or dvgrab in place of avfctl depending on the os.

**Comment by retokromer** [comment]
Indeed, I have noticed https://github.com/amiaopensource/vrecord/issues/559.

**Comment by dericed** [comment]
fixed in https://github.com/amiaopensource/vrecord/commit/478c7491332b5b11bcc41a574b57f5fbf9c4f856
