### ISSUE TITLE
Audio encoding always A_VORBIS

### ISSUE THREAD

**Issue by nihelmasell** [amiaopensource/vrecord#513]
Hi, I have captured footage both from PAL and NTSC sources, and both selecting FLAC and PCM encoding in the config window. No matter what, I get a file with 112 kb/s A_VORBIS codec. I performed like 15 full VHS captures so far. I have an Intensity Shuttle capture device, installed in a Macbook pro Late 2013. I capture mainly from composite and component input. The initial installation of vrecord was made less than a month ago, so I presume it's one the latest version. Anyone can help?

**Comment by dericed** [comment]
Hi @nihelmasell, this bug was fixed in the latest release.

**Comment by dericed** [comment]
Hi @nihelmasell, going to close, but please re-open if you have this issue with the latest release.
