### ISSUE TITLE
dv capture - slow dts reordering

### ISSUE THREAD

**Issue by bturkus** [amiaopensource/vrecord#514]
Hi,

We've been using vrecord for dv capture for a few weeks (THANK YOU THANK YOU THANK YOU), and we're finding that, on occasion, after quitting a capture there can be a very slow, drawn out process in which FFmpeg appears to be doing something related to reordering the dreaded non-monotonous DTS. Looks like this:

```
[avfoundation @ 0x7fbe99800000] DTS 0 < 24057367 out of order
[rawvideo @ 0x7fbe9a06e000] Application provided invalid, non monotonically increasing dts to muxer in stream 0: 721 >= 0
[rawvideo @ 0x7fbe9a072600] Application provided invalid, non monotonically increasing dts to muxer in stream 0: 721 >= 0
av_interleaved_write_frame(): Broken pipe
Error writing trailer of pipe:: Broken pipe
frame=  723 fps=0.2 q=-1.0 Lq=-1.0 size=   84727kB time=00:00:24.09 bitrate=28811.1kbits/s speed=0.00667x    
video:169453kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
Conversion failed!
````
Any thoughts about what causes this, whether it could be improved, or if there could possibly be a way of alerting the user to this process (right now FFmpeg just kinda hangs up after ` Stream #0:0 -> #1:0 (copy) `, and for a relatively short, 24 sec capture, it seemed to take 10-15 minutes to wrap this up) would be very appreciated.

Thanks!

Ben

**Comment by dericed** [comment]
cc'ing @thiloborgmann.
But yes ffmpeg will often hang and become unresponsive while awaiting more raw data from avfoundation so the usual method to stop ffmpeg doesn't work as well.

**Comment by dericed** [comment]
vrecord switched from avfoundation via ffmpeg to avfctl, so this might not be relevant any longer. @privatezero can you test and perhaps close.

**Comment by retokromer** [comment]
I suggest to close this one.

**Comment by dericed** [comment]
That's valid, vrecord no longer use ffmpeg/avfoundation for dv.
