### ISSUE TITLE
delete GTK_RECENT_DIR?

### ISSUE THREAD

**Issue by retokromer** [amiaopensource/vrecord#520]
What is the variable `GTK_RECENT_DIR` for?

If I am not missing something, the following lines can be deleted:

https://github.com/amiaopensource/vrecord/blob/62d85199ce1b573a28b02464ba823a9699da7844/vrecord#L9

https://github.com/amiaopensource/vrecord/blob/62d85199ce1b573a28b02464ba823a9699da7844/vrecord#L526-L528

**Comment by dericed** [comment]
It was related to some work that @siggaregina had been working on that isn't active now. No objection to deleting the lines.
