### ISSUE TITLE
maybe VU meters

### ISSUE THREAD

**Issue by jshupeGitHub** [amiaopensource/vrecord#531]
it would be "nice" to have VU meters as one is doing a capture

mpv allows this functionality
like so
mpv '--lavfi-complex=[aid1]asplit[ao][a];[a]showvolume[vo]' --alpha=no myVideo.mkv

to say it another way

when you hit Enter to start recording...
and the window showing the visual part of the signal opens
*also  display vu meters of some sort

I like the method shown by mpv because they are "led" digital  like
where as VLC  has analog "swinging needle like
In audio/visualization/vumeter

cheers

jS

**Comment by privatezero** [comment]
Hi @jshupeGitHub, the `showvolume` filter has been integrated into the passthrough mode for calibration via the `Audio + Video` filter that can be selected in the GUI. It was added to passthrough mode only (as opposed to capture) as an extra precaution against complicated filter chains causing issues with poor archival transfers on lower powered systems.

Both the current filter chain in vrecord as well as the example that you provided are not VU meters per se, they are peak meters. That filter also supports RMS metering, is that something you are interested in?

**Comment by jshupeGitHub** [comment]
right - peak not average.... i tend to call them all VU ;; just as I call all adjustable end wrenches "crescent" wrenches ... anyhoo...
Yes - I would be interested in being able to "see" the audio as recording...
so that an onGoing assessment & documentation can be made.
I understand the concern about lower powered systems...
so make it a High Performance option ; either by selection or build.
maybe

Further ... I have been wondering on a means of doing TimeStamped entry as an asset is being captured...
a thing I have tried at ( not really working ) is a selection of pull downs menu
offering a selection of "problems" [ eg : edge damage , audio missing , transmission err ]
with the notion being ....as signal rolls through operator can make realtime doc of Issues .
yielding a log
Time problem
Time problem
or to say That another way ... QCTools and file eval is Valued
also of value is the expert observations of the tech who has laid hands on tape,vtr etc.

nice talk
best wishes

**Comment by dericed** [comment]
maybe fixed via https://github.com/amiaopensource/vrecord/pull/614? @privatezero ?

**Comment by privatezero** [comment]
yup  - that should do it! As always, caveat emptor though!

**Comment by privatezero** [comment]
Closing as mostly resolved in https://github.com/amiaopensource/vrecord/pull/614. If there is a continued demand for a VU vs peak meters we could add in future (at the expense of cluttering the GUI a tad more)
