### ISSUE TITLE
add dvrescue logo to the dv tab of vrecrd

### ISSUE THREAD

**Issue by dericed** [amiaopensource/vrecord#560]
getting that tab stylish like the audio tab

**Comment by privatezero** [comment]
Would a slightly modified image help avoid confusion with the actual DV Rescue app that is ultimately in the pipeline?

**Comment by retokromer** [comment]
Please don’t forget to update the documentation accordingly.

**Comment by privatezero** [comment]
@retokromer we will definitely seek to keep documentation in sync with new features. Not sure what you are referring to, however, in the context of a logo addition though - could you clarify?

**Comment by retokromer** [comment]
@privatezero _In primis_ at the pages https://github.com/amiaopensource/vrecord/blob/master/Resources/Documentation/dv_info.md and https://github.com/amiaopensource/vrecord/blob/master/Resources/Documentation/gui_mode.md.

**Comment by privatezero** [comment]
Ah - excellent, thanks for the clarification

**Comment by privatezero** [comment]
Resolved in https://github.com/amiaopensource/vrecord/pull/562
