### ISSUE TITLE
no controlling deck control 

### ISSUE THREAD

**Issue by bturkus** [amiaopensource/vrecord#567]
Hi!

I started testing out vrecord's new deck control functionality, and it appears that it's not working 100%. With 9-pin connected and the VCR in remote mode, when I push the Deck Control button in gtkdialog, the status changes to N/A and the correct VITC timecode pops right up. But from here, when I push any of the control buttons (play, ff, rewind, eject, etc.), it doesn't seem to have any effect at all. However, when I manually control the tape with the VCR, the gtkdialog status does update (to Play, Shuttle forward, etc.) to reflect what's actually happening (the timecode also advances to match the correct values).

This is also a weird small thing, but when I enable deck control, push any of the buttons that don't seem to do anything at the moment, then push passthrough, vrecord crashes with the following message:

```
/usr/local/bin/vrecord: line 1178: Issued: command not found
/usr/local/bin/vrecord: eval: line 1179: syntax error near unexpected token `('
/usr/local/bin/vrecord: eval: line 1179: `Error sending command (InLocal mode error)'
 2020-07-15T14:46:49 - vrecord exited a form in an unexpected way, please report this error to https://github.com/amiaopensource/vrecord/issues
```
I'm guessing this is not super important and will get resolved with the larger issues, but I wanted to point it out.

Thanks!

Ben

**Comment by dericed** [comment]
Without vrecord, could you try running `deckcontrol rewind` or instead of rewind use fastforward, play, stop, etc? If that works, then start the vrecord gui, toggle the deckcontrol button in the gui on, then try the deckcontrol command again.

**Comment by bturkus** [comment]
When running deckcontrol commands with vrecord closed, I'm getting ```Error sending command (InLocal mode error)Error sending command (InLocal mode error)```. I've definitely got the machine in remote mode, so I'm not really sure what's happening. Will try another deck now.

**Comment by bturkus** [comment]
It's working on another machine, and it's so great! Guess I gotta read a manual...

**Comment by privatezero** [comment]
Thanks for the testing! I'd say you can close, since issue appears resolved!

**Comment by retokromer** [comment]
>Yeah I'm idiot.

**NO!** Some others are in you country, not you.
