### ISSUE TITLE
vrecord dv firewire deck does not show up

### ISSUE THREAD

**Issue by billbrand** [amiaopensource/vrecord#583]
I am trying to ingest dv via firewire with vrecord from a DVCAM deck and a Digital 8 Camcorder.  Neither shows up in the "select a DV device" window.  If I run iMovie they do show up, so I know the connection is good even if iMovie is not!  :)  Am I missing a software component or set-up step?  

Here's what the Config shows:
VRECORD_VARS_FILE="/tmp/v__usr_local_bin_vrecord_variables.txt"
OS_TYPE="macOS"
RESOURCE_PATH="/usr/local/opt/vrecord"
DEFAULTFONT="/System/Library/Fonts/Supplemental/Andale Mono.ttf"
CORE_COUNT="4"
OPEN_COMMAND="open"
ZCAT_COMMAND="gzcat"
COMPUTER_MODEL_NAME="iMac"
DIR_SELECTION_DIALOG="Select an existing folder (or drag/drop one below). File System/Volumes for external media."
COMPUTER_MODEL_ID="iMac17,1"
COMPUTER_PROCESSOR_NAME="Quad-Core Intel Core i7"
COMPUTER_PROCESSOR_SPEED="4 GHz"
COMPUTER_PROCESSOR_COUNT="1"
COMPUTER_MEMORY="32 GB"
COMPUTER_SERIAL="D25R41GGGQ17"
CAPTURELOGSUFFIX="_vrecord_input.log"
TIMECODELOGSUFFIX="_frame_timecodes.txt"
BREW_PREFIX="/usr/local/opt/ffmpegdecklink"
FFMPEG_BIN="/usr/local/opt/ffmpegdecklink/bin/ffmpeg-dl"
FFPLAY_BIN="/usr/local/opt/ffmpegdecklink/bin/ffplay-dl"
FFPROBE_BIN="/usr/local/opt/ffmpegdecklink/bin/ffprobe-dl"

**Comment by billbrand** [comment]
Hi Dave!  Thanks for responding   If I run avfctl -list_devices after running vrecord -e, I get nothing.  If I run avfctl -list_devices  before running vrecord, I get "zsh: command not found: avfctl"

**Comment by dericed** [comment]
Please install https://mediaarea.net/download/snapshots/binary/dvrescue/20200701-2/dvrescue_CLI_0.20.06.20200701_Mac.dmg and retry.

**Comment by dericed** [comment]
Good luck! Feedback welcome. There's a pull request at https://github.com/amiaopensource/homebrew-amiaos/pull/259/files under review, but if merged it should fix this issue.

**Comment by dericed** [comment]
Will close, but I think the updates in dvpackager in the dvrescue project should facilitate rewrapping the dv stream with audio normalized to 48k to solve the referenced issue.
