### ISSUE TITLE
Line 390 Syntax Error

### ISSUE THREAD

**Issue by alexhabgood** [amiaopensource/vrecord#588]
Hello,

I've recently updated to the latest build of vrecord (2020-08-05). However, I now get the following error whenever I try to start it up:

/usr/local/bin/vrecord: line 390: syntax error near unexpected token `;;'
/usr/local/bin/vrecord: line 390: `            "FFV1 version 3")   SUFFIX="_ffv1" ;;'

I've tried using the -e & -x to reset and edit the configuration file, but get stopped with the same error. 

It could be an issue with my set up? It's running on a Mac with High Sierra 10.13.6.

Thanks,

**Comment by dericed** [comment]
could you run `brew install bash` and retry

**Comment by alexhabgood** [comment]
brew install bash gives me:

bash 5.0.18 is already installed and up-to-date
To reinstall 5.0.18, run `brew reinstall bash`

So I reinstalled bash and restarted the terminal. But I'm still getting the same error with vrecord.

**Comment by alexhabgood** [comment]
brew install bash gives me:

bash 5.0.18 is already installed and up-to-date
To reinstall 5.0.18, run `brew reinstall bash`

So I reinstalled bash and restarted the terminal. But I'm still getting the same error with vrecord.

**Comment by dericed** [comment]
thx, i have a fix in mind and can try to post it tonight

**Comment by alexhabgood** [comment]
Great! Thanks for helping me out.

**Comment by retokromer** [comment]
I guess, it’s running the old Bash 3.2.57, kindly provided by Apple, rather than the current one, installed by Homebrew.

**Comment by alexhabgood** [comment]
I initially thought this was the problem too, it having an issue with case. So, I added the updated shell version to /etc/shells and used chsh -s to set it as the default. Now when I echo $BASH_VERSION it shows 5.0.18. Did I miss a step?

**Comment by retokromer** [comment]
You can check with `bash -c 'echo $BASH_VERSION'` which version is actually running, when multiple are installed.

**Comment by alexhabgood** [comment]
When I enter bash -c 'echo $BASH_VERSION', it comes up with the 3.2.57 version. So looks like this could be the problem!

I'll see if I can get this properly switched over tommorow.

**Comment by retokromer** [comment]
Yep, that seems to be the problem. Possibly, this may be useful: Daniel Weibel: [Upgrading Bash on macOS](https://itnext.io/upgrading-bash-on-macos-7138bd1066ba). But, of course, you can also wait for Dave’s patch.

**Comment by alexhabgood** [comment]
This problem is now fixed. So I'm going to close the case.

It was caused by starting vrecord in an the outdated version of bash (3.2.57). My problem was in /etc/paths. I had /usr/bin, above /usr/local/bin in the hierarchy, which caused bash to default to the older version, as shown in this article: https://scriptingosx.com/2019/02/install-bash-5-on-macos/.

Thanks Reto and Dave for your help! Much appreciated.

**Comment by retokromer** [comment]
Thank you, @alexhabgood, I didn’t know that article. Glad it worked.
