### ISSUE TITLE
horizontal position cross-hairs

### ISSUE THREAD

**Issue by bturkus** [amiaopensource/vrecord#603]
Wondering about the possibility of adding some sort of visualization to vrecord that could help with the process of setting the horizontal position of the video. Assuming the positioning is consistently off-center, I try to make adjustments using a TBC, but often, when I eyeball it, using a band of yellow broadcast range pixels as my guide, the resulting sometimes isn't as well positioned as it could be. Is there any chance we could add something like cross-hairs, crop detect, or corners to make this easier?

Thanks!!

**Comment by dericed** [comment]
Would something like the 'corners' view in qctools help with this?

**Comment by bturkus** [comment]
yeah i think it could. Would that be easier to implement/potentially more useful than CropW (in your opinion)?

<img width="1147" alt="Screen Shot 2020-10-06 at 11 15 04 AM" src="https://user-images.githubusercontent.com/8987230/95224711-05ad5a80-07c9-11eb-828c-42be833dd4ac.png">

**Comment by dericed** [comment]
Would it be preferable to have something less instantaneous while calibrating this? For instance, I'm thinking of how in qctools 'lines over time' it shows the same row of video pixels stacked.
