### ISSUE TITLE
Blackmagic audio device check

### ISSUE THREAD

**Issue by privatezero** [amiaopensource/vrecord#619]
Should fix [this](https://github.com/amiaopensource/vrecord/blob/master/vrecord#L329) check so that it works in `sh` (as well as [this one](https://github.com/amiaopensource/vrecord/blob/master/vrecord#L1211))

**Comment by retokromer** [comment]
And [this](https://github.com/amiaopensource/vrecord/blob/7f4b82bd13d8c7b1093e06ecbbcccf4ec6701574/Resources/vrecord_functions#L158) as well, I presume.

**Comment by privatezero** [comment]
Nice catch! I haven't tested DV on Linux yet since the functions were externalized, but yes, I bet that line is broken as well

**Comment by privatezero** [comment]
Should be fixed in https://github.com/amiaopensource/vrecord/pull/633
