### ISSUE TITLE
vector markers seem off

### ISSUE THREAD

**Issue by bturkus** [amiaopensource/vrecord#63]
looking for confirmation; only tested on one computer. See pic:

![screen shot 2016-08-22 at 5 21 27 pm](https://cloud.githubusercontent.com/assets/8987230/17901419/30372faa-6918-11e6-9032-0a0d1ab441e7.png)

**Comment by bturkus** [comment]
0.7.17

**Comment by dericed** [comment]
grats should be adjusted to 601. It may be on the default 709.

**Comment by richardpl** [comment]
It's default to auto, but if your device does not export it, it must be set to what it outputs.

**Comment by dericed** [comment]
It is receiving a pipe of uncompressed video in a nut stream from bmdcapture, so there is no method to transport the colorspace info, but in general vrecord only works with sd source, so we can fix it to 601 for now.

**Comment by privatezero** [comment]
Just changed it to be set to 601 instead of the default auto and made a new release.
