### ISSUE TITLE
phase/polarity inversion CH3&4

### ISSUE THREAD

**Issue by bturkus** [amiaopensource/vrecord#632]
Hi,

I was wondering about possibility of adding a CH3&4 phase inversion to vrecord. As far as I can tell, the "Invert CH2" option only works for CH2, and we recently had a case in which both stereo tracks of a 4-CH recording were inverted. I'd be happy to give this a try myself, but I guess I'm wondering: would it make the most to have different PHASE_VALUE variables for both tracks, to accommodate the rare situation in which one track was out of phase but the other not?

Thanks,

Ben

**Comment by dericed** [comment]
Maybe it needs to be stored as an array of channel numbers, like PHASE_FLIP="1,3" rather than arbitrarily stuck at one value.

**Comment by privatezero** [comment]
Should be resolved by https://github.com/amiaopensource/vrecord/pull/634

**Comment by bturkus** [comment]
@privatezero @dericed thank you so much for doing this! I'm sorry I failed on the testing front (too much art school)!
