### ISSUE TITLE
[question] vrecord on ARM64

### ISSUE THREAD

**Issue by retokromer** [amiaopensource/vrecord#646]
Has `vrecord` be tested on the new Apple M1 yet or “only” on Intel?

**Comment by dericed** [comment]
I haven't tested it on the new Apple M1 and I'm not sure if my tests have been only on Intel.

**Comment by retokromer** [comment]
LOL, if it was on macOS and not ARM, then it’s Intel, isn’t it? PowerPC is most probably too old, and 680x0 and 6502 are very certainly too old.

Then I’ll run tests on a new Apple computer. My question was just to avoid useless work. Thanks for the answer.

**Comment by retokromer** [comment]
Successfully tested on Mac mini (M1, 2020).
