### ISSUE TITLE
mpv issue w/ vrecord 2020-10-21?

### ISSUE THREAD

**Issue by bturkus** [amiaopensource/vrecord#652]
hi,
I noticed this a while back but failed to report: for some reason, on a Mac on the latest release of vrecord, I can't seem to get QC view (mpv) to work at all. I'm not getting much in the way of error messaging, but when I select QC view for either playback or passthrough, vrecord seems to get hung up and mpv fails to open.

Running vrecord -G -P, this is what I'm seeing:

```
MY-LPAMI-056430:~ benjaminturkus$ vrecord -G -p
STEPS 1
PLAY mpv --no-osc --load-scripts=no --script=/usr/local/opt/vrecord/qcview.lua --really-quiet --title=mode:passthrough - video:'sdi' audio:'embedded' - to end recording press q, esc, or close video window -
RECORD /usr/local/opt/ffmpegdecklink/bin/ffmpeg-dl -nostdin -nostats -timecode_format none -loglevel info -f decklink -draw_bars 0 -audio_input embedded -video_input sdi -format_code ntsc -channels 8 -audio_depth 32 -raw_format yuv422p10 -i UltraStudio HD Mini -map_metadata 0:s:v:0 -color_primaries smpte170m -color_trc bt709 -colorspace smpte170m -color_range mpeg -metadata creation_time=now -filter_complex [0:v:0]setsar=40/27,setdar=4/3; [0:a:0]pan=stereo| c0=c0 | c1=c1[stereo1] -map [stereo1] -f   -c copy -c:a pcm_s24le -map 0 -f matroska -write_crc32 0 -live true -

```

Any advice would be really appreciated! This could definitely be something I'm doing!

**Comment by retokromer** [comment]
What does `mpv --version` respond?

**Comment by bturkus** [comment]
```
mpv 0.33.0 Copyright © 2000-2020 mpv/MPlayer/mplayer2 projects
 built on Sat Jan 16 08:14:23 GMT 2021
FFmpeg library versions:
   libavutil       56.51.100
   libavcodec      58.91.100
   libavformat     58.45.100
   libswscale      5.7.100
   libavfilter     7.85.100
   libswresample   3.7.100
FFmpeg version: 4.3.1
```
I also forgot to mention: I tried building mpv from source and it didn't seem to make any difference. Thanks!

**Comment by retokromer** [comment]
Thank you, @bturkus! This is the same version we have in production here. I will try to delve into it during the weekend, unless others are faster than me.

**Comment by privatezero** [comment]
Thanks @retokromer - I most likely won't have time before then to dive into MPV so any insight is appreciated!

**Comment by retokromer** [comment]
To me it seems a regression in `vrecord`.
