### ISSUE TITLE
Record not working

### ISSUE THREAD

**Issue by alexhabgood** [amiaopensource/vrecord#659]
I've just installed vrecord (2021-01-25) on a computer with the following:
-Ubuntu 20.04
-Bash 5.0.17
-Black Magic Desktop Video 12.0
-Blackmagic Decklink Duo

I followed this guide for the install, which seemed to go through without any issue: https://github.com/amiaopensource/vrecord/blob/main/Resources/Documentation/linux_installation.md)

Passthrough mode seems to be working fine. However, I can't get record working. My config file is attached. I've also attached trace logs, to illustrate the issue.

vrecord_trace1.log - I ran _**vrecord -g**_, then clicked the record option. This returns the error: _**vrecord exited a form in an unexpected way (EXIT=record)**_

vrecord_trace2.log - I ran _**vrecord -r**_. This returns the error _**Conversion failed!**_

[vrecord_config.log](https://github.com/amiaopensource/vrecord/files/5957664/vrecord_config.log)
[vrecord_trace1.log](https://github.com/amiaopensource/vrecord/files/5957665/vrecord_trace1.log)
[vrecord_trace2.log](https://github.com/amiaopensource/vrecord/files/5957666/vrecord_trace2.log)

Thanks in advance!

**Comment by dericed** [comment]
Can you verify that Media Express works for you?
Also please run `vrecord -g -G`, go to edit mode and verify your settings and then click record, and share that terminal output.

**Comment by alexhabgood** [comment]
Media Express works.

Going through the gui setting menu gives a similar result to vrecord_trace2.log. See attached.

[vrecord_trace3.log](https://github.com/amiaopensource/vrecord/files/5958109/vrecord_trace3.log)

**Comment by dericed** [comment]
Do you mind running this without the -x.

**Comment by alexhabgood** [comment]
Here you go:

[vrecord_conversionfailed.log](https://github.com/amiaopensource/vrecord/files/5958166/vrecord_conversionfailed.log)

**Comment by dericed** [comment]
Sorry, could you run `vrecord -g -G` with no -x and send that. That output makes it easier to see the commands that are constructed.

**Comment by alexhabgood** [comment]
Ah sorry, my confusion. I wasn't aware of that feature: 

[vrecord_conversionfailed2.log](https://github.com/amiaopensource/vrecord/files/5958195/vrecord_conversionfailed2.log)

**Comment by dericed** [comment]
Can you switch from "Quality Control View (mpv)" to any non-mpv player? There's an issue with vrecord determining how many steps the recording process needs.

**Comment by bturkus** [comment]
Have you tried switching from QC view/mpv to any other visualization?

**Comment by alexhabgood** [comment]
Switched to "Audio + Visual". Now neither passthrough or record work.

could this error message be pointing to the issue?
**_Gtk-Message: 12:53:58.343: Failed to load module "atk-bridge"
Gtk-Message: 12:53:58.347: Failed to load module "canberra-gtk-module"_**

[vrecord_pass.log](https://github.com/amiaopensource/vrecord/files/5958292/vrecord_pass.log)
[vrecord_record.log](https://github.com/amiaopensource/vrecord/files/5958293/vrecord_record.log)

**Comment by dericed** [comment]
Another test, could you change the QCTools setting from "Yes concurrent" to another option

**Comment by alexhabgood** [comment]
With QCTools turned off:

[vrecord_pass2.log](https://github.com/amiaopensource/vrecord/files/5958333/vrecord_pass2.log)
[vrecord_record2.log](https://github.com/amiaopensource/vrecord/files/5958334/vrecord_record2.log)

**Comment by privatezero** [comment]
I believe I've been able to repeat this issue on Ubuntu 20.04 using virtual input. I think I'm on the trail of tracking this down - it appears to be something possibly related to linuxbrew and library issues compiling ffmpeg-dl and ffplay-dl.

**Comment by retokromer** [comment]
@privatezero In my opinion, for Linux you need now, because there was a change in the package:
```ruby
on_linux do
  depends_on "libxv"
end
```
(At least, that way it works on my end.)

**Comment by alexhabgood** [comment]
Thanks for the update @privatezero. Sounds promising.

**Comment by alexhabgood** [comment]
Thanks for sorting out those issues @dericed.

I did a bit of further investigation on Tuesday and managed to get to the bottom of the remaining issue. It seems to have been due to the fact that the workstation was set to be using nouveau display driver. When I switched to using nvidia drivers, compatible with the gtx graphics card, this fixed the issue. 

I'm going to close this issue now. Thanks again for all your help, much appreciated!

**Comment by dericed** [comment]
Hi @alexhabgood, if helpful for others we could include the solution you discovered in a sort of FAQ format.

**Comment by alexhabgood** [comment]
I'm not entirely sure what the issue was between vrecord and the nouveau display drivers. Unfortunately, I don't really have time to look into this deeper at present.

Since @privatezero seemed to be able to repeat the issue, he may be able to shed further light on what was going wrong.

I should also mention that in the process of trying to resolve this issue, I rolled the OS version back to ubuntu 18.04, so that I was following the install instructions to the letter after a fresh install. I havn't updated the OS back up to 20.04 LTS yet, to see if any other issues crop up.

Nonetheless, I think it would be a good idea to have some kind of mention of display drivers in the ubuntu install instructions. Happy to help further if I can.

**Comment by privatezero** [comment]
@retokromer, what version of Linux are you on? I've been testing with 
> on_linux do
>   depends_on "libxv"
> end
added to the formula locally and it hasn't made a difference on my end with Ubuntu 20.04. Would love to figure this out for 20.04 as I want to make sure we have problems ironed out for the current LTS release.

**Comment by retokromer** [comment]
Hello @privatezero, on both Debian 10.8 (at home) and Ubuntu 20.04.2 LTS (at work). I have to add that we don’t install with `apt-get`, therefore it’s possible that you have already installed all what’s needed with your workflow (I didn’t verify this).

**Comment by privatezero** [comment]
Hi @retokromer good to know it works in some form on 20.04 at least! It just seems to be another tangle with linuxbrew builds and the current workflow :-/ (compiling externally from linuxbrew of course works fine)
