### ISSUE TITLE
intel/Big Sur gtkdialog installation probs

### ISSUE THREAD

**Issue by bturkus** [amiaopensource/vrecord#665]
hi,
I just upgraded to Big Sur 11.2.2 on an intel iMacPro, and vrecord install seems to be getting hung up with gtkdialog:

```
==> Reinstalling amiaopensource/amiaos/vrecord 
==> Installing dependencies for amiaopensource/amiaos/vrecord: amiaopensource/amiaos/gtkdialog, cowsay, bash, gd, libcerf, lua, qt@5, gnuplot, xmlstarlet, mediaarea/mediaarea/dvrescue, jansson, mediaconch, boost, fmt, libebml, libmagic, libmatroska, pcre2, pugixml, mkvtoolnix, libb2, lz4, zstd, libarchive, luajit-openresty, mujs, uchardet, vapoursynth, youtube-dl, mpv, qwt and qcli
==> Installing amiaopensource/amiaos/vrecord dependency: amiaopensource/amiaos/gtkdialog
==> Patching
==> ./configure
Last 15 lines from /Users/pamivideo2/Library/Logs/Homebrew/gtkdialog/01.configure:
checking whether yytext is a pointer... yes
checking for bison... bison -y
checking for pkg-config... /usr/local/Homebrew/Library/Homebrew/shims/mac/super/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for GTK... no
configure: error: Package requirements (gtk+-2.0 >= 2.0.0) were not met:

Package 'xcb-shm', required by 'cairo', not found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables GTK_CFLAGS
and GTK_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/amiaopensource/homebrew-amiaos/issues
```
thanks for any help! apple sucks!

**Comment by EG-tech** [comment]
Hey y'all, I am seeing the same error trying a fresh install of vrecord into Mojave 10.14.6. I've tried with @dericed's adjusted gtkdialog formula as linked above as well, but no dice, still the same error.

**Comment by dericed** [comment]
You also get `Package 'xcb-shm', required by 'cairo', not found`? Could you describe your method to test the [PR](https://github.com/amiaopensource/homebrew-amiaos/pull/275)?

**Comment by EG-tech** [comment]
Yes - I tried:
1. git cloned `homebrew-amiaos`, checked out `gtkdialog-dependencies` and tried to brew install the adjusted `gtkdialog.rb`
2. ran `brew edit gtkdialog` and just manually made the same edits from your commit, then brew install gtkdialog

Both methods still hit `Package 'xcb-shm', required by 'cairo', not found` - let me know if I'm not testing correctly!!

**Comment by dericed** [comment]
I just updated the PR, can you test:
```
git clone --branch gtkdialog-dependencies https://github.com/amiaopensource/homebrew-amiaos.git
brew install --force homebrew-amiaos/gtkdialog.rb
```

**Comment by EG-tech** [comment]
That worked, successfully installed `gtkdialog`!

**Comment by dericed** [comment]
can you note that on the pr plz

**Comment by dericed** [comment]
closing this, cc @bturkus

**Comment by bturkus** [comment]
thank you! closing
