### ISSUE TITLE
"File did not pass vrecord policy check for FFV1 video" ?

### ISSUE THREAD

**Issue by XFRCollective** [amiaopensource/vrecord#666]
Came across a new issue, happened suddenly. When I hit record, vrecord behaves as if I have stopped a recording and the error below occurs. I recently upgrade/updated so the new fixes to gtkdialog should be in place. My settings haven't changed since before I started receiving this error (ffv1, .mkv, 10bit, etc)

I ran a check on the mediaconchreport and only error seemed related to the duration? Any thoughts on a step I could take to troubleshoot? 

```

Vrecord is analyzing your video file. Please be patient.
qctools XML /Users/xfrcollective/Desktop/mwf_1004_ffv1.mkv.qctools.xml.gz is empty or does not exist!
QCTools analysis is complete.
Checking file conformance against FFV1 video policy...
 2021-03-07T22:10:30 - File did not pass vrecord policy check for FFV1 video and may not conform to digital preservation standards. Try another file?
 2021-03-07T22:10:31 - See /Users/xfrcollective/Desktop/mwf_1004_ffv1_mediaconchreport.xml for a full MediaConch policy report.

```

EBML-ELEMENT-VALID-RANGE Tests run: 20 | Results: ❌ Fail count: 1
Results: pass ✅ 
Name: SegmentUID
Offset: 263
ID: 0x73A4
Value context: /Segment[1]/Info[1]/SegmentUID[1]
Value: [19 bytes]
Results: fail ❌ (Reason: Duration is not a valid Element range of >0x0p+0 octets but is instead storing 0.000.)
Name: Duration
Offset: 293
ID: 0x4489
Value context: /Segment[1]/Info[1]/Duration[1]
Value: 0.000

**Comment by XFRCollective** [comment]
Issue #666 #ftw😈

**Comment by dericed** [comment]
Congrats 😈😈😈
The policy expects greater than zero duration so am guessing it fails cuz you have an empty file. Could you try qctools after, rather than concurrent, or send the ffmpeg log.

**Comment by XFRCollective** [comment]
Thanks! I see why the conformance would fail. Here are the vrecord and capture options log. 

[test8_ffv1_vrecord_input.log](https://github.com/amiaopensource/vrecord/files/6101626/test8_ffv1_vrecord_input.log)
[test8_ffv1_capture_options.log](https://github.com/amiaopensource/vrecord/files/6101627/test8_ffv1_capture_options.log)

**Comment by dericed** [comment]
Checking into this, nearly a year later and can't recreate. Still a thing?

**Comment by XFRCollective** [comment]
Not still a thing! Closing
