### ISSUE TITLE
DV device not showing - Ubuntu 18.04

### ISSUE THREAD

**Issue by alexhabgood** [amiaopensource/vrecord#667]
Hiya,

I'm wanting to capture DV on Ubuntu 18.04. However, under the DVRescue tab my DV device isn't showing. I've seen some other issues that seem to relate to this: #631 and #559 

Is this a current limitation, using vrecord on Ubuntu? Or is there something wrong with my install?

I'm able to use DVgrab and kino to capture DV, so there doesn't seem to be any problem with my hardware or drivers. I've attached my config file.
[vrecord_conf.txt](https://github.com/amiaopensource/vrecord/files/6335904/vrecord_conf.txt)

Thanks in advance.

**Comment by alexhabgood** [comment]
Thanks for confirming. 

I had a go at capture but get the following error:

> Unknown input format 'iec61883'
> libEGL warning: DRI2: failed to autheticate
> "pipe:: Invalid data found when processing inputKB sq=  0B f=0/0
> 2021-04-20T10:13:35 - vrecord exited a form in an unexpected way (P1_ERR=1)"

For context, the DV device is connected via a firewire PCI card. It's also the only device connected by firewire to the computer.

**Comment by dericed** [comment]
I'm guessing that your ffmpeg is not configured with --enable-libiec61883. Are you able to recompile with that option?

**Comment by alexhabgood** [comment]
Thanks @dericed. Using "which ffmpeg" points to an ffmpeg binary that was installed by linuxbrew. I'll compile my own with libiec61883 enabled. Hopefully that'll sort it out.

**Comment by alexhabgood** [comment]
Bit of initial confusion on my end, as I forgot that vrecord uses ffmpegdecklink (ffmpeg-dl), not the standard ffmpeg I have on my computer. Nevertheless, the issue now seems to be fixed. I made sure I had the following dependencies installed: 
> sudo apt install libiec61883-dev
> sudo apt install libraw1394-dev
> sudo apt install libavc1394-dev
> sudo apt install libavc1394-tools

Then reinstalled ffmpegdecklink, with iec61883 enabled:
> brew reinstall ffmpegdecklink --with-iec61883

So, I'll close this issue. Thanks @privatezero and @dericed for your help.

**Comment by dericed** [comment]
It used ffmpegdecklink for two reasons. One was to ensure a recent patch and one was to ensure configuration with libiec61883 for linux. That patch is now in ffmpeg 4.4, but I don't think libiec61883 is standard in linuxbrew, thus we are still with ffmpegdecklink that any ffmpeg 4.4 or later with libiec61883 would be okay.
