### ISSUE TITLE
vrecord exited a form in an unexpected way

### ISSUE THREAD

**Issue by NMAAHC** [amiaopensource/vrecord#669]
I'm using macOS Catalina and I can't get vrecord to open. I installed desktop video and I'm getting this error when running vrecord -e 

MingC@NMAAHC-L37332 ~ % vrecord -e
Initiatizing the configuration file at /Users/MingC/.vrecord.conf.
 2021-05-24T12:37:54 - vrecord exited a form in an unexpected way (EXIT=), please report this error to https://github.com/amiaopensource/vrecord/issues
MingC@NMAAHC-L37332 ~ %

**Comment by libbyhopfauf** [comment]
I would recommend uninstalling and reinstall ffmpegdecklink by running
brew uninstall ffmpegdecklink
brew reinstall ffmpegdecklink

And then restart your computer. That it how I have resolved this in the past.

**Comment by dericed** [comment]
@NMAAHC, will close, please reopen if this is still an issue in git-main or the soon release.
