### ISSUE TITLE
Documentation linux_installation.md: add more install dependencies

### ISSUE THREAD

**Issue by takahe** [amiaopensource/vrecord#671]
on linux-mint 20.1 I needed to
`apt install libc6-dev texinfo`
to compile DeckLinkAPIDispatch.cpp (libc6-dev, stdio.h "no such file" error) and gtkdialog (missing makeinfo).

**Comment by privatezero** [comment]
Thanks for reporting this @takahe! We'll add it to the tips for installing in the linux documentation.

**Comment by dericed** [comment]
@privatezero, closed now, ya?

**Comment by privatezero** [comment]
@dericed I reckon so!
