### ISSUE TITLE
m1 mac installation issues

### ISSUE THREAD

**Issue by bturkus** [amiaopensource/vrecord#673]
I finally got my hands on a m1 mac mini, and I'm having some vrecord installation issues. On Big Sur with the latest Desktop Video installed, and using an Ultrastudio HD Mini.

I've tried uninstalling and reinstalling ffmpegdecklink, and even upgraded to HEAD (as of this morning).

Here's the relevant error message:

```
==> Installing amiaopensource/amiaos/vrecord dependency: amiaopensource/ami
==> make
Last 15 lines from /Users/benjaminturkus/Library/Logs/Homebrew/deckcontrol/01.make:
2021-06-21 10:25:23 -0400

make

gcc -g -I/usr/local/include -c deckcontrol.cpp
make: *** No rule to make target /usr/local/include/DeckLinkAPIDispatch.cpp', needed by DeckLinkAPIDispatch.o'.  Stop.
make: *** Waiting for unfinished jobs....
```

**Comment by BleakleyMcD** [comment]
Same here.

**Comment by iamdamosuzuki** [comment]
This info was available on the BM forums:

> What's new in Desktop Video 12.0
> For Mac OS
> Add support for the following products on Mac OS Big Sur:
> M1 and Intel Macs:
> DeckLink Duo 2
> DeckLink Quad 2
> DeckLink Quad HDMI Recorder
> DeckLink 8K Pro
> DeckLink 4K Extreme 12G
> DeckLink Micro Recorder
> DeckLink SDI Micro
> DeckLink Mini Monitor 4K
> DeckLink Mini Recorder
> DeckLink Mini Recorder 4K
> DeckLink SDI 4K
> DeckLink Studio 4K
> UltraStudio Recorder 3G
> UltraStudio Monitor 3G
> UltraStudio HD Mini
> UltraStudio 4K Mini
> UltraStudio 4K Extreme 3
> Intensity Pro 4K
> DeckLink 4K Pro
> DeckLink 4K Extreme
> UltraStudio 4K
> UltraStudio 4K Extreme
> 
> 
> Intel Macs only:
> DeckLink Mini Monitor
> DeckLink HD Extreme 3
> DeckLink HD Extreme 3D
> DeckLink SDI
> DeckLink Duo
> DeckLink Quad
> DeckLink Studio
> UltraStudio Express
> UltraStudio Mini Monitor
> UltraStudio Mini Recorder
> Intensity Pro
> Intensity Shuttle Thunderbolt

**Comment by iamdamosuzuki** [comment]
At BAVC we use the DeckLink 4K Extreme, which is on the supported list. We're due to get an M1 mini in the coming weeks, I'll update y'all on whether that works or not.

**Comment by dericed** [comment]
This was fixed in https://github.com/bavc/deckcontrol/pull/2. @bturkus & @BleakleyMcD, if still an issue, please reopen.
