### ISSUE TITLE
on screen dropped frame warning

### ISSUE THREAD

**Issue by bturkus** [amiaopensource/vrecord#68]
think this has been discussed already, but I'd love to see a dropped frame warning (with a running tally?) appear somewhere in the capture window.

**Comment by dericed** [comment]
Does this data get collected in the bmdcapture log? Any existing logs with this data. At one point @CSchloss385 was trying to force situations with dropped frames but haven't no luck reliably getting dropped frames. @bturkus do you have any logs or evidence of such a scenario?

**Comment by kieranjol** [comment]
Is this commit related? https://github.com/amiaopensource/vrecord/commit/2e2ee61cd80731a50bea5d3195c4d463d8709914

**Comment by dericed** [comment]
Ah I forgot about that, but I guess there's two issues:
- what is above is about if ffmpeg dropped frames while encoding. The test checks how many frames ffmpeg decoded (uncompressed from nut pipe from bmdcapture) versus how many it encoded. Possibly buffer could be exceeded and ffmpeg may not be able to keep up with encoding as fast as needed.

- the other issue would be dropped frames happening within bmdcapture so they never get to ffmpeg, which is what I was considering in the above response.

**Comment by dericed** [comment]
I think this could be done with the drawtext filter calling the bmdcapture log via the `textfile` option and then the `reload=1` option set so that the text is reloaded as the capture progresses.

**Comment by dericed** [comment]
Here's an example of writing a logfile on screen with reloading.

`ffplay -f lavfi -i color=s=720x480 -vf "drawtext=fontcolor=white:fontsize=22:fontfile=/Library/Fonts/Andale Mono.ttf:textfile=test.txt:reload=1"`

**Comment by dericed** [comment]
Add a `y` based on text height allows the text to scroll up as it comes in

`ffplay -f lavfi -i color=s=720x180 -vf "drawtext=fontcolor=white:fontsize=22:fontfile=/Library/Fonts/Andale Mono.ttf:textfile=test.txt:reload=1:y=180-th"`

Note the 180 of the window to draw the text matches the 180 used to calculate where to draw the y coordinate of the text.

**Comment by dericed** [comment]
@savcampbell addressed this in https://github.com/amiaopensource/vrecord/pull/108. @bturkus please test.

**Comment by retokromer** [comment]
If no opposition, I will close this in the next days.
