### ISSUE TITLE
no video card seen in latest version 

### ISSUE THREAD

**Issue by bturkus** [amiaopensource/vrecord#685]
I'm trying out the latest release of vrecord on a 2019 mac mini (no m1) with big sur, and for some reason I'm not seeing any video cards. Media Express is working fine, and I've tried uninstalling and reinstalling both vrecord and ffmpegdecklink.

also on desktop video 12.1

thanks for any help!

**Comment by iamdamosuzuki** [comment]
I was able to get my M1 Mac Mini to detect the BM card by enabling System Extensions or Kernel Extensions. Here's a link on how to do it, though you may need IT support do so. 

https://iboysoft.com/howto/enable-system-extension-m1-mac.html

**Comment by privatezero** [comment]
I'll hopefully have access to a mac tomorrow - I'll see if I can reproduce!

**Comment by iamdamosuzuki** [comment]
Just to clarify, my note about needing "IT support" to do it is in regards to someone working at an institution without admin access. Basically as long as you have admin access you'll be able to enable system extensions.

**Comment by dericed** [comment]
Should be fixed in https://github.com/amiaopensource/vrecord/pull/687. Please `brew upgrade && echo B)"
