### ISSUE TITLE
redundant install docs?

### ISSUE THREAD

**Issue by privatezero** [amiaopensource/vrecord#692]
I see that the main [install instructions](https://github.com/amiaopensource/vrecord/blob/main/Resources/Documentation/installation_and_setup.md#installing-vrecord) have some information about linux setup, but no actual link to the separate [linux specific](https://github.com/amiaopensource/vrecord/blob/main/Resources/Documentation/linux_installation.md) page. Would there be any opposition to replacing the information in the main docs with a cross-link? Seems this would help avoid potential confusion as well as simplify maintenance.

**Comment by retokromer** [comment]
Not al all, it’s a good idea!

**Comment by privatezero** [comment]
Should be resolved in https://github.com/amiaopensource/vrecord/pull/695
