### ISSUE TITLE
problem with brew install gtkdialog

### ISSUE THREAD

**Issue by jbbenoit73** [amiaopensource/vrecord#696]
Hello, i can't install gtkdialog.
Have a look :

++++++++++++++++++++++++++++

jbbenoit@jbbenoit-MacBookPro:~$ brew install gtkdialog
==> Downloading https://github.com/puppylinux-woof-CE/gtkdialog/archive/0.8.4d.t
Already downloaded: /home/jbbenoit/.cache/Homebrew/downloads/9ad1b9aa93836cdde8a71070ff94b52c7c4d75777648ab8dc3bab09b9d35dd8e--gtkdialog-0.8.4d.tar.gz
==> Installing gtkdialog from amiaopensource/amiaos
==> ./autogen.sh
==> make
Last 15 lines from /home/jbbenoit/.cache/Homebrew/Logs/gtkdialog/02.make:
then \
  rc=0; \
  CDPATH="${ZSH_VERSION+.}:" && cd .; \
else \
  rc=$?; \
  CDPATH="${ZSH_VERSION+.}:" && cd . && \
  $restore $backupdir/* `echo "./gtkdialog.info" | sed 's|[^/]*$||'`; \
fi; \
rm -rf $backupdir; exit $rc
/bin/bash: line 9: makeinfo: command not found
make[2]: *** [Makefile:338: gtkdialog.info] Error 127
make[2]: Leaving directory '/tmp/gtkdialog-20211126-96504-zjavaj/gtkdialog-0.8.4d/doc'
make[1]: *** [Makefile:424: all-recursive] Error 1
make[1]: Leaving directory '/tmp/gtkdialog-20211126-96504-zjavaj/gtkdialog-0.8.4d'
make: *** [Makefile:363: all] Error 2

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/amiaopensource/homebrew-amiaos/issues

++++++++++++++++++++++++++++

Could you help me please ?
My system is Ubuntu 20.04
I have to install vrecord in a Dell workstation in an university.
Thank you.
JB

**Comment by jbbenoit73** [comment]
Hi @privatezero. Thank you. I try it, look...

jbbenoit@jbbenoit-MacBookPro:~$ makeinfo
makeinfo: missing file argument.
Try `makeinfo --help' for more information.

**Comment by jbbenoit73** [comment]
jbbenoit@jbbenoit-MacBookPro:~$ apt-file search bin/makeinfo
texinfo: /usr/bin/makeinfo                
jbbenoit@jbbenoit-MacBookPro:~$ apt-file search makeinfo
emacs-common: /usr/share/emacs/26.3/lisp/textmodes/makeinfo.elc
emacs-el: /usr/share/emacs/26.3/lisp/textmodes/makeinfo.el.gz
manpages-ja: /usr/share/man/ja/man1/makeinfo.1.gz
manpages-zh: /usr/share/man/zh_CN/man1/makeinfo.1.gz
manpages-zh: /usr/share/man/zh_TW/man1/makeinfo.1.gz
octave-common: /usr/share/octave/5.2.0/m/help/__makeinfo__.m
octave-doc: /usr/share/doc/octave/octave.html/XREFmakeinfo_005fprogram.html
octave-plplot: /usr/share/plplot_octave/support/__makeinfo__.m
sendmail-cf: /usr/share/sendmail/cf/sh/makeinfo.sh
texi2html: /usr/share/texi2html/makeinfo.init
texinfo: /usr/bin/makeinfo
texinfo: /usr/share/doc/texinfo/html/Invoking-makeinfo.html
texinfo: /usr/share/doc/texinfo/html/makeinfo-Advantages.html
texinfo: /usr/share/doc/texinfo/html/makeinfo-Options.html
texinfo: /usr/share/doc/texinfo/html/makeinfo-Pointer-Creation.html
texinfo: /usr/share/doc/texinfo/html/makeinfo-Preferred.html
texinfo: /usr/share/doc/texinfo/html/makeinfo-advantages.html
texinfo: /usr/share/doc/texinfo/html/makeinfo-in-Emacs.html
texinfo: /usr/share/doc/texinfo/html/makeinfo-top-command.html
texinfo: /usr/share/doc/texinfo/html/makeinfo-top.html
texinfo: /usr/share/man/man1/makeinfo.1.gz
vim-syntastic: /usr/share/vim/addons/syntax_checkers/texinfo/makeinfo.vim
xemacs21-basesupport: /usr/share/xemacs21/xemacs-packages/lisp/texinfo/makeinfo.elc
xemacs21-basesupport-el: /usr/share/xemacs21/xemacs-packages/lisp/texinfo/makeinfo.el.gz

**Comment by jbbenoit73** [comment]
Hello
I re-installed texinfo and **brew install gtkdialog** succeeds, the next steps are ok and Vrecord works.
@privatezero, thanks for your help.

**Comment by privatezero** [comment]
Thanks for the update - glad it worked!
