### ISSUE TITLE
Audio Only Capture Conversion Failed

### ISSUE THREAD

**Issue by beccabender** [amiaopensource/vrecord#699]
Hi All,

This is VERY likely user error, but I'm trying to do audio-only capture for the first time, using a Blackmagic Ultrastudio Express, and I can't get it to work. (Video capture is working fine).

If I set my audio device to the Blackmagic, it doesn't seem to read anything in the audio levels:

<img width="460" alt="Screen Shot 2021-12-29 at 4 41 16 PM" src="https://user-images.githubusercontent.com/27779787/147705513-c5b0fa9b-80d2-42bf-98fd-b8724eedf787.png">

If I set it to Built-In Microphone, I get levels, but still no captured audio. 

<img width="478" alt="Screen Shot 2021-12-29 at 4 41 26 PM" src="https://user-images.githubusercontent.com/27779787/147705595-fd9d54ea-ce23-43be-abac-c805895f955e.png">

Both device selections give me the following error at the end:

av_interleaved_write_frame(): Broken pipe
Error writing trailer of pipe:: Broken pipe
size=    2615kB time=00:00:18.34 bitrate=1167.8kbits/s speed=   1x    
video:0kB audio:3486kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
Conversion failed!

Maybe I'm missing something in the Audio MIDI Setup? 

I saw a closed issue about the audio capture not working with Blackmagic back in 2020, but it seems like it's been resolved since then.

Thank you for the help!!
Becca

**Comment by privatezero** [comment]
Hi @beccabender thanks for reporting this! I won't have access to a mac/blackmagic until next week, but I'll take a look then to see if I can reproduce the issue.

**Comment by beccabender** [comment]
Thank you @privatezero!

**Comment by privatezero** [comment]
Hi @beccabender - I had a chance to test this out on my end today with a mac and an Ultrastudio Express and I haven't yet been able to reproduce the problem. There should be some log files that are produced when vrecord runs that contain things like the command it is trying to use. Could you share the contents of those here? They might help in figuring out where things are getting tangled.

**Comment by beccabender** [comment]
Thank you so much @privatezero for testing it so quickly. Due to some current computer limitations around here, I don't think I'll be able to try again and send you the log files until early next week. Thank you!

**Comment by beccabender** [comment]
Actually, I just realized that I still had those logs on my home computer. They're attached here. Thanks!
[Test_BM_vrecord_input.log](https://github.com/amiaopensource/vrecord/files/7829149/Test_BM_vrecord_input.log)
[Test_BM_capture_options.log](https://github.com/amiaopensource/vrecord/files/7829150/Test_BM_capture_options.log)
.

**Comment by privatezero** [comment]
Hi @beccabender - I haven't been able to reproduce this yet, part of me wonders if this could be related to an update on the Blackmagic side. Is this still broken for you?

**Comment by beccabender** [comment]
Hi @privatezero. I'm so sorry I disappeared. There has been a LOT of tech changing around here lately including an OS upgrade as well as audio and computer hardware, so things have been on hold for a while. I will hopefully be able to get back to audio work soon, but please feel free to close this issue. If I run into more problems in the future, it will likely be with a somewhat different setup, so I will start fresh if need be. I'm chalking this one up to the gremlins!

**Comment by privatezero** [comment]
Thanks for letting us know! Give a holler if the gremlins pop back up in the future!
