### ISSUE TITLE
Close FFplay window after time limit is up

### ISSUE THREAD

**Issue by jfarbowitz** [amiaopensource/vrecord#7]

**Comment by jfarbowitz** [comment]
Need to see if I can replicate this...

**Comment by dericed** [comment]
ffplay is using -autoexit so it should close the window when nothing is coming in; however it's possible that although ffmpeg stops at the time requested that bmdcapture doesn't stop and thus keeps ffplay open

**Comment by jfarbowitz** [comment]
I haven't seen this behavior at all. I'm closing until someone finds it again.
