### ISSUE TITLE
Audio + Video with PAL input

### ISSUE THREAD

**Issue by privatezero** [amiaopensource/vrecord#700]
Audio + Video mode seems to possibly have issues when using a PAL input rather than NTSC. Needs to be tested with a couple more tapes and fixed if needed!

**Comment by bturkus** [comment]
I can confirm this (and also apologize for not reporting it months ago!)

**Comment by privatezero** [comment]
Thanks for the confirmation! That filter is stretched pretty thin, so not surprised that something went a little wonky - I'll look into seeing what will make it happy.

**Comment by privatezero** [comment]
Resolved in https://github.com/amiaopensource/vrecord/pull/702#event-5867589278
