### ISSUE TITLE
Update date

### ISSUE THREAD

**Issue by retokromer** [amiaopensource/vrecord#707]
The documentation seems to have been updated since two years:

>[This documentation is up to date as of vrecord version 2020-02-10.](https://github.com/amiaopensource/vrecord/blob/1c374544cd5ed43d199c60d1ec17c6569c67c380/README.md?plain=1#L3)

Is it up-to-date with the current version 2022-01-10?

**Comment by privatezero** [comment]
I would say the documentation is probably mostly out of date (and more up to date than 2020-02), but can't say for certain that it is 100% up to date. I've been trying to review chunks of it and make changes as needed, but haven't been able to look at everything yet.

**Comment by dericed** [comment]
Will close as I think @privatezero's comment answers the initial question.
