### ISSUE TITLE
vrecord -a   ---->  .... No such filter: 'streams'

### ISSUE THREAD

**Issue by jbbenoit73** [amiaopensource/vrecord#715]
Hello,
I've a new issue with another station. 'vrecord -a' fail, please have a look :

numersiation@station-av-lin01:~$ vrecord -a
Input #0, matroska,webm, from 'pipe:':
  Metadata:
    creation_time   : 2022-02-11T10:45:17.788391Z
    ENCODER         : Lavf58.76.100
  Duration: N/A, start: 0.000000, bitrate: 9216 kb/s
  Stream #0:0: Audio: pcm_s24le, 48000 Hz, 8 channels, s32 (24 bit), 9216 kb/s (default)
    Metadata:
      ENCODER         : Lavc58.134.100 pcm_s24le
  Stream #0:1: Video: rawvideo (UYVY / 0x59565955), uyvy422(tv, bt470bg/bt470bg/bt709, top first), 720x576, 25 fps, 25 tbr, 1k tbn, 1k tbc (default)
No such filter: 'streams'
   0.01 A-V:    nan fd=   0 aq=    0KB vq= 4860KB sq=    0B f=0/0   
numersiation@station-av-lin01:~$ 

Dell tower precision, ubuntu 20.04, DeclLink Studio 4K

Regards,

jb

**Comment by privatezero** [comment]
Hi @jbbenoit73 this should have been resolved in the fix that we did to correct the button behavior in https://github.com/amiaopensource/vrecord/commit/3d97afe436f8952469a7527fa76c56a4272cc466 - once we make a new release it should be better.

**Comment by jbbenoit73** [comment]
Hi.
Thank you.
