### ISSUE TITLE
Update documentation: gtkdialog install issues persist with Ubuntu 22.04

### ISSUE THREAD

**Issue by ncam610** [amiaopensource/vrecord#730]
gtkdialog issue noted for Ubuntu 18.04 is persistent when installing with 22.04. The workaround noted here seems to have worked: https://github.com/amiaopensource/homebrew-amiaos/blob/master/TROUBLESHOOTING.md#vrecord.

**Comment by privatezero** [comment]
Thanks for reporting! I'll update the README to just say `Ubuntu` as this seems to be something that is version independent these days.
