### ISSUE TITLE
No input signal detected / Frames dropped

### ISSUE THREAD

**Issue by pjotrek-b** [amiaopensource/vrecord#744]
I'm basically having the same issue as mentioned in #736 :cry: 

My ffmpeg capture output literally looks like a copy/paste of @ppsgroup's problem:

> [decklink @ 0x5602d8a54a80] Frame received (#18452) - No input signal detected - Frames dropped 1
> [decklink @ 0x5602d8a54a80] Frame received (#18454) - Input returned - Frames dropped 2

I've checked with the Blackmagic Desktop Video GUI, and it also drops frames.
I've tried using a spinning disk as well as an SSD to rule out disk-speed issues.

I must say though, that I'm using a Blackmagic Mini Converter ADC (Composite to SDI) - and the analog source signal seems to drop out a lot, so maybe the ADC or SDI-input is losing it's sync?

So it's not really a vrecord issue, but if anyone here's interested in debugging this with me, I'd be grateful :wink: :smile:

## System details:
Ubuntu 20.04 (64bit)
AMD Ryzen 8 core
Decklink SDI 4k card

**Comment by privatezero** [comment]
Hi @pjotrek-b, do you have any sort of time base corrector in your signal chain?

Personally I've never had any luck with ingesting via a Blackmagic device without a TBC further up the chain, so that might be something to look at if you aren't using one.

**Comment by pjotrek-b** [comment]
True. I've made the same experience(s) with Blackmagic ADCs without TBC.... :wink:

SOLVED:
The issue was in fact a series of tapes that were "problematic" (*).
I've then switched to other tapes - and now the (video) signal is fine. No more dropped frames.
vrecord runs perfectly fine.

(*) The TBC I've used had severe issues even sync'ing on the signal. It actually made it worse than without.
The problematic tapes came from the same source. I guess the VCR they were recorded with was odd (or misaligned).

Sorry for the noise!
Thanks for your time.

**Comment by harrypm** [comment]
@pjotrek-b Just noting Blackmagic hardware uses the [ADV7842](https://www.analog.com/media/en/technical-documentation/data-sheets/adv7842.pdf) on current hardware for analog to SDI units (almost all solutions do), sadly the 3D comb and TBC fuctions are not enabled they are ment for use with external TBC or live signals only esseintally.

However Magewell/Brighteyes units do enable it and AJA have the 3D comb enabled last I checked, but today you might want to look at [cvbs-decode](https://github.com/oyvindln/vhs-decode/wiki/CVBS-Composite-Decode) for future composite capture or [vhs-decode](https://github.com/oyvindln/vhs-decode#readme) for direct tape capture as its software TBC and signal correction abbilitys beats the ADV chips and it works for multible tape formats and tv systems.

**Comment by privatezero** [comment]
@pjotrek-b thanks for the follow-up! Glad to hear all is well (sorry about the bad batch of tapes though!)
