### ISSUE TITLE
hardware issue

### ISSUE THREAD

**Issue by a7med12h** [amiaopensource/vrecord#748]
I tried to install vrecord to my pc ( linux) but I did not get familiar with it. I want to switch to MacPro when I bought it . there is no way to install blackmagic card on it . how i can connect cards and interface to MacPro ? so I can do digitizing

**Comment by a7med12h** [comment]
and also what is the minimum HW requirements for macpro . RAM ? GPU ?

**Comment by retokromer** [comment]
>I tried to install vrecord to my pc ( linux) but I did not get familiar with it. I want to switch to MacPro when I bought it . there is no way to install blackmagic card on it . how i can connect cards and interface to MacPro ? so I can do digitizing

Which Blackmagic card are you using? What exactly did you try and where did you get stuck?

>and also what is the minimum HW requirements for macpro . RAM ? GPU ?

MacPro are very powerful machines! Any MacPro will fit.

We actually are working just with Mac mini  and Intel NUC running Terminal under Windows. In past we used also Intel NUC under Ubuntu.

**Comment by a7med12h** [comment]
Thank for ur reply . I have old tapes and I want to digitize them with vrecord. 
So I bought blackmagic card decklink intensity 4 k pro . And also I bought other equipment but all of them I have no problem cuz no direct connection between them and mac z Except the decklink wheich need Pcie slot and Macpro can not accept .

**Comment by privatezero** [comment]
> I tried to install vrecord to my pc ( linux) but I did not get familiar with it.
Were there any specific issues you were having with the installation on your pc?

**Comment by a7med12h** [comment]
actually yes, I have downloaded every thing as it said . but  steps were not clear about linux. it just clear for the Mac . I tried many times to download every thing again but same thing. I could not download vrecord. so thats why I decide to change to Mac cuz all steps are for Mac. Linux very powerfull but I am very confused to deal with it . plz letme know if I can download and run vrecord ? I will give another chance if u tell me Linux is better than Mac

**Comment by retokromer** [comment]
>I could not download vrecord.

I am afraid, I cannot understand you. What do you mean exactly? Downloading `vrecord` from GitHub and installing it manually or (recommended) installing it via the [Homebrew formula](https://github.com/amiaopensource/homebrew-amiaos) should not be difficult.

**Comment by retokromer** [comment]
Which step from our [guideline](https://github.com/amiaopensource/vrecord/blob/main/Resources/Documentation/linux_installation.md) did not work?

**Comment by a7med12h** [comment]
first I really want to thank u for ur reply . I will do it again in my Linux and let u know at which step I got stuck. just give me less than hour

**Comment by a7med12h** [comment]
I think I did a mistake when I tried to do installing . Linux and Mac both r working perfect now . thank u so much

**Comment by privatezero** [comment]
Glad it seems to have worked out!
