### ISSUE TITLE
interlaced & progressive 

### ISSUE THREAD

**Issue by a7med12h** [amiaopensource/vrecord#756]
I noticed that when ever capture video in vrecord, it would capture it with interlaced. I want to ask is there any way to change it to progressive ? 
other question . is there any way to have output as MKV ffv3 lossless and also mp4 lossy file ?

**Comment by retokromer** [comment]
>is there any way to have output as MKV ffv3 lossless and also mp4 lossy file ?

Not in one go, as current computers might be to slow. Yet you can capture in Matroska/FFV1 in one step and then encode in MP4/H.264 in another step. See `ffmprovisr`:

- https://amiaopensource.github.io/ffmprovisr/#transcode_h264
- https://amiaopensource.github.io/ffmprovisr/#transcode_gpu
