### ISSUE TITLE
Input Swapping on Each Boot

### ISSUE THREAD

**Issue by gbagit** [amiaopensource/vrecord#759]
This is a very small bug. Upon starting a vrecord session, the list of video devices are randomized slightly. It looks like ffmpeg gathers the inputs from this command:

ffmpeg -f avfoundation -list_devices true -i ""

Which gives this output:

ffmpeg version 6.0 Copyright (c) 2000-2023 the FFmpeg developers
  built with Apple clang version 14.0.3 (clang-1403.0.22.14.1)
  configuration: --prefix=/opt/homebrew/Cellar/ffmpeg/6.0 --enable-shared --enable-pthreads --enable-version3 --cc=clang --host-cflags= --host-ldflags= --enable-ffplay --enable-gnutls --enable-gpl --enable-libaom --enable-libaribb24 --enable-libbluray --enable-libdav1d --enable-libmp3lame --enable-libopus --enable-librav1e --enable-librist --enable-librubberband --enable-libsnappy --enable-libsrt --enable-libsvtav1 --enable-libtesseract --enable-libtheora --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libxvid --enable-lzma --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libspeex --enable-libsoxr --enable-libzmq --enable-libzimg --disable-libjack --disable-indev=jack --enable-videotoolbox --enable-audiotoolbox --enable-neon
  libavutil      58.  2.100 / 58.  2.100
  libavcodec     60.  3.100 / 60.  3.100
  libavformat    60.  3.100 / 60.  3.100
  libavdevice    60.  1.100 / 60.  1.100
  libavfilter     9.  3.100 /  9.  3.100
  libswscale      7.  1.100 /  7.  1.100
  libswresample   4. 10.100 /  4. 10.100
  libpostproc    57.  1.100 / 57.  1.100
[AVFoundation indev @ 0x13a7047a0] AVFoundation video devices:
[AVFoundation indev @ 0x13a7047a0] [0] DV-VCR
[AVFoundation indev @ 0x13a7047a0] [1] AJ-YAD120AG
[AVFoundation indev @ 0x13a7047a0] [2] AJ-HD1400
[AVFoundation indev @ 0x13a7047a0] [3] AJ-YAD120AG
[AVFoundation indev @ 0x13a7047a0] [4] Capture screen 0
[AVFoundation indev @ 0x13a7047a0] AVFoundation audio devices:

This list is then displayed here:

![Screenshot 2023-08-28 at 2 02 41 PM](https://github.com/amiaopensource/vrecord/assets/142834591/e0d803fe-26c9-4d9a-a851-de196f817b8b)

With the two AJ-YAD120AG, either of the two inputs could be listed as 1 or 3. For every new tape that is run, the order shuffles again. So, the two inputs swap around with each new tape throughout the day.

I am running this with ffmpeg6.0 on a 13.4 mac mini.

**Comment by retokromer** [comment]
>I am running this with ffmpeg6.0 on a 13.4 mac mini.

Thank you for reporting!

Is there any reason, why you use `ffmpeg` (6.0) rather than `ffmpegdecklink` (5.1.2) for `vrecord`?

**Comment by gbagit** [comment]
Frankly, I was unaware that there was another option! The command was narrowed down to be specifically from ffmpeg from another IT member. If there's a way to specifically call ffmpegdecklink or use it within vrecord, I'd be willing to try it to see if it breaks.
