### ISSUE TITLE
cat ... "_ffmpeg_input.log: No such file or directory"

### ISSUE THREAD

**Issue by pjotrek-b** [amiaopensource/vrecord#761]
I'm getting the following non-critical errors, when vrecord tries to cat logfiles *after* capture:

> cat: /home/dva/Videos/vrecord/aux/xxx3_ffv1_ffmpeg_input.log: No such file or directory
> cat: /home/dva/Videos/vrecord/aux/xxx3_ffv1_ffmpeg_input.log: No such file or directory

(Yes, twice the same line)

I've checked the code and I'm wondering if it maybe a typo between mismatching file suffixes:
  * Once it's `_vrecord_input.log`
  * And then it's `_ffmpeg_input.log`

See:
  * https://github.com/amiaopensource/vrecord/blob/0831f7cea2091bb938ba3934bfda49507aef7265/vrecord#L209

  * https://github.com/amiaopensource/vrecord/blob/0831f7cea2091bb938ba3934bfda49507aef7265/vrecord#L2540-L2541

**Comment by pjotrek-b** [comment]
Oh, maybe I should mention that I'm using the "auxiliary" folder feature for capture metadata files (instead of having them next to the captured videos).

**Comment by privatezero** [comment]
Hi @pjotrek-b - It certainly looks like the difference in suffixes there is the root of this (and in looking at the commit history line 209 originally set the suffix to  `_ffmpeg_input.log`, so it looks like 2540 and 2541 just didn't get updated when the change to `_vrecord_input.log` was made.

We'll get a fix in soon! Thanks for noticing and reporting!

**Comment by dericed** [comment]
Yes, oops. I think that was me. I had been thinking that `_ffmpeg_input` isn't a fair suffix, since there's a few inputs in here (bmdtools, ffmpeg, avfctl), so I may have been trying to decide if to standardize to either `_vrecord_input` or `_${input_tool}_input`.
