### ISSUE TITLE
Wishlist: Option to suppress "out of range" highlighting

### ISSUE THREAD

**Issue by kellyhaydon** [amiaopensource/vrecord#77]
It would be great to be able to suppress the highlighting of out-of-(8-bit studio)-range pixels in the right window.

**Comment by dericed** [comment]
?_?

**Comment by dericed** [comment]
The whole point of that pane is to show out-of-broadcast-range pixels. If that is omitted what else should the space be used for?

**Comment by kellyhaydon** [comment]
I wasn't thinking the space should disappear (the two playback windows also
show different frame sizes), just that the highlighting is switched off as
a preference. This could just be my own weirdness, but when digitizing some
amateur and/or art works, especially those on 1/2" open reel, the
highlighting isn't all that helpful and, for me, a distraction. Feel free
to ignore if this isn't something others experience.


*Kelly Haydon | Preservationist*
*415.558.2158 <http://415.558.2158> | kelly@bavc.org
<kelly@bavc.org> | @bavcpreserve <https://twitter.com/BAVCPreserve>*



*Join BAVC in celebrating four decades of empowering storytellers. *
*www.bavc.org/events/big-4-oh <https://bavc.org/events/big-4-oh>*

*Support BAVC today. *
*www.bavc.org/donate <https://bavc.org/donate>*

Archivists can use the power of archives to promote accountability, open
government, diversity, and social justice. In doing so, it is essential to
distinguish objectivity from neutrality. - Howard Zinn

**Comment by kellyhaydon** [comment]
Alternatively, there could be an option for full-swing highlighting?


*Kelly Haydon | Preservationist*
*415.558.2158 <http://415.558.2158> | kelly@bavc.org
<kelly@bavc.org> | @bavcpreserve <https://twitter.com/BAVCPreserve>*



*Join BAVC in celebrating four decades of empowering storytellers. *
*www.bavc.org/events/big-4-oh <https://bavc.org/events/big-4-oh>*

*Support BAVC today. *
*www.bavc.org/donate <https://bavc.org/donate>*

Archivists can use the power of archives to promote accountability, open
government, diversity, and social justice. In doing so, it is essential to
distinguish objectivity from neutrality. - Howard Zinn

**Comment by bturkus** [comment]
I can imagine a situation in which someone would want to set levels and
check brange pixels in passthrough mode, then switch to full screen mode
for capture.

Sent from my iPhone

On Oct 17, 2016, at 8:38 AM, Kelly Haydon <notifications@github.com> wrote:

Alternatively, there could be an option for full-swing highlighting?


*Kelly Haydon | Preservationist*
*415.558.2158 <http://415.558.2158> | kelly@bavc.org
<kelly@bavc.org> | @bavcpreserve <https://twitter.com/BAVCPreserve>*



*Join BAVC in celebrating four decades of empowering storytellers. *
*www.bavc.org/events/big-4-oh <https://bavc.org/events/big-4-oh>*

*Support BAVC today. *
*www.bavc.org/donate <https://bavc.org/donate>*

Archivists can use the power of archives to promote accountability, open
government, diversity, and social justice. In doing so, it is essential to
distinguish objectivity from neutrality. - Howard Zinn

On Mon, Oct 17, 2016 at 8:36 AM, Kelly Haydon <kellyhaydon@bavc.org> wrote:

> I wasn't thinking the space should disappear (the two playback windows
> also show different frame sizes), just that the highlighting is switched
> off as a preference. This could just be my own weirdness, but when
> digitizing some amateur and/or art works, especially those on 1/2" open
> reel, the highlighting isn't all that helpful and, for me, a distraction.
> Feel free to ignore if this isn't something others experience.
>
>
> *Kelly Haydon | Preservationist*
> *415.558.2158 <http://415.558.2158> | kelly@bavc.org
> <kelly@bavc.org> | @bavcpreserve <https://twitter.com/BAVCPreserve>*
>
>
>
> *Join BAVC in celebrating four decades of empowering storytellers. *
> *www.bavc.org/events/big-4-oh <https://bavc.org/events/big-4-oh>*
>
> *Support BAVC today. *
> *www.bavc.org/donate <https://bavc.org/donate>*
>
> Archivists can use the power of archives to promote accountability, open
> government, diversity, and social justice. In doing so, it is essential to
> distinguish objectivity from neutrality. - Howard Zinn
>
> On Mon, Oct 17, 2016 at 7:18 AM, Dave Rice <notifications@github.com>
> wrote:
>
>> The whole point of that pane is to show out-of-broadcast-range pixels. If
>> that is omitted what else should the space be used for?
>>
>> —
>> You are receiving this because you authored the thread.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/amiaopensource/vrecord/issues/
77#issuecomment-254220363>,
>> or mute the thread
>> <https://github.com/notifications/unsubscribe-
auth/AI_8UdunKRIlf5irCPv53rp_BguNhL4Hks5q04OdgaJpZM4KXxjb>
>> .
>>
>
>

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/amiaopensource/vrecord/issues/77#issuecomment-254244403>,
or mute the thread

**Comment by savcampbell** [comment]
Hi Kelly,

We have added a new playback view option for full-swing highlighting.  If you select "Full Range Visual", the display will highlight any pixels that fall outside of the full range of code values, rather than pixels that are out of broadcast range.

**Comment by dericed** [comment]
Hi Kelly, I'm also interested if you see the need for the resulting file to be labelled in metadata as full range instead of broadcast range. After @savcampbell the upper-right highlight pane can guide the user to full range capture but the video file would still be interpreted as broadcast range. Do you intend to make 'full range' recordings via vrecord?

**Comment by kellyhaydon** [comment]
@savcampbell - thank you! I love it.

@dericed - Right now we do not capture in vrecord, only preview, but yes it
makes sense to have "full range" in the metadata for when that fateful day
comes.



*Kelly Haydon | Preservationist*
*415.558.2158 <http://415.558.2158> | kelly@bavc.org
<kelly@bavc.org> | @bavcpreserve <https://twitter.com/BAVCPreserve>*



*Join BAVC in celebrating four decades of empowering storytellers. *
*www.bavc.org/events/big-4-oh <https://bavc.org/events/big-4-oh>*

*Support BAVC today. *
*www.bavc.org/donate <https://bavc.org/donate>*

Archivists can use the power of archives to promote accountability, open
government, diversity, and social justice. In doing so, it is essential to
distinguish objectivity from neutrality. - Howard Zinn

**Comment by dericed** [comment]
> Right now we do not capture in vrecord, only preview

@kellyhaydon what's vrecord missing for you?

**Comment by kellyhaydon** [comment]
Hi Dave -  vrecord is still not reliable for us vis-a-vis audio sync (we do
not convert everything to SDI).


*Kelly Haydon | Preservationist*
*415.558.2158 <http://415.558.2158> | kelly@bavc.org
<kelly@bavc.org> | @bavcpreserve <https://twitter.com/BAVCPreserve>*



*Join BAVC in celebrating four decades of empowering storytellers. *
*www.bavc.org/events/big-4-oh <https://bavc.org/events/big-4-oh>*

*Support BAVC today. *
*www.bavc.org/donate <https://bavc.org/donate>*

Archivists can use the power of archives to promote accountability, open
government, diversity, and social justice. In doing so, it is essential to
distinguish objectivity from neutrality. - Howard Zinn

**Comment by privatezero** [comment]
Hi Kelly!
At what point are the audio sync issues occurring?  Is this during playback monitoring, or are the actual files being generated having sync issues?

**Comment by kellyhaydon** [comment]
I haven't noticed anything during monitoring, only after the file has been
created. I can send you a clip if you'd like. It is "close" and barely
noticeable but definitely several frames off.




*Kelly Haydon | Preservationist*
*415.558.2158 <http://415.558.2158> | kelly@bavc.org
<kelly@bavc.org> | @bavcpreserve <https://twitter.com/BAVCPreserve>*



*Join BAVC in celebrating four decades of empowering storytellers. *
*www.bavc.org/events/big-4-oh <https://bavc.org/events/big-4-oh>*

*Support BAVC today. *
*www.bavc.org/donate <https://bavc.org/donate>*

Archivists can use the power of archives to promote accountability, open
government, diversity, and social justice. In doing so, it is essential to
distinguish objectivity from neutrality. - Howard Zinn

**Comment by privatezero** [comment]
Thanks Kelly! A clip would be great!

**Comment by privatezero** [comment]
Also- are these sync issues recent or have you been having them for a while?

**Comment by kellyhaydon** [comment]
I'll send a clip your way soon; we have always had these problems with
vrecord.


*Kelly Haydon | Preservationist*
*415.558.2158 <http://415.558.2158> | kelly@bavc.org
<kelly@bavc.org> | @bavcpreserve <https://twitter.com/BAVCPreserve>*



*Join BAVC in celebrating four decades of empowering storytellers. *
*www.bavc.org/events/big-4-oh <https://bavc.org/events/big-4-oh>*

*Support BAVC today. *
*www.bavc.org/donate <https://bavc.org/donate>*

Archivists can use the power of archives to promote accountability, open
government, diversity, and social justice. In doing so, it is essential to
distinguish objectivity from neutrality. - Howard Zinn

**Comment by savcampbell** [comment]
Doing some cleanup and closing this issue for now, since full-swing highlighting has been added.  As other issues have been brought up here, I have created new tickets for audio sync issues ( #88 ) and adding metadata for full range captures ( #87 ).
