### ISSUE TITLE
Audio mapping to QC Graphs

### ISSUE THREAD

**Issue by swdrop** [amiaopensource/vrecord#773]
Hi - I incorrectly set the vRecord audio input channels to 1&2 when my audio was on channels 3&4, so the output video doesn’t have any audio (understandably), however the QC Graphs output does show audio levels. When I recaptured the video with the correct audio channels, the output QC Graphs look the same as the first attempt. 

Do all 4 audio channels feed the QC Graphs output regardless of input setting? If so, changing it to the input channels would be helpful as it's a good quick visual check to confirm that audio was recorded.

Thanks!

**Comment by privatezero** [comment]
Hi @swdrop thanks for reporting! This is probably a side effect of how the input gets split for playback and file creation with slightly different things applied to both - I'll take a look and see if there is a clean solution.

**Comment by swdrop** [comment]
Thanks for looking into it!

**Comment by privatezero** [comment]
Hi @swdrop - I think I have a fix for this in https://github.com/amiaopensource/vrecord/pull/774. Go ahead and test that branch if you would like - it should get rolled into a release soonish.
