### ISSUE TITLE
add channel 3/4 -> 1st track stereo mapping

### ISSUE THREAD

**Issue by dericed** [amiaopensource/vrecord#78]
The use case is for when a DPS-575AV has Umatic audio wired to audio input 1/2 and VHS audio wired to audio input 3/4. If vrecord can simply map only 3/4 to a stereo first track then we can avoid the need for a hardware based audio switcher.

**Comment by privatezero** [comment]
Added with https://github.com/amiaopensource/vrecord/commit/294eeaf8c7428e3bcfd9573a38abed273333e99f.  Has been merged and tested so closing this!
