### ISSUE TITLE
Raw Video Error

### ISSUE THREAD

**Issue by libbyhopfauf** [amiaopensource/vrecord#8]
Just in case anyone else has stumbled across this issue as well, here is my experience. 

I will run VRecord and everything opens/runs smoothly, but once I close out of the window to end the capture, I receive the following warning (see rawvideo error in red at bottom of image below). 

This is just caused by closing the window and stopping the recording. FFmpeg just complains because it received a partial frame when I closed it. 

I tried this several different times, using the different options and the two that were successful (despite this error) were the following:
- 10 bit and Uncompressed
- 8 bit and FFV1 version 3

![test3](https://cloud.githubusercontent.com/assets/13877631/10494145/8353b222-7269-11e5-9515-a7c01c09429f.png)
![test4](https://cloud.githubusercontent.com/assets/13877631/10494144/83505f8c-7269-11e5-82fa-1d47d7138567.png)

**Comment by dericed** [comment]
I think @jfarbowitz addressed this in documentation here: https://github.com/amiaopensource/vrecord/blob/master/README.md#ffmpeg-error-message. When the recording is stopped it is unlikely to be stopped exactly on a frame boundary in the data stream, thus a partial frame will be left out which is what the warning is about.
