### ISSUE TITLE
FFmpeg errors appear when creating an MP4 sidecar file. 

### ISSUE THREAD

**Issue by iamdamosuzuki** [amiaopensource/vrecord#804]
The following error appears when creating an MP4 sidecar file:

`no ICC profile found, will write nclx/nclc colour info instead`

**Comment by dericed** [comment]
I think this is resolved in https://github.com/amiaopensource/vrecord/commit/e3f555df9f125d6df404ddb660eee446caca1f6f by applying the color info to the mp4 output. And the other informational messages from the libx264 and aac encoder are silenced via . https://github.com/amiaopensource/vrecord/pull/807/commits/7b158e7d80cec9012f0823ac8d71875589b7b85c

**Comment by iamdamosuzuki** [comment]
Tested with https://github.com/amiaopensource/vrecord/commit/7b158e7d80cec9012f0823ac8d71875589b7b85c. This is working great! thanks so much
