### ISSUE TITLE
Conversion

### ISSUE THREAD

**Issue by mpesetsky** [amiaopensource/vrecord#818]
Can lower resolution video files be up-converted to mkv files? If so, which software is best? Or, do mkv files need to be created via a live capture device?

Thanks,
Mark

**Comment by retokromer** [comment]
Capture directly in Matroska (the .mkv files)! File conversions are at best the same quality as the source file, but usually lower quality.

**Comment by mpesetsky** [comment]
What I figured, thanks....Just getting set up with this new system and process of capturing for our archival library.

**Comment by dericed** [comment]
Hi @mpesetsky, maybe this is out of scope for this project but there's some info on rewrapping to matroska at ffmprovisor at https://amiaopensource.github.io/ffmprovisr/#rewrap.
