### ISSUE TITLE
access mp4 creating 8-channel audio from 2-channel source

### ISSUE THREAD

**Issue by svhartzell** [amiaopensource/vrecord#820]
Using the Access mp4 feature in vrecord encodes what I believe is 7.1 surround sound, even though the mkv has the original 2-channels of stereo from the source. The vrecord_input.log says this:

`Guessed Channel Layout for Input Stream #0.0 : 7.1
[Parsed_pan_4 @ 0x60000221c6e0] [SWR @ 0x128850000] Input channel layout has a different number of channels than the number of used channels, ignoring layout
[flac @ 0x146e09ea0] encoding as 24 bits-per-sample
av_interleaved_write_frame(): Broken pipe
Error writing trailer of pipe:: Broken pipe
Error closing file pipe:: Broken pipe
`

 Here's the mediainfo  for the mkv's audio:

> Audio
> ID                                       : 2
> Format                                   : FLAC
> Format/Info                              : Free Lossless Audio Codec
> Codec ID                                 : A_FLAC
> Duration                                 : 57 min 36 s
> Bit rate mode                            : Variable
> Channel(s)                               : 2 channels
> Channel layout                           : L R
> Sampling rate                            : 48.0 kHz
> Bit depth                                : 24 bits
> Compression mode                         : Lossless
> Writing library                          : Lavc59.37.100 flac
> Default                                  : No
> Forced                                   : No
> MD5 of the unencoded content             : 0F6E33CA5F20D782ED776560CE20C1F4

And for the mp4 from vrecord:

> Audio
> ID                                       : 2
> Format                                   : AAC LC
> Format/Info                              : Advanced Audio Codec Low Complexity
> Codec ID                                 : mp4a-40-2
> Duration                                 : 57 min 36 s
> Source duration                          : 57 min 36 s
> Bit rate mode                            : Constant
> Bit rate                                 : 192 kb/s
> Channel(s)                               : 8 channels
> Channel layout                           : C L R Ls Rs Lw Rw LFE
> Sampling rate                            : 48.0 kHz
> Frame rate                               : 46.875 FPS (1024 SPF)
> Compression mode                         : Lossy
> Stream size                              : 79.3 MiB (6%)
> Source stream size                       : 79.3 MiB (6%)
> Default                                  : Yes
> Alternate group                          : 1
> Encoded date                             : 2024-08-20 15:51:51 UTC
> Tagged date                              : 2024-08-20 15:51:51 UTC
> 

Thanks a bunch!

[NV1427C65F426_1989b_Videotape_10_1_capture_options.log](https://github.com/user-attachments/files/16679270/NV1427C65F426_1989b_Videotape_10_1_capture_options.log)

**Comment by privatezero** [comment]
thanks for reporting @svhartzell! It looks like the raw track layout from the blackmagic device is getting passed to the access file. I think I have a fix for that in https://github.com/amiaopensource/vrecord/pull/821 , just need to test it a bit more.

**Comment by privatezero** [comment]
@svhartzell We've merged this in, so the issue should be fixed in the next release. Thanks again for reporting!
