### ISSUE TITLE
Automatically create SRT or WebVTTfiles from SCC files when caption data is captured

### ISSUE THREAD

**Issue by iamdamosuzuki** [amiaopensource/vrecord#822]
Right now vrecord will create an SCC file when caption data is captured. Is it possible for it to create SRT or WebVTT files as well? Perhaps checkboxes for SRT and WebVTT in the _config_ tab, so the user can select which, if any, to create. thanks!

**Comment by dericed** [comment]
done in https://github.com/amiaopensource/vrecord/pull/825
