### ISSUE TITLE
Remove encoding specific suffixes 

### ISSUE THREAD

**Issue by iamdamosuzuki** [amiaopensource/vrecord#823]
Currently vrecord adds __ffv1_ and __j2k_ suffixes to files using those encodings. This is independent of the user-selected suffixes or prefixes. Is it possible to turn this off, or remove it entirely? I'm not sure if anyone is using this option, and it forces users into a specific file naming convention that may not be used at their organization.

**Comment by dericed** [comment]
I'd support removing the encoding specific suffixes as well (the `_j2k` and `_ffv1` ones).

**Comment by privatezero** [comment]
@iamdamosuzuki if you click the 'Disable suffixes' box next to the options for user specified suffixes that will turn off the appending of the _ffv2/_j2k suffixes.

If nobody wants/needs the suffixes I'd definitely support getting rid of them entirely though!

**Comment by iamdamosuzuki** [comment]
@privatezero Thanks for the info! I thought I had tested that, but realized that flipping the "Disable Suffixes" toggle doesn't refresh the filename itself, you also need to select the encoding parameter too, 

Is it possible to make that checkbox refresh the filename upon user entry? 

Additionally, I'd be interested to know if anyone is using those suffixes. Might it be better to either of these options deployed if most people aren't using them. 
 - Default to having the "Disable Suffixes" checkbox turned on
 - change the checkbox to say "Enable Suffixes" and have it default to off

**Comment by privatezero** [comment]
Yeahhh the refresh triggers for the name seem to be a UX issue for sure. I found on my end that after clicking the box if you retype the name it will correctly generate it without the suffix...but I'd have to look at what does and doesn't trigger the refresh currently.

I think we should definitely take a look at making that option to disable more clearly and agree with your suggestion to make them off by default. But yeah, also if really nobody is using them we could just skip all that and get rid of them entirely!

**Comment by retokromer** [comment]
I suggest keeping the suffixes, but flipping the switch (enable suffixes rather than disable suffixes).

**Comment by privatezero** [comment]
Give this a test: https://github.com/amiaopensource/vrecord/pull/824 and see if that seems like an optimal solution or not

**Comment by iamdamosuzuki** [comment]
Yes, this is a great solution. Thank you

**Comment by privatezero** [comment]
I also poked a bit at having it more correctly regenerate the displayed output file name when the box is checked/unchecked but I think that'll have to wait for a future PR. The triggers are pretty wonky - right now it is actually incorrectly set to trigger on a key press and it really should be a mouse click. But changing it to a mouse click actually makes the behavior worse because it appears to be regenerating the output file name _before_ it updates the associated variables so it actually ends up displaying the opposite of the new status that it should.

**Comment by dericed** [comment]
done in https://github.com/amiaopensource/vrecord/pull/824, thx @iamdamosuzuki @privatezero
