### ISSUE TITLE
vrecord won't launch if framemd5 option is not enabled

### ISSUE THREAD

**Issue by villereal** [amiaopensource/vrecord#83]
When I try to run vrecord without framemd5 on I get the following error twice in Terminal window, and playback window fails to launch: 

cat: /Users/srv3f/Desktop/_ffmpeg_*.log: No such file or directory

**Comment by dericed** [comment]
I think the issue pertains to the unquoted variables at https://github.com/amiaopensource/vrecord/blob/78dc39a8c8712fd5854fb5c759ecf1f735e1163d/vrecord#L1174-L1175.

**Comment by privatezero** [comment]
Made changes at https://github.com/amiaopensource/vrecord/pull/84/commits/a2826af0adf546df6b11423d37c8539b04675dac and https://github.com/amiaopensource/vrecord/pull/84/commits/b027dd0c3762ba04931dfb1fc9ab602b3b18ef93 that should take care of this.

**Comment by savcampbell** [comment]
Tested the changes today and the issue appears to be resolved
