### ISSUE TITLE
VRecord Not Recording Audio (Reopening Issue - Closed Incorrectly)

### ISSUE THREAD

**Issue by SoFrans** [amiaopensource/vrecord#845]
Hi, 

During the hiatus due to the FFV1 glitch, we had to revert back to Uncompressed capture, and I was capturing video. Unfortunately, going back, I have now realized that no audio was captured for these video clips. I just tested it and although there is video and audio for Uncompressed in passthrough and even in recording, it seems when the video gets generated to an mov it is gone. I cannot attach the report this moment, because I do not have my phone to do the 2FA for GitHub on my computer, so I will have to upload it in a couple hours. We are using the 24 bit PCM setting and the top mixdown option. It had been working prior to the recent fix, so not sure if something got wacky there.

Thanks, 
Sophia

((Originally closed thinking I had figured it out.  Freshly installed VRecord without changes and still having issues.))

_Originally posted by @SophiaFrancis1 in https://github.com/amiaopensource/vrecord/issues/844_

**Comment by dericed** [comment]
Seeing the ffmpeg log would be helpful. Which container were you using?

**Comment by SophiaFrancis1** [comment]
Hi Dave,

I tried using both .MKV and also .MOV for the containers, but no luck with either of them.

Thanks,
Sophia



Sophia Francis (she/her)

Digitization Assistant – Digital Products and Data Curation

Northwestern University Libraries

Northwestern University

***@***.******@***.***>

847-467-5695



[cid:4e6b4247-f768-4293-b227-3be4ccbff6e2]



________________________________

**Comment by privatezero** [comment]
Hi @SophiaFrancis1, thanks for sharing those logs! I noticed that you are capturing the audio with the settings `2 Stereo Tracks (Channels 1 & 2 -> 1st Track Stereo, Channels 3 & 4 -> 2nd Track Stereo)`. Is it possible that your audio is getting mapped to the wrong stereo track? If you open your file in something like VLC you should be able to switch between the first and second stereo tracks.

If you post a screenshot of running a video in `Audio + Video` mode that could also help us determine which channels your audio is coming through on via the meters that are in that visualization.

**Comment by SophiaFrancis1** [comment]
Hi, 

That is the setting that we have always utilized (not entirely sure why as that pre-dates my time where I work). Switching to the 2nd track in VLC didn't do anything unfortunately. But anyways, here is a screenshot :)
<img width="1428" alt="Screenshot 2024-10-28 at 1 07 30 PM" src="https://github.com/user-attachments/assets/850ec1f9-5bbb-4f2f-9eb1-1cb836a7c4f8">

**Comment by privatezero** [comment]
Hi @SophiaFrancis1 to do a swap in the order of two stereo tracks you should be able to use FFmpeg with something like:
`ffmpeg -i INPUT.mkv -c copy -map 0:v:0 -map 0:a:1 -map 0:a:0 OUTPUT.mkv`. If you want to do something like get rid of the first stereo track and keep the second you can just drop the `-map 0:a:0` part.

As for why it was set up like that, not sure about the specifics of your system, but is it possible that someone was capturing tapes that had 4 channels? 

For the example you gave a screen shot of, is there nothing audible on the second stereo pair? (Like any hum or tone?) Your volume levels for that second pair are showing higher than I'd expect for something totally empty...although the phase of 1.00 does also suggest an empty track.

**Comment by SophiaFrancis1** [comment]
We are typically capturing both 2 norm tracks and 2 HiFi tracks if present so we just default to having all on. Technically I believe that video I posted above should have HiFi. I believe channels 1 and 2 are the HIFI and the norms are 3 and 4. Are we perhaps not taking the correct approach with capturing -- perhaps I'm mis-interpreting the channel mapping? Channels 3 and 4 do move around a bit but the phase meter doesn't really do much (maybe it's a Vrecord thing?). I would be happy to do a screen record or something similar and share it if that would be helpful.

**Comment by privatezero** [comment]
Hi @SophiaFrancis1 ah great - that all makes sense then! I didn't realize you were grabbing HiFi as well in that example - I think you should be good as long as things are wired up so that whichever pair you want to come first in the file is going into inputs 1 and 2.

**Comment by privatezero** [comment]
Closing this as I think it is resolved - go ahead and reopen if that isn't the case!
