### ISSUE TITLE
cowsay

### ISSUE THREAD

**Issue by retokromer** [amiaopensource/vrecord#848]
FYI: Homebrew says regarding `cowsay`:

>Deprecated because it has an archived upstream repository!
>It will be disabled on 2024-11-22.

**Comment by dericed** [comment]
I'm planning to replace `cowsay` with `banner`

**Comment by dericed** [comment]
or perhaps the `say` command on mac would be better `say -v "Bad News" You have dropped frames ... Your file is outta sync ... Your hard drive is full `

**Comment by retokromer** [comment]
Or just with `echo` resp. `printf`?

**Comment by dericed** [comment]
```
 ___________________
< Love Live Cowsay! >
 -------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||
```

https://github.com/Homebrew/homebrew-core/commit/4e775971e427fb625a3c06a0f8620a2cccca262e
