### ISSUE TITLE
segmentation fault when creating a QCTools report for a file with 2 Stereo Audio Channels

### ISSUE THREAD

**Issue by iamdamosuzuki** [amiaopensource/vrecord#851]
I get an error when attempting to capture a 4 Channel audio file (2x Stereo Channels) with vrecord set to create a QCTools report after capture. Creating the QCTools file after capture works perfectly well if done on a file with a single stereo channel. Here's te error i Get, you can see the segmentation fault near the end. 

```
Hit enter to start recording

Close the playback window to stop recording.
Guessed Channel Layout for Input Stream #0.0 : 7.1
[Parsed_pan_1 @ 0x7fb993115bc0] [SWR @ 0x7fb980ec8000] Input channel layout has a different number of channels than the number of used channels, ignoring layout
[Parsed_pan_0 @ 0x7fb993115840] [SWR @ 0x7fb980ee0000] Input channel layout has a different number of channels than the number of used channels, ignoring layout
Input #0, matroska,webm, from 'pipe:':
  Metadata:
    ENCODER         : Lavf59.27.100
  Duration: N/A, start: 0.000000, bitrate: 9216 kb/s
  Stream #0:0: Audio: pcm_s24le, 48000 Hz, 8 channels, s32 (24 bit), 9216 kb/s
    Metadata:
      ENCODER         : Lavc59.37.100 pcm_s24le
  Stream #0:1: Video: v210 (v210 / 0x30313276), yuv422p10le(bottom first), 720x486, 29.97 fps, 29.97 tbr, 1k tbn
[Parsed_pan_0 @ 0x7f78ff7181c0] Pure channel mapping detected: 0 1 2 3
[Parsed_pan_0 @ 0x7f78ff71d240] Pure channel mapping detected: 0 1 2 3
[Parsed_pan_6 @ 0x7fb99311b980] [SWR @ 0x7fb9811a8000] Input channel layout has a different number of channels than the number of used channels, ignoring layout
[Parsed_pan_5 @ 0x7fb99311b640] [SWR @ 0x7fb9811c0000] Input channel layout has a different number of channels than the number of used channels, ignoring layout
 300.28 A-V:  0.180 fd=  56 aq=    0KB vq=    0KB sq=    0B f=0/0   
mv: /Volumes/CaptureDisk01/20251105/Test03_vrecord_input.log: set owner/group (was: 501/0): Operation not permitted
mv: /Volumes/CaptureDisk01/20251105/Test03_vitc_frame_timecodes.txt: set owner/group (was: 501/0): Operation not permitted
mv: /Volumes/CaptureDisk01/20251105/Test03_frame_eia608data.txt: set owner/group (was: 501/0): Operation not permitted
qcli dev build, Oct 12 2023 07:09:34
filters selected: signalstats aphasemeter astats ssim 

analyzing input file... /Volumes/CaptureDisk01/20251105/Test03.mkv
/usr/local/bin/vrecord: line 2836:  7673 Segmentation fault: 11  "${QCLI_COMMAND_FILE[@]}"
Vrecord is analyzing your video file. Please be patient.
qctools XML /Volumes/CaptureDisk01/20251105/Test03.mkv.qctools.mkv is empty or does not exist!
QCTools analysis is complete.
Checking file conformance against FFV1 video policy...
 2024-11-05T16:12:18 - File passed policy check for FFV1 video.
```

**Comment by iamdamosuzuki** [comment]
I did some further testing and found that this is a qcli error. I've made a ticket here: https://github.com/bavc/qctools/issues/842

Let me know if you want me to close this ticket.

**Comment by privatezero** [comment]
thanks for the further testing @iamdamosuzuki! I suppose we might as well leave this open for the time being so people who are trying to use this feature might find it. We'll just have to remember to close once this is resolved upstream.

**Comment by henryborchers** [comment]
@iamdamosuzuki I might be able to take a look at this if you can help walk me through a setting up a repeatable test case. Are you going to be at AMIA?

**Comment by iamdamosuzuki** [comment]
@henryborchers I will be! I'll see you there. 

In the meantime I'll work on creating a few files that break qcli. I'll then upload those to google drive so you can test them you. thanks!

**Comment by iamdamosuzuki** [comment]
Files are being uploaded here: https://drive.google.com/drive/folders/1PVBl39L6SZGVp7nKjTQyELvNeX_MeAvd?usp=sharing

It's broken into three folders:

- QCLI Works: These are files where QCLI worked properly, creating QCTools reports
- QLIC Breaks: These are files where QCLI broke due to a segmentation fault
- Vrecord Breaks: This is a separate file entirely, but these files couldn't even be created due to an error by vrecord. Mostly just here for safe keeping, I'll make a ticket about this soon.

**Comment by iamdamosuzuki** [comment]
This has been solved in the QCTools code with this PR: https://github.com/bavc/qctools/pull/845
