### ISSUE TITLE
Error in h.264 encoding for access copy: "height not divisible by 4 (720x486)"

### ISSUE THREAD

**Issue by pjotrek-b** [amiaopensource/vrecord#854]
Hi everyone :smile: 

We only have a few NTSC tapes in our collections every once in a while...
However, if I want to create access copies **I get the error that height 486px is not divisible by 4**
(so that's AFAIK why `720x480` exist)

vrecord is creating files for NTSC with `720x486` pixel resolution.

How do you deal with creating h.264 (libx264) from that archive material?
Do you crop to 480 height?

I've read this:
[Are we using the correct PAR settings? #689 ](https://github.com/amiaopensource/vrecord/issues/689)
(but that doesn't change the fact that my vrecord-captured NTSC files are 720x486... :fearful:)

Any suggestions greatly welcome!

**Comment by pjotrek-b** [comment]
I saw in vrecord's script code, that when capturing directly to h264, the video is indeed cropped:

```
DECKLINK_FPS="30000/1001"
if [[ "${VIDEO_CODEC_CHOICE}" = "h264" ]] ; then
    RECORDINGFILTER+="crop=w=720:h=480:x=0:y=4,"
    MIDDLEOPTIONS+=(-x264opts bff)
fi
```

**Comment by privatezero** [comment]
Closing as I think the question was answered - reopen if that is not the case!

**Comment by pjotrek-b** [comment]
The above code is cropping *when capturing directly to h.264*.
But for ffv1 (=720x486), you mean the common workflow for US NTSC is to require special intervention (crop to 480 height) for converting to h.264?

And then archival/access copy having different resolutions?

I'm surprised to hear that.
Sounds like a lot of extra effort to handle this systematically.

Is anyone capturing directly to 480 height?
Since this seems to be mandatory for anyone having h.264/mp4 as archival format.

**Comment by privatezero** [comment]
CUNY has a good example of handling resolutions systematically as part of their [micoservices](https://github.com/mediamicroservices/mm/blob/master/makederiv#L531).  Yes, I think many workflows that capture at 720x486 implement cropping in access file generation - if even just to crop out some of the head switching noise to make things more palatable to online viewers.
