### ISSUE TITLE
Earliest macos supported

### ISSUE THREAD

**Issue by jf-blanco** [amiaopensource/vrecord#861]
Sorry if this has been already answered or if this is not the place to ask this. But I have not found another place to do it. The thing is that I'm building a setup and the core of it is gonna be an old imac 2012 that supports till macOS 10.15 Catalina (2019). And my question / worries is if this is gonna be a limitation in the near future to use this old computer with vrecord.

**Comment by retokromer** [comment]
Sorry, I cannot answer your question. The information I can give is that until this Summer we were running `vrecord` on one remaining macOS 10.15.7 on a Mac mini (Late 2012). Today the oldest one we have is a Mac mini (Late 2014) running under 12.7.6.

**Comment by retokromer** [comment]
It’s the contrary: the 2014 model has two Thunderbolt 2 ports, while the 2012 model has one FireWire 800 port and one Thunderbolt 1 port. Yet, yes, the converter FireWire 800-Thunderbolt 2 works fine.
