### ISSUE TITLE
Add metadata for full range recordings

### ISSUE THREAD

**Issue by savcampbell** [amiaopensource/vrecord#87]
Since vrecord now has a playback view option for full range capture, this should be reflected in metadata of the resulting video files. Metadata should specify whether a video file should be interpreted as broadcast range or full range.

**Comment by dericed** [comment]
With https://github.com/amiaopensource/vrecord/pull/90, vrecord now specifies that mkv (and maybe mov) are to be interpreted as broadcast range (in https://github.com/amiaopensource/vrecord/blob/d4a2d770de6f9411fe65aebce46d4552068839ab/vrecord#L1117). A full range option could be done by conditionally changing this to `-color_range jpeg` where relevant.
