### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by retokromer** [amiaopensource/vrecord#99]
Instead of the customised error message generated by vrecord at https://github.com/amiaopensource/vrecord/blob/6c903dd3483a408648f3e7f5f2545a8fcf065891/vrecord#L51 I got this one from Bash:

```
[21:30:20]reto@Castor:~/Desktop$ vrecord -y
/usr/local/bin/vrecord: illegal option -- y
/usr/local/bin/vrecord: line 51: report: command not found

vrecord 
vrecord will record a file via the Blackmagic SDK and bmdtools. It is an interactive script and will create 8 or 10-bit video files.
Dependencies: 
Usage: vrecord [ -h ]
  -h ( display this help menu )
  -e ( edit the configuration file before recording )
  -r ( enable record mode [default] )
  -p ( enable passthrough mode where the video signal coming into the computer can be monitored, but not written to a file. Useful for testing equipment and setting up a tape to bars. )
  -a ( enable audio passthrough mode. Identical to passthrough except for the addition of audio bars. Note: Will eventually lag and crash if left on too long)
  -x ( reset the configuration, this will clear the default configuration file at /Users/reto/.vrecord.conf and create a new one)

Installation help:
To install (on a Mac with Homebrew package manager installed) run these commands:
$ brew update
$ brew tap amiaopensource/amiaos
$ brew install vrecord
[21:30:46]reto@Castor:~/Desktop$ 
```

[BTW: The variable `$version`, used at https://github.com/amiaopensource/vrecord/blob/6c903dd3483a408648f3e7f5f2545a8fcf065891/vrecord#L22 is not initialised.]

**Comment by privatezero** [comment]
Looks like there might be issues because the report function is defined later on in the script?
https://github.com/amiaopensource/vrecord/blob/master/vrecord#L171

**Comment by retokromer** [comment]
The trailing ":" in https://github.com/amiaopensource/vrecord/commit/175a59a9742892e90b99259e2095cb1b352e3f2b#diff-b4a43d9cc5c10eaaac3b127ec6c5b7caL43 silences the Bash error and uses our handle. (Therefore I usually add this on my side.) In the current version the script’s own error message is **not** prompted.

I have to check this more in detail tomorrow.

**Comment by retokromer** [comment]
@privatezero This error is not dependent on the position of the `report` function inside the script, because the same behaviour occurs also if I move it to the beginning, just after the shebang.

**Comment by retokromer** [comment]
The value `q` or `Q` are not passed to (therefore or interpreted by) `lookup_video_input` https://github.com/amiaopensource/vrecord/blob/018321256a5b378c8ba0bd8c6a597dc25b5ddb30/vrecord#L225

**Comment by retokromer** [comment]
The admissible values for:

https://github.com/amiaopensource/vrecord/blob/018321256a5b378c8ba0bd8c6a597dc25b5ddb30/vrecord#L225

are defined in:

https://github.com/amiaopensource/vrecord/blob/018321256a5b378c8ba0bd8c6a597dc25b5ddb30/vrecord#L63

where `q` and `Q` are **not** present. (They just would become additional numbers to chose in.) And similar for all the other settings.

We could add an item "Quit" and quit with a quitting message when the corresponding number is passed, but it should exist a more elegant solution.
